// Code generated by gqlc dev. DO NOT EDIT.

package writemanyprojectionentity

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const markAdultsQueryText = `MATCH (p:Person) WHERE p.age >= $minAge SET p.checked = true RETURN p`

// MarkAdults executes the MarkAdults query.
//
//	MATCH (p:Person) WHERE p.age >= $minAge SET p.checked = true RETURN p
func (q *Queries) MarkAdults(ctx context.Context, minAge int64) ([]Person, error) {
	records, err := q.db.run(ctx, markAdultsQueryText, map[string]any{"minAge": minAge}, neo4j.AccessModeWrite)
	if err != nil {
		return nil, err
	}
	out := make([]Person, 0, len(records))
	for _, record := range records {
		node, isNil, err := neo4j.GetRecordValue[dbtype.Node](record, "p")
		if err != nil {
			return nil, fmt.Errorf("MarkAdults: decode column %q: %w", "p", err)
		}
		if isNil {
			return nil, fmt.Errorf("MarkAdults: column %q is non-nullable but arrived null", "p")
		}
		value, err := decodePerson(node)
		if err != nil {
			return nil, fmt.Errorf("MarkAdults: decode column %q: %w", "p", err)
		}
		out = append(out, value)
	}
	return out, nil
}
