// Code generated by gqlc dev. DO NOT EDIT.

package entitypropertyshadowsdecoderlocal

import "context"

type ReadQuerier interface {
	OneMarker(ctx context.Context) (Marker, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
