// Code generated by gqlc dev. DO NOT EDIT.

package writeexeczeroparam

import (
	"context"
	"fmt"
)

const truncatePeopleQueryText = `MATCH (p:Person) DELETE p`

// TruncatePeople executes the TruncatePeople query.
//
//	MATCH (p:Person) DELETE p
func (q *queries) TruncatePeople(ctx context.Context) error {
	stmt, err := q.cypherStmt("$gqlc$", truncatePeopleQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, "{}"); err != nil {
		return fmt.Errorf("TruncatePeople: %w", err)
	}
	return nil
}
