// Code generated by gqlc dev. DO NOT EDIT.

package writeexecfloat32param

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Height float32
	Id     int64
	Tall   bool
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing per-property nullability against the schema.
func decodePerson(node dbtype.Node) (Person, error) {
	var out Person
	height, err := neo4j.GetProperty[float64](node, "height")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Height: %w", err)
	}
	out.Height = float32(height)
	id, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = id
	tall, err := neo4j.GetProperty[bool](node, "tall")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Tall: %w", err)
	}
	out.Tall = tall
	return out, nil
}
