// Code generated by gqlc dev. DO NOT EDIT.

package propertyduration

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Span corresponds to the Span node type.
type Span struct {
	Elapsed dbtype.Duration
	Id      int64
}

// decodeSpan decodes a driver dbtype.Node into a Span struct,
// enforcing per-property nullability against the schema.
func decodeSpan(node dbtype.Node) (Span, error) {
	var out Span
	value0, err := neo4j.GetProperty[dbtype.Duration](node, "elapsed")
	if err != nil {
		return Span{}, fmt.Errorf("decode Span.Elapsed: %w", err)
	}
	out.Elapsed = value0
	value1, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Span{}, fmt.Errorf("decode Span.Id: %w", err)
	}
	out.Id = value1
	return out, nil
}
