// Code generated by gqlc dev. DO NOT EDIT.

package propertyduration

import "context"

type ReadQuerier interface {
	Spans(ctx context.Context) ([]Span, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
