// Code generated by gqlc dev. DO NOT EDIT.

package float32column

import (
	"fmt"
	"math"
	"strconv"
	"strings"
)

// Person corresponds to the Person node type.
type Person struct {
	Height float32
	Id     int64
}

// agtypeFloat64 decodes an agtype float scalar. The float parser reads
// it rather than the JSON decoder because agtype's float vocabulary is
// IEEE 754's: NaN, Infinity and -Infinity are values AGE emits and JSON
// has no spelling for. A value carrying the ::numeric annotation is one
// AGE evaluated in arbitrary precision, and lands on the nearest
// float64.
func agtypeFloat64(raw []byte) (float64, error) {
	out, err := strconv.ParseFloat(strings.TrimSuffix(string(raw), "::numeric"), 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype float: %w", raw, err)
	}
	return out, nil
}

// agtypeFloat32 decodes an agtype float into the narrower width,
// refusing a value that overflows to an infinity the stored value did
// not hold.
//
// Precision loss is NOT refused: FLOAT32 is approximate and every
// in-range float64 rounds to reach it. The test is the invented infinity
// rather than a comparison against math.MaxFloat32, because a float64
// strictly greater than MaxFloat32 can still round DOWN to it — that
// value is representable and a magnitude test would refuse it. An
// infinity or a NaN the store already held passes through unchanged.
func agtypeFloat32(raw []byte) (float32, error) {
	v, err := agtypeFloat64(raw)
	if err != nil {
		return 0, err
	}
	out := float32(v)
	if math.IsInf(float64(out), 0) && !math.IsInf(v, 0) {
		return 0, fmt.Errorf("gqlc: value %g does not fit the declared float32 width", v)
	}
	return out, nil
}
