// Code generated by gqlc dev. DO NOT EDIT.

package float32column

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const personHeightQueryText = `MATCH (p:Person) RETURN p.height AS h`

// PersonHeight executes the PersonHeight query.
//
//	MATCH (p:Person) RETURN p.height AS h
func (q *Queries) PersonHeight(ctx context.Context) (float32, error) {
	records, err := q.db.run(ctx, personHeightQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return 0, err
	}
	if len(records) == 0 {
		return 0, ErrNoRows
	}
	if len(records) > 1 {
		return 0, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[float64](records[0], "h")
	if err != nil {
		return 0, fmt.Errorf("PersonHeight: decode column %q: %w", "h", err)
	}
	if isNil {
		return 0, fmt.Errorf("PersonHeight: column %q is non-nullable but arrived null", "h")
	}
	return float32(value), nil
}
