// Code generated by gqlc dev. DO NOT EDIT.

package queryparamshadowsemittedname

import (
	"context"
	"fmt"
)

const personByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt RETURN p.name`

// PersonByStmt executes the PersonByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt RETURN p.name
func (q *queries) PersonByStmt(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"stmt": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByStmt: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByStmt: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByStmt: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args RETURN p.name`

// PersonByArgs executes the PersonByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args RETURN p.name
func (q *queries) PersonByArgs(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"args": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByArgs: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByArgs: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByArgs: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	return out, nil
}

const personByRowsQueryText = `MATCH (p:Person) WHERE p.name = $rows RETURN p.name`

// PersonByRows executes the PersonByRows query.
//
//	MATCH (p:Person) WHERE p.name = $rows RETURN p.name
func (q *queries) PersonByRows(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRowsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"rows": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByRows: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByRows: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByRows: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	return out, nil
}

const personByRaw0QueryText = `MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name`

// PersonByRaw0 executes the PersonByRaw0 query.
//
//	MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name
func (q *queries) PersonByRaw0(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRaw0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"raw0": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByRaw0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByRaw0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByRaw0: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByValue0QueryText = `MATCH (p:Person) WHERE p.name = $value0 RETURN p.name`

// PersonByValue0 executes the PersonByValue0 query.
//
//	MATCH (p:Person) WHERE p.name = $value0 RETURN p.name
func (q *queries) PersonByValue0(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByValue0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"value0": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByValue0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByValue0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByValue0: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const deleteByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt DELETE p`

// DeleteByStmt executes the DeleteByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt DELETE p
func (q *queries) DeleteByStmt(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", deleteByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"stmt": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("DeleteByStmt: %w", err)
	}
	return nil
}

const deleteByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args DELETE p`

// DeleteByArgs executes the DeleteByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args DELETE p
func (q *queries) DeleteByArgs(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", deleteByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"args": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("DeleteByArgs: %w", err)
	}
	return nil
}

const constShadowOneQueryText = `MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name`

// ConstShadowOne executes the ConstShadowOne query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name
func (q *queries) ConstShadowOne(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", constShadowOneQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"constShadowOneQueryText": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ConstShadowOne: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ConstShadowOne: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ConstShadowOne: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ConstShadowOne: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const constShadowManyQueryText = `MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name`

// ConstShadowMany executes the ConstShadowMany query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name
func (q *queries) ConstShadowMany(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", constShadowManyQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"constShadowManyQueryText": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("ConstShadowMany: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("ConstShadowMany: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("ConstShadowMany: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("ConstShadowMany: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ConstShadowMany: %w", err)
	}
	return out, nil
}

const constShadowExecQueryText = `MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p`

// ConstShadowExec executes the ConstShadowExec query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p
func (q *queries) ConstShadowExec(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", constShadowExecQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"constShadowExecQueryText": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("ConstShadowExec: %w", err)
	}
	return nil
}

const receiverShadowQueryText = `MATCH (p:Person) WHERE p.name = $q RETURN p.name`

// ReceiverShadow executes the ReceiverShadow query.
//
//	MATCH (p:Person) WHERE p.name = $q RETURN p.name
func (q *queries) ReceiverShadow(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", receiverShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"q": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ReceiverShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ReceiverShadow: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ReceiverShadow: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ReceiverShadow: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ReceiverShadow: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ReceiverShadow: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const contextShadowQueryText = `MATCH (p:Person) WHERE p.name = $ctx RETURN p.name`

// ContextShadow executes the ContextShadow query.
//
//	MATCH (p:Person) WHERE p.name = $ctx RETURN p.name
func (q *queries) ContextShadow(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", contextShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"ctx": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ContextShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ContextShadow: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ContextShadow: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ContextShadow: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ContextShadow: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ContextShadow: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const importShadowQueryText = `MATCH (p:Person) WHERE p.name = $fmt RETURN p.name`

// ImportShadow executes the ImportShadow query.
//
//	MATCH (p:Person) WHERE p.name = $fmt RETURN p.name
func (q *queries) ImportShadow(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", importShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"fmt": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ImportShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ImportShadow: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ImportShadow: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ImportShadow: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ImportShadow: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ImportShadow: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const helperShadowQueryText = `MATCH (p:Person) WHERE p.name = $decodePerson RETURN p`

// HelperShadow executes the HelperShadow query.
//
//	MATCH (p:Person) WHERE p.name = $decodePerson RETURN p
func (q *queries) HelperShadow(ctx context.Context, arg string) (Person, error) {
	stmt, err := q.cypherStmt("$gqlc$", helperShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Person{}, err
	}
	args, err := agtypeArgs(map[string]any{"decodePerson": arg})
	if err != nil {
		return Person{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return Person{}, fmt.Errorf("HelperShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Person{}, fmt.Errorf("HelperShadow: %w", err)
		}
		return Person{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Person{}, fmt.Errorf("HelperShadow: scan row: %w", err)
	}
	if rows.Next() {
		return Person{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Person{}, fmt.Errorf("HelperShadow: %w", err)
	}
	if raw0 == nil {
		return Person{}, fmt.Errorf("HelperShadow: column %q is non-nullable but arrived null", "p")
	}
	value0, err := decodePerson(raw0)
	if err != nil {
		return Person{}, fmt.Errorf("HelperShadow: decode column %q: %w", "p", err)
	}
	return value0, nil
}

const errShadowQueryText = `MATCH (p:Person) WHERE p.name = $err RETURN p.name`

// ErrShadow executes the ErrShadow query.
//
//	MATCH (p:Person) WHERE p.name = $err RETURN p.name
func (q *queries) ErrShadow(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", errShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"err": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ErrShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ErrShadow: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ErrShadow: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ErrShadow: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ErrShadow: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ErrShadow: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const recordsShadowQueryText = `MATCH (p:Person) WHERE p.name = $records RETURN p.name`

// RecordsShadow executes the RecordsShadow query.
//
//	MATCH (p:Person) WHERE p.name = $records RETURN p.name
func (q *queries) RecordsShadow(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", recordsShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"records": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("RecordsShadow: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("RecordsShadow: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("RecordsShadow: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("RecordsShadow: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("RecordsShadow: %w", err)
	}
	return out, nil
}

const outShadowQueryText = `MATCH (p:Person) WHERE p.name = $out RETURN p.name`

// OutShadow executes the OutShadow query.
//
//	MATCH (p:Person) WHERE p.name = $out RETURN p.name
func (q *queries) OutShadow(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", outShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"out": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("OutShadow: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("OutShadow: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("OutShadow: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("OutShadow: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("OutShadow: %w", err)
	}
	return out, nil
}

const blankShadowQueryText = `MATCH (p:Person) WHERE p.name = $_ RETURN p.name`

// BlankShadow executes the BlankShadow query.
//
//	MATCH (p:Person) WHERE p.name = $_ RETURN p.name
func (q *queries) BlankShadow(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", blankShadowQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"_": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("BlankShadow: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("BlankShadow: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("BlankShadow: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("BlankShadow: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("BlankShadow: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("BlankShadow: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}
