// Code generated by gqlc dev. DO NOT EDIT.

package queryparamshadowsemittedname

import (
	"context"
	"fmt"
)

const personByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt RETURN p.name`

// PersonByStmt executes the PersonByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt RETURN p.name
func (q *Queries) PersonByStmt(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"stmt": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByStmt: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByStmt: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByStmt: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args RETURN p.name`

// PersonByArgs executes the PersonByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args RETURN p.name
func (q *Queries) PersonByArgs(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"args": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByArgs: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByArgs: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByArgs: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	return out, nil
}

const personByRowsQueryText = `MATCH (p:Person) WHERE p.name = $rows RETURN p.name`

// PersonByRows executes the PersonByRows query.
//
//	MATCH (p:Person) WHERE p.name = $rows RETURN p.name
func (q *Queries) PersonByRows(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRowsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"rows": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByRows: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByRows: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByRows: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	return out, nil
}

const personByRaw0QueryText = `MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name`

// PersonByRaw0 executes the PersonByRaw0 query.
//
//	MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name
func (q *Queries) PersonByRaw0(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRaw0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"raw0": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByRaw0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByRaw0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByRaw0: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByValue0QueryText = `MATCH (p:Person) WHERE p.name = $value0 RETURN p.name`

// PersonByValue0 executes the PersonByValue0 query.
//
//	MATCH (p:Person) WHERE p.name = $value0 RETURN p.name
func (q *Queries) PersonByValue0(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByValue0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"value0": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByValue0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByValue0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByValue0: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const deleteByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt DELETE p`

// DeleteByStmt executes the DeleteByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt DELETE p
func (q *Queries) DeleteByStmt(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", deleteByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"stmt": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("DeleteByStmt: %w", err)
	}
	return nil
}

const deleteByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args DELETE p`

// DeleteByArgs executes the DeleteByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args DELETE p
func (q *Queries) DeleteByArgs(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", deleteByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"args": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("DeleteByArgs: %w", err)
	}
	return nil
}

const constShadowOneQueryText = `MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name`

// ConstShadowOne executes the ConstShadowOne query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name
func (q *Queries) ConstShadowOne(ctx context.Context, arg string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", constShadowOneQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"constShadowOneQueryText": arg})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("ConstShadowOne: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("ConstShadowOne: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("ConstShadowOne: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("ConstShadowOne: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const constShadowManyQueryText = `MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name`

// ConstShadowMany executes the ConstShadowMany query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name
func (q *Queries) ConstShadowMany(ctx context.Context, arg string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", constShadowManyQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"constShadowManyQueryText": arg})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("ConstShadowMany: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("ConstShadowMany: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("ConstShadowMany: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("ConstShadowMany: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ConstShadowMany: %w", err)
	}
	return out, nil
}

const constShadowExecQueryText = `MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p`

// ConstShadowExec executes the ConstShadowExec query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p
func (q *Queries) ConstShadowExec(ctx context.Context, arg string) error {
	stmt, err := q.cypherStmt("$gqlc$", constShadowExecQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"constShadowExecQueryText": arg})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("ConstShadowExec: %w", err)
	}
	return nil
}
