// Code generated by gqlc dev. DO NOT EDIT.

package temporallistparam

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const slotsMatchingQueryText = `MATCH (s:Slot)
WHERE s.tags = $tags AND s.ranks = $ranks AND s.windows = $windows AND s.days = $days AND s.spans = $spans
RETURN s.id AS id`

type SlotsMatchingParams struct {
	Tags    []string
	Ranks   []int32
	Windows [][]Date
	Days    []Date
	Spans   *[]Duration
}

// SlotsMatching executes the SlotsMatching query.
//
//	MATCH (s:Slot)
//	WHERE s.tags = $tags AND s.ranks = $ranks AND s.windows = $windows AND s.days = $days AND s.spans = $spans
//	RETURN s.id AS id
func (q *Queries) SlotsMatching(ctx context.Context, arg SlotsMatchingParams) ([]int64, error) {
	records, err := q.db.run(ctx, slotsMatchingQueryText, map[string]any{"tags": arg.Tags, "ranks": arg.Ranks, "windows": fromDateList2(arg.Windows), "days": fromDateList(arg.Days), "spans": fromDurationListPtr(arg.Spans)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("SlotsMatching: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("SlotsMatching: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}
