// Code generated by gqlc dev. DO NOT EDIT.

package entityedgeambiguouslabelnamed

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Company corresponds to the Company node type.
type Company struct {
	Id int64
}

// decodeCompany decodes a driver dbtype.Node into a Company struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeCompany(node dbtype.Node) (Company, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Company" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Company{}, fmt.Errorf("decode Company: expected a node labelled %q, got labels %q", "Company", node.Labels)
	}
	var out Company
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Company{}, fmt.Errorf("decode Company.Id: %w", err)
	}
	out.Id = value0
	return out, nil
}

// Person corresponds to the Person node type.
type Person struct {
	Id int64
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodePerson(node dbtype.Node) (Person, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Person" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Person{}, fmt.Errorf("decode Person: expected a node labelled %q, got labels %q", "Person", node.Labels)
	}
	var out Person
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = value0
	return out, nil
}

// CompanyKnows corresponds to the KNOWS edge type (Company -> Company).
type CompanyKnows struct {
	Since int64
}

// decodeCompanyKnows decodes a driver dbtype.Relationship into a CompanyKnows struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeCompanyKnows(rel dbtype.Relationship) (CompanyKnows, error) {
	if rel.Type != "KNOWS" {
		return CompanyKnows{}, fmt.Errorf("decode CompanyKnows: expected a relationship of type %q, got %q", "KNOWS", rel.Type)
	}
	var out CompanyKnows
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return CompanyKnows{}, fmt.Errorf("decode CompanyKnows.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}

// PersonKnows corresponds to the KNOWS edge type (Person -> Person).
type PersonKnows struct {
	Since int64
}

// decodePersonKnows decodes a driver dbtype.Relationship into a PersonKnows struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodePersonKnows(rel dbtype.Relationship) (PersonKnows, error) {
	if rel.Type != "KNOWS" {
		return PersonKnows{}, fmt.Errorf("decode PersonKnows: expected a relationship of type %q, got %q", "KNOWS", rel.Type)
	}
	var out PersonKnows
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return PersonKnows{}, fmt.Errorf("decode PersonKnows.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}
