// Code generated by gqlc dev. DO NOT EDIT.

package listlistint

import "context"

type ReadQuerier interface {
	NestedList(ctx context.Context) ([][]int64, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
