// Code generated by gqlc dev. DO NOT EDIT.

package entitydecodedonlyaslistelement

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const nearChainsQueryText = `MATCH (:Tag)-[n:NEAR*1..3]->(:Tag) RETURN n`

// NearChains executes the NearChains query.
//
//	MATCH (:Tag)-[n:NEAR*1..3]->(:Tag) RETURN n
func (q *queries) NearChains(ctx context.Context) ([][]Near, error) {
	records, err := q.db.run(ctx, nearChainsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([][]Near, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[[]any](record, "n")
		if err != nil {
			return nil, fmt.Errorf("NearChains: decode column %q: %w", "n", err)
		}
		if isNil {
			return nil, fmt.Errorf("NearChains: column %q is non-nullable but arrived null", "n")
		}
		acc := make([]Near, 0, len(value))
		for i, elem := range value {
			rel, ok := elem.(dbtype.Relationship)
			if !ok {
				return nil, fmt.Errorf("NearChains: decode column %q element %d: expected dbtype.Relationship, got %T", "n", i, elem)
			}
			decoded, err := decodeNear(rel)
			if err != nil {
				return nil, fmt.Errorf("NearChains: decode column %q element %d: %w", "n", i, err)
			}
			acc = append(acc, decoded)
		}
		out = append(out, acc)
	}
	return out, nil
}
