// Code generated by gqlc dev. DO NOT EDIT.

package unionlistnullablemember

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const tallyWholeQueryText = `MATCH (t:Tally) WHERE t.id = $id RETURN t`

// TallyWhole executes the TallyWhole query.
//
//	MATCH (t:Tally) WHERE t.id = $id RETURN t
func (q *queries) TallyWhole(ctx context.Context, arg int64) (Tally, error) {
	records, err := q.db.run(ctx, tallyWholeQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Tally{}, err
	}
	if len(records) == 0 {
		return Tally{}, ErrNoRows
	}
	if len(records) > 1 {
		return Tally{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "t")
	if err != nil {
		return Tally{}, fmt.Errorf("TallyWhole: decode column %q: %w", "t", err)
	}
	if isNil {
		return Tally{}, fmt.Errorf("TallyWhole: column %q is non-nullable but arrived null", "t")
	}
	value, err := decodeTally(node)
	if err != nil {
		return Tally{}, fmt.Errorf("TallyWhole: decode column %q: %w", "t", err)
	}
	return value, nil
}

const tallyColumnsQueryText = `MATCH (t:Tally) RETURN t.counts AS counts, t.refs AS refs`

type TallyColumnsRow struct {
	Counts *any
	Refs   *any
}

// TallyColumns executes the TallyColumns query.
//
//	MATCH (t:Tally) RETURN t.counts AS counts, t.refs AS refs
func (q *queries) TallyColumns(ctx context.Context) ([]TallyColumnsRow, error) {
	records, err := q.db.run(ctx, tallyColumnsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]TallyColumnsRow, 0, len(records))
	for _, record := range records {
		var row TallyColumnsRow
		value0, ok := record.Get("counts")
		if !ok {
			return nil, fmt.Errorf("TallyColumns: decode column %q: key not found", "counts")
		}
		var value0Ptr *any
		if value0 != nil {
			v, err := decodeUnion0b44ccb3(value0)
			if err != nil {
				return nil, fmt.Errorf("TallyColumns: decode column %q: %w", "counts", err)
			}
			value0Ptr = &v
		}
		row.Counts = value0Ptr
		value1, ok := record.Get("refs")
		if !ok {
			return nil, fmt.Errorf("TallyColumns: decode column %q: key not found", "refs")
		}
		var value1Ptr *any
		if value1 != nil {
			v, err := decodeUnion47606938(value1)
			if err != nil {
				return nil, fmt.Errorf("TallyColumns: decode column %q: %w", "refs", err)
			}
			value1Ptr = &v
		}
		row.Refs = value1Ptr
		out = append(out, row)
	}
	return out, nil
}
