// Code generated by gqlc dev. DO NOT EDIT.

package unionlistnullablemember

import (
	"fmt"
)

// decodeUnion47606938 dispatches a driver value onto the member of UNION<INT64|LIST<UUID>> whose wire
// shape it arrived as, and narrows it to that member's declared width.
func decodeUnion47606938(v any) (any, error) {
	switch t := v.(type) {
	case int64:
		return t, nil
	case []any:
		v1 := make([]*UUID, len(t))
		for v2, v3 := range t {
			if v3 == nil {
				continue
			}
			v4, ok := v3.(string)
			if !ok {
				return nil, fmt.Errorf("decode %s element: expected string, got %T", "UNION<INT64|LIST<UUID>>", v3)
			}
			v5, err := toUUID(v4)
			if err != nil {
				return nil, fmt.Errorf("decode %s element: %w", "UNION<INT64|LIST<UUID>>", err)
			}
			v1[v2] = &v5
		}
		return v1, nil
	}
	return nil, fmt.Errorf("decode %s: no member carries %T", "UNION<INT64|LIST<UUID>>", v)
}

// decodeUnion0b44ccb3 dispatches a driver value onto the member of UNION<LIST<INT32>|STRING> whose wire
// shape it arrived as, and narrows it to that member's declared width.
func decodeUnion0b44ccb3(v any) (any, error) {
	switch t := v.(type) {
	case []any:
		v1 := make([]*int32, len(t))
		for v2, v3 := range t {
			if v3 == nil {
				continue
			}
			v4, ok := v3.(int64)
			if !ok {
				return nil, fmt.Errorf("decode %s element: expected int64, got %T", "UNION<LIST<INT32>|STRING>", v3)
			}
			v5, err := narrowInt[int32](v4)
			if err != nil {
				return nil, fmt.Errorf("decode %s element: %w", "UNION<LIST<INT32>|STRING>", err)
			}
			v1[v2] = &v5
		}
		return v1, nil
	case string:
		return t, nil
	}
	return nil, fmt.Errorf("decode %s: no member carries %T", "UNION<LIST<INT32>|STRING>", v)
}
