// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionmanytwocandidates

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const listActionsQueryText = `MATCH (:Person)-[r:AUTHORED|LIKES]->(:Post) RETURN r`

// ListActions executes the ListActions query.
//
//	MATCH (:Person)-[r:AUTHORED|LIKES]->(:Post) RETURN r
func (q *Queries) ListActions(ctx context.Context) ([]ListActionsR, error) {
	records, err := q.db.run(ctx, listActionsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]ListActionsR, 0, len(records))
	for _, record := range records {
		raw, ok := record.Get("r")
		if !ok {
			return nil, fmt.Errorf("ListActions: column %q missing from record", "r")
		}
		if raw == nil {
			return nil, fmt.Errorf("ListActions: column %q is non-nullable but arrived null", "r")
		}
		rel, ok := raw.(dbtype.Relationship)
		if !ok {
			return nil, fmt.Errorf("ListActions: column %q: expected dbtype.Relationship, got %T", "r", raw)
		}
		switch rel.Type {
		case "AUTHORED":
			entity, err := decodeAUTHORED(rel)
			if err != nil {
				return nil, fmt.Errorf("ListActions: decode column %q: %w", "r", err)
			}
			out = append(out, entity)
		case "LIKES":
			entity, err := decodeLIKES(rel)
			if err != nil {
				return nil, fmt.Errorf("ListActions: decode column %q: %w", "r", err)
			}
			out = append(out, entity)
		default:
			return nil, fmt.Errorf("ListActions: column %q: unexpected relationship type %q", "r", rel.Type)
		}
	}
	return out, nil
}
