// Code generated by gqlc dev. DO NOT EDIT.

package entityzeropropertynode

import "context"

type ReadQuerier interface {
	Markers(ctx context.Context) ([]Marker, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
