// Code generated by gqlc dev. DO NOT EDIT.

package queryparamshadowsemittedname

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const personByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt RETURN p.name`

// PersonByStmt executes the PersonByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt RETURN p.name
func (q *Queries) PersonByStmt(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByStmtQueryText, map[string]any{"stmt": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByStmt: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const personByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args RETURN p.name`

// PersonByArgs executes the PersonByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args RETURN p.name
func (q *Queries) PersonByArgs(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, personByArgsQueryText, map[string]any{"args": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("PersonByArgs: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("PersonByArgs: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const personByRowsQueryText = `MATCH (p:Person) WHERE p.name = $rows RETURN p.name`

// PersonByRows executes the PersonByRows query.
//
//	MATCH (p:Person) WHERE p.name = $rows RETURN p.name
func (q *Queries) PersonByRows(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, personByRowsQueryText, map[string]any{"rows": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("PersonByRows: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("PersonByRows: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const personByRaw0QueryText = `MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name`

// PersonByRaw0 executes the PersonByRaw0 query.
//
//	MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name
func (q *Queries) PersonByRaw0(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByRaw0QueryText, map[string]any{"raw0": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByRaw0: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const personByValue0QueryText = `MATCH (p:Person) WHERE p.name = $value0 RETURN p.name`

// PersonByValue0 executes the PersonByValue0 query.
//
//	MATCH (p:Person) WHERE p.name = $value0 RETURN p.name
func (q *Queries) PersonByValue0(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByValue0QueryText, map[string]any{"value0": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByValue0: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const deleteByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt DELETE p`

// DeleteByStmt executes the DeleteByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt DELETE p
func (q *Queries) DeleteByStmt(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, deleteByStmtQueryText, map[string]any{"stmt": arg}, neo4j.AccessModeWrite)
	return err
}

const deleteByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args DELETE p`

// DeleteByArgs executes the DeleteByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args DELETE p
func (q *Queries) DeleteByArgs(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, deleteByArgsQueryText, map[string]any{"args": arg}, neo4j.AccessModeWrite)
	return err
}

const constShadowOneQueryText = `MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name`

// ConstShadowOne executes the ConstShadowOne query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name
func (q *Queries) ConstShadowOne(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, constShadowOneQueryText, map[string]any{"constShadowOneQueryText": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ConstShadowOne: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const constShadowManyQueryText = `MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name`

// ConstShadowMany executes the ConstShadowMany query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name
func (q *Queries) ConstShadowMany(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, constShadowManyQueryText, map[string]any{"constShadowManyQueryText": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("ConstShadowMany: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("ConstShadowMany: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const constShadowExecQueryText = `MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p`

// ConstShadowExec executes the ConstShadowExec query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p
func (q *Queries) ConstShadowExec(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, constShadowExecQueryText, map[string]any{"constShadowExecQueryText": arg}, neo4j.AccessModeWrite)
	return err
}

const receiverShadowQueryText = `MATCH (p:Person) WHERE p.name = $q RETURN p.name`

// ReceiverShadow executes the ReceiverShadow query.
//
//	MATCH (p:Person) WHERE p.name = $q RETURN p.name
func (q *Queries) ReceiverShadow(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, receiverShadowQueryText, map[string]any{"q": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ReceiverShadow: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ReceiverShadow: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const contextShadowQueryText = `MATCH (p:Person) WHERE p.name = $ctx RETURN p.name`

// ContextShadow executes the ContextShadow query.
//
//	MATCH (p:Person) WHERE p.name = $ctx RETURN p.name
func (q *Queries) ContextShadow(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, contextShadowQueryText, map[string]any{"ctx": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ContextShadow: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ContextShadow: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const importShadowQueryText = `MATCH (p:Person) WHERE p.name = $fmt RETURN p.name`

// ImportShadow executes the ImportShadow query.
//
//	MATCH (p:Person) WHERE p.name = $fmt RETURN p.name
func (q *Queries) ImportShadow(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, importShadowQueryText, map[string]any{"fmt": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ImportShadow: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ImportShadow: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const helperShadowQueryText = `MATCH (p:Person) WHERE p.name = $decodePerson RETURN p`

// HelperShadow executes the HelperShadow query.
//
//	MATCH (p:Person) WHERE p.name = $decodePerson RETURN p
func (q *Queries) HelperShadow(ctx context.Context, arg string) (Person, error) {
	records, err := q.db.run(ctx, helperShadowQueryText, map[string]any{"decodePerson": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Person{}, err
	}
	if len(records) == 0 {
		return Person{}, ErrNoRows
	}
	if len(records) > 1 {
		return Person{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "p")
	if err != nil {
		return Person{}, fmt.Errorf("HelperShadow: decode column %q: %w", "p", err)
	}
	if isNil {
		return Person{}, fmt.Errorf("HelperShadow: column %q is non-nullable but arrived null", "p")
	}
	value, err := decodePerson(node)
	if err != nil {
		return Person{}, fmt.Errorf("HelperShadow: decode column %q: %w", "p", err)
	}
	return value, nil
}

const errShadowQueryText = `MATCH (p:Person) WHERE p.name = $err RETURN p.name`

// ErrShadow executes the ErrShadow query.
//
//	MATCH (p:Person) WHERE p.name = $err RETURN p.name
func (q *Queries) ErrShadow(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, errShadowQueryText, map[string]any{"err": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ErrShadow: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ErrShadow: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const recordsShadowQueryText = `MATCH (p:Person) WHERE p.name = $records RETURN p.name`

// RecordsShadow executes the RecordsShadow query.
//
//	MATCH (p:Person) WHERE p.name = $records RETURN p.name
func (q *Queries) RecordsShadow(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, recordsShadowQueryText, map[string]any{"records": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("RecordsShadow: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("RecordsShadow: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const outShadowQueryText = `MATCH (p:Person) WHERE p.name = $out RETURN p.name`

// OutShadow executes the OutShadow query.
//
//	MATCH (p:Person) WHERE p.name = $out RETURN p.name
func (q *Queries) OutShadow(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, outShadowQueryText, map[string]any{"out": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("OutShadow: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("OutShadow: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const blankShadowQueryText = `MATCH (p:Person) WHERE p.name = $_ RETURN p.name`

// BlankShadow executes the BlankShadow query.
//
//	MATCH (p:Person) WHERE p.name = $_ RETURN p.name
func (q *Queries) BlankShadow(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, blankShadowQueryText, map[string]any{"_": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("BlankShadow: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("BlankShadow: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}
