// Code generated by gqlc dev. DO NOT EDIT.

package unionlistexpressionelement

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const accountEithersQueryText = `MATCH (a:Account) RETURN [a.either] AS xs ORDER BY a.id`

// AccountEithers executes the AccountEithers query.
//
//	MATCH (a:Account) RETURN [a.either] AS xs ORDER BY a.id
func (q *queries) AccountEithers(ctx context.Context) ([][]any, error) {
	records, err := q.db.run(ctx, accountEithersQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([][]any, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[[]any](record, "xs")
		if err != nil {
			return nil, fmt.Errorf("AccountEithers: decode column %q: %w", "xs", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountEithers: column %q is non-nullable but arrived null", "xs")
		}
		acc := make([]any, 0, len(value))
		for i, elem := range value {
			if elem == nil {
				acc = append(acc, nil)
				continue
			}
			v, err := decodeUnion0aa394d5(elem)
			if err != nil {
				return nil, fmt.Errorf("AccountEithers: decode column %q element %d: %w", "xs", i, err)
			}
			acc = append(acc, v)
		}
		out = append(out, acc)
	}
	return out, nil
}
