// Code generated by gqlc dev. DO NOT EDIT.

package schemalistproperty

import "context"

type ReadQuerier interface {
	GetEventTags(ctx context.Context) (*[]string, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
