FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

WORKDIR /antlr
RUN wget https://www.antlr.org/download/antlr-4.13.1-complete.jar -O antlr.jar

ENTRYPOINT ["java", "-jar", "/antlr/antlr.jar", "-Dlanguage=Go"]

WORKDIR /work/internal/grammar/gql
CMD ["-package", "gen", "-visitor", "-o", "gen", "GQL.g4"]
