# single source of truth for the linter toolchain version. Every lint/fmt
# recipe self-heals: it verifies the pinned version in .bin/ and reinstalls on
# mismatch, so a version bump here is a one-line change and nobody ever
# installs or upgrades the linter by hand.
golangci_version := "v2.12.2"
golangci := justfile_directory() + "/.bin/golangci-lint"
actionlint_version := "v1.7.7"

# Configures local git settings required after a fresh clone.
# Idempotent: safe to run multiple times.
init:
    git config core.hooksPath .githooks
    @echo "git hooks activated (core.hooksPath = .githooks)"

# provisions the pinned golangci-lint into the gitignored .bin/ when missing
# or version-mismatched (~3s; official release binary — golangci-lint does not
# support builds from source). The happy path is a ~30ms version check, cheap
# enough to run before every lint/fmt invocation, in hooks included.
[private]
ensure-golangci:
    #!/usr/bin/env bash
    set -euo pipefail
    want="{{golangci_version}}"
    if [ "$({{quote(golangci)}} version --short 2>/dev/null || true)" = "${want#v}" ]; then
        exit 0
    fi
    echo "provisioning golangci-lint $want into .bin/" >&2
    curl --proto '=https' --tlsv1.2 -sSfL \
        "https://raw.githubusercontent.com/golangci/golangci-lint/$want/install.sh" \
        | sh -s -- -b {{quote(justfile_directory() + "/.bin")}} "$want"

# full static analysis (.golangci.yml): linters + formatter diffs as issues
lint: ensure-golangci
    {{golangci}} run

# lints only lines changed since the given rev — the fast pre-push variant
lint-new rev="origin/master": ensure-golangci
    {{golangci}} run --new-from-rev {{rev}}

# rewrites formatting in place (gofumpt + gci, both bundled in golangci-lint)
fmt: ensure-golangci
    {{golangci}} fmt

# formatting check without writing; fails with a diff when unformatted
fmt-check: ensure-golangci
    {{golangci}} fmt --diff

# runs the whole suite (unit, golden snapshots, godog) in one shot. Independent
# of fetch-tck: the TCK is vendored, so there is no network at test time.
# -shuffle catches inter-test coupling; go build link-checks package main,
# which has no tests and is otherwise only compile-checked by lint.
test:
    go build ./...
    go test -shuffle=on ./...

# fails when go.mod/go.sum are not tidy
tidy-check:
    go mod tidy -diff

# call-graph-aware vulnerability scan; run on dependency changes and on the
# weekly CI schedule ("@latest" deliberate: the vuln DB matters more than
# tool-version reproducibility)
vuln:
    go run golang.org/x/vuln/cmd/govulncheck@latest ./...

# lints the GitHub Actions workflow files
actionlint:
    go run github.com/rhysd/actionlint/cmd/actionlint@{{actionlint_version}}

# pinned openCypher release tag the TCK is vendored from; never "master" so the
# corpus is reproducible. Bump deliberately, then re-run fetch-tck and commit.
tck_tag := "2024.3"
tck_dir := "test/data/query/cypher/tck"

# vendors the whole openCypher tck/ subtree (features + LICENSE) at tck_tag into
# tck_dir via a shallow, sparse git checkout — no new deps, no extraction step
# (godog reads the .feature files directly). Run for initial population and
# deliberate version bumps; the result is committed.
fetch-tck:
    rm -rf {{tck_dir}}
    mkdir -p {{tck_dir}}
    rm -rf .tck-fetch
    git clone --depth 1 --branch {{tck_tag}} --filter=blob:none --sparse \
        https://github.com/opencypher/openCypher.git .tck-fetch
    cd .tck-fetch && git sparse-checkout set tck
    cp -R .tck-fetch/tck/. {{tck_dir}}/
    cp .tck-fetch/LICENSE {{tck_dir}}/LICENSE
    rm -rf .tck-fetch
    @echo "vendored TCK {{tck_tag}} into {{tck_dir}}"

# builds the autogenerated code from the available, relevant ANTLR grammars
build-grammar:
    sudo docker build -q -t antlr-tool -f Dockerfile.grammar .
    @echo "Generating Go files from GQL.g4..."
    sudo docker run --rm -v {{invocation_directory()}}:/work -w /work/internal/grammar/gql antlr-tool -package gen -visitor -o gen GQL.g4
    @echo "Generating Go files from Cypher.g4..."
    sudo docker run --rm -v {{invocation_directory()}}:/work -w /work/internal/grammar/cypher antlr-tool -package gen -visitor -o gen Cypher.g4
