// Code generated by gqlc dev. DO NOT EDIT.

package writeexectwoparams

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const removeRelationQueryText = `MATCH (a:Person)-[r:KNOWS]->(b:Person) WHERE a.id = $srcId AND b.id = $tgtId DELETE r`

type RemoveRelationParams struct {
	SrcId int64
	TgtId int64
}

// RemoveRelation executes the RemoveRelation query.
//
//	MATCH (a:Person)-[r:KNOWS]->(b:Person) WHERE a.id = $srcId AND b.id = $tgtId DELETE r
func (q *Queries) RemoveRelation(ctx context.Context, arg RemoveRelationParams) error {
	_, err := q.db.run(ctx, removeRelationQueryText, map[string]any{"srcId": arg.SrcId, "tgtId": arg.TgtId}, neo4j.AccessModeWrite)
	return err
}
