// Code generated by gqlc dev. DO NOT EDIT.

package writeexectwoparams

import "context"

type ReadQuerier interface {
}

type WriteQuerier interface {
	RemoveRelation(ctx context.Context, arg RemoveRelationParams) error
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
