// Code generated by gqlc dev. DO NOT EDIT.

package nullabletemporallistelement

import (
	"context"
	"fmt"
)

const slotsMatchingQueryText = `MATCH (s:Slot)
WHERE s.days = $days AND s.spans = $spans AND s.maybe = $maybe
RETURN s.id AS id`

type SlotsMatchingParams struct {
	Days  []*Date
	Spans []Duration
	Maybe *[]*Date
}

// SlotsMatching executes the SlotsMatching query.
//
//	MATCH (s:Slot)
//	WHERE s.days = $days AND s.spans = $spans AND s.maybe = $maybe
//	RETURN s.id AS id
func (q *queries) SlotsMatching(ctx context.Context, arg SlotsMatchingParams) ([]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", slotsMatchingQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	param0, err := agtypeEncodedList(arg.Days, func(in *Date) (*string, error) {
		return agtypeEncodedNullable(in, agtypeDateText)
	})
	if err != nil {
		return nil, fmt.Errorf("SlotsMatching: parameter $days: %w", err)
	}
	param1, err := agtypeEncodedList(arg.Spans, agtypeDurationMicros)
	if err != nil {
		return nil, fmt.Errorf("SlotsMatching: parameter $spans: %w", err)
	}
	param2, err := agtypeEncodedNullable(arg.Maybe, func(in []*Date) ([]*string, error) {
		return agtypeEncodedList(in, func(in *Date) (*string, error) {
			return agtypeEncodedNullable(in, agtypeDateText)
		})
	})
	if err != nil {
		return nil, fmt.Errorf("SlotsMatching: parameter $maybe: %w", err)
	}
	args, err := agtypeArgs(map[string]any{"days": param0, "spans": param1, "maybe": param2})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("SlotsMatching: %w", err)
	}
	defer rows.Close()
	out := make([]int64, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("SlotsMatching: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("SlotsMatching: column %q is non-nullable but arrived null", "id")
		}
		value0, err := agtypeInt64(raw0)
		if err != nil {
			return nil, fmt.Errorf("SlotsMatching: decode column %q: %w", "id", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("SlotsMatching: %w", err)
	}
	return out, nil
}
