// Code generated by gqlc dev. DO NOT EDIT.

package nullabletemporallistelement

import (
	"time"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// toDate reads the calendar components off a driver date. The
// hydrator builds it as UTC midnight of the packed epoch-day, so the
// clock the newtype also carries holds nothing to lose.
func toDate(v dbtype.Date) Date {
	year, month, day := time.Time(v).Date()
	return Date{Year: year, Month: int(month), Day: day}
}

// fromDate builds the driver date the packer turns into epoch-days.
// UTC midnight, so the packer's day division is exact for every date,
// including those before the epoch.
func fromDate(v Date) dbtype.Date {
	return dbtype.Date(time.Date(v.Year, time.Month(v.Month), v.Day, 0, 0, 0, 0, time.UTC))
}

// fromNullableDateList widens a list of nullable Date parameters element by
// element. A nil element binds the Cypher null the schema's element
// nullability declared: packV packs a nil interface as null, so the
// conversion the other elements owe is simply the one it does not.
func fromNullableDateList(v []*Date) []any {
	out := make([]any, len(v))
	for i := range v {
		if v[i] == nil {
			out[i] = nil
			continue
		}
		out[i] = fromDate(*v[i])
	}
	return out
}

// fromNullableDateListPtr binds a nullable list of *Date: a nil pointer is the
// Cypher null the schema's nullability declared, not an empty list.
func fromNullableDateListPtr(v *[]*Date) any {
	if v == nil {
		return nil
	}
	return fromNullableDateList(*v)
}

// toDuration copies a driver duration field for field: dbtype.Duration
// already holds the four components apart.
func toDuration(v dbtype.Duration) Duration {
	return Duration{Months: v.Months, Days: v.Days, Seconds: v.Seconds, Nanos: v.Nanos}
}

// fromDuration copies a duration field for field.
func fromDuration(v Duration) dbtype.Duration {
	return dbtype.Duration{Months: v.Months, Days: v.Days, Seconds: v.Seconds, Nanos: v.Nanos}
}

// fromDurationList widens a list of Duration parameters element by element. The
// driver marshals no gqlc struct, so each element converts before the
// list reaches the wire.
func fromDurationList(v []Duration) []any {
	out := make([]any, len(v))
	for i := range v {
		out[i] = fromDuration(v[i])
	}
	return out
}
