// Code generated by gqlc dev. DO NOT EDIT.

package entitypropertyshadowsdecoderlocal

import (
	"context"
	"fmt"
)

const oneMarkerQueryText = `MATCH (m:Marker) RETURN m`

// OneMarker executes the OneMarker query.
//
//	MATCH (m:Marker) RETURN m
func (q *queries) OneMarker(ctx context.Context) (Marker, error) {
	stmt, err := q.cypherStmt("$gqlc$", oneMarkerQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Marker{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return Marker{}, fmt.Errorf("OneMarker: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Marker{}, fmt.Errorf("OneMarker: %w", err)
		}
		return Marker{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Marker{}, fmt.Errorf("OneMarker: scan row: %w", err)
	}
	if rows.Next() {
		return Marker{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Marker{}, fmt.Errorf("OneMarker: %w", err)
	}
	if raw0 == nil {
		return Marker{}, fmt.Errorf("OneMarker: column %q is non-nullable but arrived null", "m")
	}
	value0, err := decodeMarker(raw0)
	if err != nil {
		return Marker{}, fmt.Errorf("OneMarker: decode column %q: %w", "m", err)
	}
	return value0, nil
}
