// Code generated by gqlc dev. DO NOT EDIT.

package relationshiprebindnarrowstoonetype

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Id int64
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing per-property nullability against the schema.
func decodePerson(node dbtype.Node) (Person, error) {
	var out Person
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = value0
	return out, nil
}

// Post corresponds to the Post node type.
type Post struct {
	Id int64
}

// decodePost decodes a driver dbtype.Node into a Post struct,
// enforcing per-property nullability against the schema.
func decodePost(node dbtype.Node) (Post, error) {
	var out Post
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Post{}, fmt.Errorf("decode Post.Id: %w", err)
	}
	out.Id = value0
	return out, nil
}

// AUTHORED corresponds to the AUTHORED edge type (Person -> Post).
type AUTHORED struct {
	Since int64
}

// decodeAUTHORED decodes a driver dbtype.Relationship into a AUTHORED struct,
// enforcing per-property nullability against the schema.
func decodeAUTHORED(rel dbtype.Relationship) (AUTHORED, error) {
	var out AUTHORED
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return AUTHORED{}, fmt.Errorf("decode AUTHORED.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}

// LIKES corresponds to the LIKES edge type (Person -> Post).
type LIKES struct {
}

// decodeLIKES decodes a driver dbtype.Relationship into a LIKES struct,
// enforcing per-property nullability against the schema.
func decodeLIKES(rel dbtype.Relationship) (LIKES, error) {
	var out LIKES
	return out, nil
}

// SHARED corresponds to the SHARED edge type (Person -> Post).
type SHARED struct {
}

// decodeSHARED decodes a driver dbtype.Relationship into a SHARED struct,
// enforcing per-property nullability against the schema.
func decodeSHARED(rel dbtype.Relationship) (SHARED, error) {
	var out SHARED
	return out, nil
}
