// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumntime

import "context"

type ReadQuerier interface {
	NowZoned(ctx context.Context) (Time, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
