// Code generated by gqlc dev. DO NOT EDIT.

package timestampprojection

import (
	"context"
	"fmt"
	"time"
)

const readingAtQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r.takenAt AS takenAt`

// ReadingAt executes the ReadingAt query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r.takenAt AS takenAt
func (q *Queries) ReadingAt(ctx context.Context, id int64) (time.Time, error) {
	stmt, err := q.cypherStmt("$gqlc$", readingAtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return time.Time{}, err
	}
	args, err := agtypeArgs(map[string]any{"id": id})
	if err != nil {
		return time.Time{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return time.Time{}, fmt.Errorf("ReadingAt: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return time.Time{}, fmt.Errorf("ReadingAt: %w", err)
		}
		return time.Time{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return time.Time{}, fmt.Errorf("ReadingAt: scan row: %w", err)
	}
	if rows.Next() {
		return time.Time{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return time.Time{}, fmt.Errorf("ReadingAt: %w", err)
	}
	if raw0 == nil {
		return time.Time{}, fmt.Errorf("ReadingAt: column %q is non-nullable but arrived null", "takenAt")
	}
	value0, err := agtypeInstant(raw0)
	if err != nil {
		return time.Time{}, fmt.Errorf("ReadingAt: decode column %q: %w", "takenAt", err)
	}
	return value0, nil
}

const oneReadingQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r`

// OneReading executes the OneReading query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r
func (q *Queries) OneReading(ctx context.Context, id int64) (Reading, error) {
	stmt, err := q.cypherStmt("$gqlc$", oneReadingQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Reading{}, err
	}
	args, err := agtypeArgs(map[string]any{"id": id})
	if err != nil {
		return Reading{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Reading{}, fmt.Errorf("OneReading: %w", err)
		}
		return Reading{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Reading{}, fmt.Errorf("OneReading: scan row: %w", err)
	}
	if rows.Next() {
		return Reading{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Reading{}, fmt.Errorf("OneReading: %w", err)
	}
	if raw0 == nil {
		return Reading{}, fmt.Errorf("OneReading: column %q is non-nullable but arrived null", "r")
	}
	value0, err := decodeReading(raw0)
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: decode column %q: %w", "r", err)
	}
	return value0, nil
}

const allReadingsQueryText = `MATCH (r:Reading) RETURN r.takenAt AS takenAt ORDER BY r.takenAt`

// AllReadings executes the AllReadings query.
//
//	MATCH (r:Reading) RETURN r.takenAt AS takenAt ORDER BY r.takenAt
func (q *Queries) AllReadings(ctx context.Context) ([]time.Time, error) {
	stmt, err := q.cypherStmt("$gqlc$", allReadingsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("AllReadings: %w", err)
	}
	defer rows.Close()
	out := make([]time.Time, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("AllReadings: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("AllReadings: column %q is non-nullable but arrived null", "takenAt")
		}
		value0, err := agtypeInstant(raw0)
		if err != nil {
			return nil, fmt.Errorf("AllReadings: decode column %q: %w", "takenAt", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("AllReadings: %w", err)
	}
	return out, nil
}
