// Code generated by gqlc dev. DO NOT EDIT.

package unioncolumnsoledecode

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Thing corresponds to the Thing node type.
type Thing struct {
	Either *any
	Id     int64
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDate decodes a stored DATE. agtype has no temporal value, so
// gqlc stores one as the string scalar in zero-padded ISO YYYY-MM-DD:
// the one temporal spelling whose lexical order is its chronological
// order, so an author's ORDER BY n.dob is answered by the database's own
// string comparison with nothing for gqlc to rewrite.
//
// That ordering holds across [0001-01-01, 9999-12-31] and nowhere else,
// which is why the padding and the bound are read back here rather than
// assumed. A year needing a fifth digit sorts under every four-digit year
// because '1' < '2', and a proleptic year before 1 CE needs a sign, which
// sorts under every digit and files the whole era at the front,
// ascending. gqlc's own encode produces neither — it refuses them — but
// it writes to an ordinary agtype string property on a vertex any writer
// can touch, so what is read back is whatever the graph holds.
//
// The padding is enforced by the layout and not by a check beside it.
// time.Parse reads each field at a fixed width, so '2024-1-2' fails at
// the month, '24-01-02' at the year, and a signed or five-digit year at
// the first byte that is not a digit where one belongs — every spelling
// that would sort in the wrong place is refused before a Date is built.
//
// That leaves the range bounded at one end only, which is measured
// rather than an oversight. A year over 9999 needs a fifth digit and a
// year before 1 CE needs a sign, and the layout refuses both; year 0 is
// the one out-of-range year spelled with four unsigned digits, so it is
// the only one that reaches here, and it is what this bound is for.
func agtypeDate(raw []byte) (Date, error) {
	text, err := agtypeString(raw)
	if err != nil {
		return Date{}, err
	}
	at, err := time.Parse(agtypeDateLayout, text)
	if err != nil {
		return Date{}, fmt.Errorf("gqlc: %q is not a date in zero-padded ISO YYYY-MM-DD form: %w", text, err)
	}
	if at.Year() < 1 {
		return Date{}, fmt.Errorf("gqlc: %q is outside the year 1 to year 9999 range this encoding admits", text)
	}
	return Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}, nil
}

// decodeUnion0aa394d5 dispatches an agtype value onto the member of
// UNION<DATE|INT64> whose wire family it arrived as, and narrows it
// to that member's declared width.
func decodeUnion0aa394d5(raw []byte) (any, error) {
	body := bytes.TrimSpace(raw)
	if len(body) == 0 {
		return nil, fmt.Errorf("decode UNION<DATE|INT64>: %q is not an agtype value", raw)
	}
	switch body[0] {
	case '"':
		out, err := agtypeDate(body)
		if err != nil {
			return nil, fmt.Errorf("decode UNION<DATE|INT64>: %w", err)
		}
		return out, nil
	}
	if out, err := agtypeInt64(body); err == nil {
		return out, nil
	}
	return nil, fmt.Errorf("decode UNION<DATE|INT64>: %q is no member's wire shape", raw)
}
