// Code generated by gqlc dev. DO NOT EDIT.

package unioncolumnsoledecode

import (
	"context"
	"fmt"
)

const eithersQueryText = `MATCH (t:Thing) RETURN t.either AS either`

// Eithers executes the Eithers query.
//
//	MATCH (t:Thing) RETURN t.either AS either
func (q *queries) Eithers(ctx context.Context) ([]*any, error) {
	stmt, err := q.cypherStmt("$gqlc$", eithersQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("Eithers: %w", err)
	}
	defer rows.Close()
	out := make([]*any, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("Eithers: scan row: %w", err)
		}
		var value0 *any
		if raw0 != nil {
			decoded, err := decodeUnion0aa394d5(raw0)
			if err != nil {
				return nil, fmt.Errorf("Eithers: decode column %q: %w", "either", err)
			}
			value0 = &decoded
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("Eithers: %w", err)
	}
	return out, nil
}
