// Code generated by gqlc dev. DO NOT EDIT.

package unionlisttemporalmember

import (
	"time"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// toDate reads the calendar components off a driver date. The
// hydrator builds it as UTC midnight of the packed epoch-day, so the
// clock the newtype also carries holds nothing to lose.
func toDate(v dbtype.Date) Date {
	year, month, day := time.Time(v).Date()
	return Date{Year: year, Month: int(month), Day: day}
}

// fromDate builds the driver date the packer turns into epoch-days.
// UTC midnight, so the packer's day division is exact for every date,
// including those before the epoch.
func fromDate(v Date) dbtype.Date {
	return dbtype.Date(time.Date(v.Year, time.Month(v.Month), v.Day, 0, 0, 0, 0, time.UTC))
}

// fromNullableDateList widens a list of nullable Date parameters element by
// element. A nil element binds the Cypher null the schema's element
// nullability declared: packV packs a nil interface as null, so the
// conversion the other elements owe is simply the one it does not.
func fromNullableDateList(v []*Date) []any {
	out := make([]any, len(v))
	for i := range v {
		if v[i] == nil {
			out[i] = nil
			continue
		}
		out[i] = fromDate(*v[i])
	}
	return out
}

// toLocalTime reads the clock components off a driver local time.
func toLocalTime(v dbtype.LocalTime) LocalTime {
	t := time.Time(v)
	hour, minute, second := t.Clock()
	return LocalTime{Hour: hour, Minute: minute, Second: second, Nanosecond: t.Nanosecond()}
}

// fromLocalTime builds the driver local time the packer turns into
// nanoseconds since midnight. The date is an arbitrary anchor the
// packer never reads.
func fromLocalTime(v LocalTime) dbtype.LocalTime {
	return dbtype.LocalTime(time.Date(0, time.January, 1, v.Hour, v.Minute, v.Second, v.Nanosecond, time.UTC))
}

// fromNullableLocalTimeList widens a list of nullable LocalTime parameters element by
// element. A nil element binds the Cypher null the schema's element
// nullability declared: packV packs a nil interface as null, so the
// conversion the other elements owe is simply the one it does not.
func fromNullableLocalTimeList(v []*LocalTime) []any {
	out := make([]any, len(v))
	for i := range v {
		if v[i] == nil {
			out[i] = nil
			continue
		}
		out[i] = fromLocalTime(*v[i])
	}
	return out
}

// toTime reads the clock components and the zone offset off a driver
// zoned time. The offset is east-positive, matching the wire.
func toTime(v dbtype.Time) Time {
	t := time.Time(v)
	hour, minute, second := t.Clock()
	_, offset := t.Zone()
	return Time{Hour: hour, Minute: minute, Second: second, Nanosecond: t.Nanosecond(), OffsetSeconds: offset}
}

// fromTime builds the driver zoned time the packer turns into
// (nanoseconds since local midnight, offset seconds). The zone is
// named "Offset" because that is the name the driver's own hydrator
// gives a fixed-offset zone.
func fromTime(v Time) dbtype.Time {
	zone := time.FixedZone("Offset", v.OffsetSeconds)
	return dbtype.Time(time.Date(0, time.January, 1, v.Hour, v.Minute, v.Second, v.Nanosecond, zone))
}

// fromNullableTimeList widens a list of nullable Time parameters element by
// element. A nil element binds the Cypher null the schema's element
// nullability declared: packV packs a nil interface as null, so the
// conversion the other elements owe is simply the one it does not.
func fromNullableTimeList(v []*Time) []any {
	out := make([]any, len(v))
	for i := range v {
		if v[i] == nil {
			out[i] = nil
			continue
		}
		out[i] = fromTime(*v[i])
	}
	return out
}

// toDuration copies a driver duration field for field: dbtype.Duration
// already holds the four components apart.
func toDuration(v dbtype.Duration) Duration {
	return Duration{Months: v.Months, Days: v.Days, Seconds: v.Seconds, Nanos: v.Nanos}
}

// fromDuration copies a duration field for field.
func fromDuration(v Duration) dbtype.Duration {
	return dbtype.Duration{Months: v.Months, Days: v.Days, Seconds: v.Seconds, Nanos: v.Nanos}
}

// fromNullableDurationList widens a list of nullable Duration parameters element by
// element. A nil element binds the Cypher null the schema's element
// nullability declared: packV packs a nil interface as null, so the
// conversion the other elements owe is simply the one it does not.
func fromNullableDurationList(v []*Duration) []any {
	out := make([]any, len(v))
	for i := range v {
		if v[i] == nil {
			out[i] = nil
			continue
		}
		out[i] = fromDuration(*v[i])
	}
	return out
}
