// Code generated by gqlc dev. DO NOT EDIT.

package manycolonerow

import "context"

type ReadQuerier interface {
	PersonById(ctx context.Context, id int64) (PersonByIdRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
