// Code generated by gqlc dev. DO NOT EDIT.

package temporallistparam

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Slot corresponds to the Slot node type.
type Slot struct {
	Days  []Date
	Id    int64
	Ranks []int32
	Spans *[]Duration
	Tags  []string
}

// decodeSlot decodes an agtype vertex into a Slot struct, enforcing
// the label and the per-property nullability the schema declares.
func decodeSlot(raw []byte) (Slot, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot: %w", err)
	}
	if label != "Slot" {
		return Slot{}, fmt.Errorf("decode Slot: expected label %q, got %q", "Slot", label)
	}
	var out Slot
	value0, err := agtypeProperty(props, "days", agtypeListOfDate)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Days: %w", err)
	}
	out.Days = value0
	value1, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Id: %w", err)
	}
	out.Id = value1
	value2, err := agtypeProperty(props, "ranks", agtypeListOfInt32)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Ranks: %w", err)
	}
	out.Ranks = value2
	value3, err := agtypeNullableProperty(props, "spans", agtypeListOfDuration)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Spans: %w", err)
	}
	out.Spans = value3
	value4, err := agtypeProperty(props, "tags", agtypeListOfString)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Tags: %w", err)
	}
	out.Tags = value4
	return out, nil
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeIntAs decodes an agtype integer into a width narrower than the
// int64 scalar it rides in, refusing a stored value that width cannot
// hold rather than wrapping it.
//
// Two clauses, and both are load-bearing. The round-trip catches every
// width whose range is a strict subset of int64's. It cannot catch
// uint64, where the conversion is a bijection and int64(uint64(-1)) is
// -1 again; there the sign comparison is the whole of the check. A
// UINT64 property's readable set is therefore [0, MaxInt64], since
// agtype's integer scalar is signed 64-bit and a larger value is
// unstorable rather than unreadable.
func agtypeIntAs[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](raw []byte) (T, error) {
	v, err := agtypeInt64(raw)
	if err != nil {
		return 0, err
	}
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("gqlc: value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDate decodes a stored DATE. agtype has no temporal value, so
// gqlc stores one as the string scalar in zero-padded ISO YYYY-MM-DD:
// the one temporal spelling whose lexical order is its chronological
// order, so an author's ORDER BY n.dob is answered by the database's own
// string comparison with nothing for gqlc to rewrite.
//
// That ordering holds across [0001-01-01, 9999-12-31] and nowhere else,
// which is why the padding and the bound are read back here rather than
// assumed. A year needing a fifth digit sorts under every four-digit year
// because '1' < '2', and a proleptic year before 1 CE needs a sign, which
// sorts under every digit and files the whole era at the front,
// ascending. gqlc's own encode produces neither — it refuses them — but
// it writes to an ordinary agtype string property on a vertex any writer
// can touch, so what is read back is whatever the graph holds.
//
// The padding is enforced by the layout and not by a check beside it.
// time.Parse reads each field at a fixed width, so '2024-1-2' fails at
// the month, '24-01-02' at the year, and a signed or five-digit year at
// the first byte that is not a digit where one belongs — every spelling
// that would sort in the wrong place is refused before a Date is built.
//
// That leaves the range bounded at one end only, which is measured
// rather than an oversight. A year over 9999 needs a fifth digit and a
// year before 1 CE needs a sign, and the layout refuses both; year 0 is
// the one out-of-range year spelled with four unsigned digits, so it is
// the only one that reaches here, and it is what this bound is for.
func agtypeDate(raw []byte) (Date, error) {
	text, err := agtypeString(raw)
	if err != nil {
		return Date{}, err
	}
	at, err := time.Parse(agtypeDateLayout, text)
	if err != nil {
		return Date{}, fmt.Errorf("gqlc: %q is not a date in zero-padded ISO YYYY-MM-DD form: %w", text, err)
	}
	if at.Year() < 1 {
		return Date{}, fmt.Errorf("gqlc: %q is outside the year 1 to year 9999 range this encoding admits", text)
	}
	return Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}, nil
}

// agtypeDuration decodes a stored DURATION: the integer scalar, counting
// total microseconds. Signed, so a negative count is a duration
// backwards and orders below every positive one.
//
// What comes back is normalised, and cannot be otherwise: the stored
// count is one number, so the Months and Days a Duration can hold have
// nothing to be filled from and stay zero. A value written as 90 days
// reads back as 7776000 seconds. Months is zero rather than derived
// because no fixed count of microseconds is faithful to a month — which
// is the same reason the encode direction refuses a Duration carrying
// one instead of storing an approximation of it.
//
// The division floors rather than truncating, so Nanos is never
// negative and a duration backwards borrows from Seconds: -1500000
// microseconds is Seconds -2 and Nanos 500000000, not Seconds -1 and
// Nanos -500000000. Go's / and % truncate toward zero and would
// produce the second, which no neo4j value ever takes — the driver
// renders a Duration by borrowing from a negative Seconds against a
// positive Nanos, so a negative Nanos is a shape its own String method
// has no reading for. The two are the same amount of time either way;
// what floor division buys is that the components a caller reads off
// this carrier do not change meaning when the target does.
func agtypeDuration(raw []byte) (Duration, error) {
	micros, err := agtypeInt64(raw)
	if err != nil {
		return Duration{}, err
	}
	seconds := micros / 1000000
	rem := micros % 1000000
	if rem < 0 {
		seconds--
		rem += 1000000
	}
	return Duration{Seconds: seconds, Nanos: int(rem * 1000)}, nil
}

// agtypeDateText encodes a DATE into the string a query binds it as, the
// same text agtypeDate reads back.
//
// It fails rather than encodes twice over. A year outside
// [0001, 9999] has no zero-padded four-digit spelling, and the string it
// would get instead sorts in the wrong place — which is the one property
// the whole encoding rests on, so storing it would put a value in the
// column that silently breaks every ORDER BY over it. A Year, Month and
// Day naming no day on the calendar fails for the narrower reason that
// agtypeDate would refuse to read it back: time.Date rolls February 30th
// forward to March 2nd, and a round trip that returns a different date
// than it stored is not one.
func agtypeDateText(d Date) (string, error) {
	if d.Year < 1 || d.Year > 9999 {
		return "", fmt.Errorf(
			"gqlc: year %d is outside the year 1 to year 9999 range this encoding admits", d.Year)
	}
	at := time.Date(d.Year, time.Month(d.Month), d.Day, 0, 0, 0, 0, time.UTC)
	if (Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}) != d {
		return "", fmt.Errorf(
			"gqlc: year %d month %d day %d is not a date on the calendar", d.Year, d.Month, d.Day)
	}
	return at.Format(agtypeDateLayout), nil
}

// agtypeDurationMicros encodes a DURATION into the integer a query binds
// it as, the same count agtypeDuration reads back.
//
// A Duration carrying months is refused rather than approximated. A month
// is not a fixed count of microseconds — it is 28, 29, 30 or 31 days
// depending on where it lands — so any count this could return would be
// one the caller did not write, and a comparison against it would be
// answered wrongly rather than refused. ADR 0002 collapsed the
// (YEAR TO MONTH) and (DAY TO SECOND) qualifiers onto one carrier, so
// which of the two a value holds is not knowable until it is in hand:
// this is a run-time refusal because there is no generate-time question
// to ask.
//
// Days are not months. A day is fixed at 86400 seconds in this encoding,
// which carries no zone and so has no daylight-saving transition to fall
// on, and it folds into the count.
//
// Sub-microsecond precision truncates, as everywhere else here.
func agtypeDurationMicros(d Duration) (int64, error) {
	if d.Months != 0 {
		return 0, fmt.Errorf(
			"gqlc: a duration of %d months has no faithful encoding here, because a month is not a fixed count of microseconds", d.Months)
	}
	return (d.Days*86400+d.Seconds)*1000000 + int64(d.Nanos)/1000, nil
}

// agtypeEncodedNullable runs a fallible encoder over an absent value,
// which crosses as the agtype null a nullable parameter holds.
func agtypeEncodedNullable[T, E any](in *T, encode func(T) (E, error)) (*E, error) {
	if in == nil {
		return nil, nil
	}
	out, err := encode(*in)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// agtypeEncodedList runs a fallible encoder over every element of a bound
// list. The index is named on failure: the elements share one parameter
// name, so it is the only thing that says which value was refused.
func agtypeEncodedList[T, E any](in []T, encode func(T) (E, error)) ([]E, error) {
	out := make([]E, len(in))
	for i, v := range in {
		encoded, err := encode(v)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d: %w", i, err)
		}
		out[i] = encoded
	}
	return out, nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeList decodes an agtype list, reading each element through the
// decoder the caller supplies. The split steps over a nested string, map
// or list whole, so a comma inside one separates nothing; an element the
// decoder refuses fails the whole list rather than being dropped or
// zeroed, because a slice one element short is not the value the graph
// holds.
//
// The empty list decodes to a slice of length zero and not to nil: AGE
// stores it as a value, and a nil slice is what an absent property
// reaches the caller as.
func agtypeList[T any](raw []byte, decode func([]byte) (T, error)) ([]T, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '[' || body[len(body)-1] != ']' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype list", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make([]T, 0)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		elem := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])
		value, err := decode(elem)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d of %q: %w", len(out), raw, err)
		}
		out = append(out, value)
	}
	return out, nil
}

// agtypeListOfDate decodes an agtype list of Date elements.
func agtypeListOfDate(raw []byte) ([]Date, error) {
	return agtypeList(raw, agtypeDate)
}

// agtypeListOfDuration decodes an agtype list of Duration elements.
func agtypeListOfDuration(raw []byte) ([]Duration, error) {
	return agtypeList(raw, agtypeDuration)
}

// agtypeListOfInt32 decodes an agtype list of int32 elements.
func agtypeListOfInt32(raw []byte) ([]int32, error) {
	return agtypeList(raw, agtypeIntAs[int32])
}

// agtypeListOfString decodes an agtype list of string elements.
func agtypeListOfString(raw []byte) ([]string, error) {
	return agtypeList(raw, agtypeString)
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}

// agtypeNullableProperty reads one nullable property out of a split
// entity, where the absence agtypeProperty refuses is the schema's null
// and reaches the caller as the nil pointer.
func agtypeNullableProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (*T, error) {
	raw, ok := props[key]
	if !ok {
		return nil, nil
	}
	out, err := decode(raw)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
