// Code generated by gqlc dev. DO NOT EDIT.

package temporallistparam

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Slot corresponds to the Slot node type.
type Slot struct {
	Days  []Date
	Id    int64
	Ranks []int32
	Spans *[]Duration
	Tags  []string
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDateText encodes a DATE into the string a query binds it as, the
// same text agtypeDate reads back.
//
// It fails rather than encodes twice over. A year outside
// [0001, 9999] has no zero-padded four-digit spelling, and the string it
// would get instead sorts in the wrong place — which is the one property
// the whole encoding rests on, so storing it would put a value in the
// column that silently breaks every ORDER BY over it. A Year, Month and
// Day naming no day on the calendar fails for the narrower reason that
// agtypeDate would refuse to read it back: time.Date rolls February 30th
// forward to March 2nd, and a round trip that returns a different date
// than it stored is not one.
func agtypeDateText(d Date) (string, error) {
	if d.Year < 1 || d.Year > 9999 {
		return "", fmt.Errorf(
			"gqlc: year %d is outside the year 1 to year 9999 range this encoding admits", d.Year)
	}
	at := time.Date(d.Year, time.Month(d.Month), d.Day, 0, 0, 0, 0, time.UTC)
	if (Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}) != d {
		return "", fmt.Errorf(
			"gqlc: year %d month %d day %d is not a date on the calendar", d.Year, d.Month, d.Day)
	}
	return at.Format(agtypeDateLayout), nil
}

// agtypeDurationMicros encodes a DURATION into the integer a query binds
// it as, the same count agtypeDuration reads back.
//
// A Duration carrying months is refused rather than approximated. A month
// is not a fixed count of microseconds — it is 28, 29, 30 or 31 days
// depending on where it lands — so any count this could return would be
// one the caller did not write, and a comparison against it would be
// answered wrongly rather than refused. ADR 0002 collapsed the
// (YEAR TO MONTH) and (DAY TO SECOND) qualifiers onto one carrier, so
// which of the two a value holds is not knowable until it is in hand:
// this is a run-time refusal because there is no generate-time question
// to ask.
//
// Days are not months. A day is fixed at 86400 seconds in this encoding,
// which carries no zone and so has no daylight-saving transition to fall
// on, and it folds into the count.
//
// Sub-microsecond precision truncates, as everywhere else here.
func agtypeDurationMicros(d Duration) (int64, error) {
	if d.Months != 0 {
		return 0, fmt.Errorf(
			"gqlc: a duration of %d months has no faithful encoding here, because a month is not a fixed count of microseconds", d.Months)
	}
	return (d.Days*86400+d.Seconds)*1000000 + int64(d.Nanos)/1000, nil
}

// agtypeEncodedNullable runs a fallible encoder over an absent value,
// which crosses as the agtype null a nullable parameter holds.
func agtypeEncodedNullable[T, E any](in *T, encode func(T) (E, error)) (*E, error) {
	if in == nil {
		return nil, nil
	}
	out, err := encode(*in)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// agtypeEncodedList runs a fallible encoder over every element of a bound
// list. The index is named on failure: the elements share one parameter
// name, so it is the only thing that says which value was refused.
func agtypeEncodedList[T, E any](in []T, encode func(T) (E, error)) ([]E, error) {
	out := make([]E, len(in))
	for i, v := range in {
		encoded, err := encode(v)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d: %w", i, err)
		}
		out[i] = encoded
	}
	return out, nil
}
