// Code generated by gqlc dev. DO NOT EDIT.

package entityedgeprojectedone

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Movie corresponds to the Movie node type.
type Movie struct {
	Id int64
}

// Person corresponds to the Person node type.
type Person struct {
	Id int64
}

// ActedIn corresponds to the ACTED_IN edge type (Person -> Movie).
type ActedIn struct {
	Since int64
}

// decodeActedIn decodes a driver dbtype.Relationship into a ActedIn struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeActedIn(rel dbtype.Relationship) (ActedIn, error) {
	if rel.Type != "ACTED_IN" {
		return ActedIn{}, fmt.Errorf("decode ActedIn: expected a relationship of type %q, got %q", "ACTED_IN", rel.Type)
	}
	var out ActedIn
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return ActedIn{}, fmt.Errorf("decode ActedIn.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}
