// Code generated by gqlc dev. DO NOT EDIT.

package certifiedselection

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const minRankQueryText = `MATCH (p:Person) RETURN min(p.rank) AS m`

// MinRank executes the MinRank query.
//
//	MATCH (p:Person) RETURN min(p.rank) AS m
func (q *queries) MinRank(ctx context.Context) (*int32, error) {
	records, err := q.db.run(ctx, minRankQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[int64](records[0], "m")
	if err != nil {
		return nil, fmt.Errorf("MinRank: decode column %q: %w", "m", err)
	}
	var valuePtr *int32
	if !isNil {
		v, err := narrowInt[int32](value)
		if err != nil {
			return nil, fmt.Errorf("MinRank: decode column %q: %w", "m", err)
		}
		valuePtr = &v
	}
	return valuePtr, nil
}

const maxNameQueryText = `MATCH (p:Person) RETURN max(p.name) AS m`

// MaxName executes the MaxName query.
//
//	MATCH (p:Person) RETURN max(p.name) AS m
func (q *queries) MaxName(ctx context.Context) (*string, error) {
	records, err := q.db.run(ctx, maxNameQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "m")
	if err != nil {
		return nil, fmt.Errorf("MaxName: decode column %q: %w", "m", err)
	}
	var valuePtr *string
	if !isNil {
		v := value
		valuePtr = &v
	}
	return valuePtr, nil
}
