// Code generated by gqlc dev. DO NOT EDIT.

package writeoneprojectionentity

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const createPersonQueryText = `CREATE (p:Person {id: $id, name: $name}) RETURN p`

type CreatePersonParams struct {
	Id   int64
	Name string
}

// CreatePerson executes the CreatePerson query.
//
//	CREATE (p:Person {id: $id, name: $name}) RETURN p
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	records, err := q.db.run(ctx, createPersonQueryText, map[string]any{"id": arg.Id, "name": arg.Name}, neo4j.AccessModeWrite)
	if err != nil {
		return Person{}, err
	}
	if len(records) == 0 {
		return Person{}, ErrNoRows
	}
	if len(records) > 1 {
		return Person{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "p")
	if err != nil {
		return Person{}, fmt.Errorf("CreatePerson: decode column %q: %w", "p", err)
	}
	if isNil {
		return Person{}, fmt.Errorf("CreatePerson: column %q is non-nullable but arrived null", "p")
	}
	value, err := decodePerson(node)
	if err != nil {
		return Person{}, fmt.Errorf("CreatePerson: decode column %q: %w", "p", err)
	}
	return value, nil
}
