// Code generated by gqlc dev. DO NOT EDIT.

package uuidproperty

// UUID is a 128-bit UUID in the byte order RFC 9562 lays down: the
// value, with no textual form attached. Convert it to whichever UUID
// library this program already uses — those are [16]byte too, so the
// conversion is direct.
type UUID [16]byte
