// Code generated by gqlc dev. DO NOT EDIT.

package listexpressiondeclaredelements

import "context"

type ReadQuerier interface {
	AccountLiterals(ctx context.Context) ([]AccountLiteralsRow, error)
	AccountCollected(ctx context.Context) ([]AccountCollectedRow, error)
	AccountNested(ctx context.Context) ([]AccountNestedRow, error)
}

type WriteQuerier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
