// Code generated by gqlc dev. DO NOT EDIT.

package uuidproperty

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"uuid"
)

// Account corresponds to the Account node type.
type Account struct {
	Chain  *[]UUID
	Either *any
	Id     int64
	Prior  *UUID
	Ref    UUID
	Span   Duration
	Trail  *[]*UUID
}

// decodeAccount decodes an agtype vertex into a Account struct, enforcing
// the label and the per-property nullability the schema declares.
func decodeAccount(raw []byte) (Account, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Account{}, fmt.Errorf("decode Account: %w", err)
	}
	if label != "Account" {
		return Account{}, fmt.Errorf("decode Account: expected label %q, got %q", "Account", label)
	}
	var out Account
	value0, err := agtypeNullableProperty(props, "chain", agtypeListOfUUID)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Chain: %w", err)
	}
	out.Chain = value0
	value1, err := agtypeNullableProperty(props, "either", decodeUnion26f53c9e)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Either: %w", err)
	}
	out.Either = value1
	value2, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Id: %w", err)
	}
	out.Id = value2
	value3, err := agtypeNullableProperty(props, "prior", agtypeUUID)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Prior: %w", err)
	}
	out.Prior = value3
	value4, err := agtypeProperty(props, "ref", agtypeUUID)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Ref: %w", err)
	}
	out.Ref = value4
	value5, err := agtypeProperty(props, "span", agtypeDuration)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Span: %w", err)
	}
	out.Span = value5
	value6, err := agtypeNullableProperty(props, "trail", agtypeListOfNullableUUID)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Trail: %w", err)
	}
	out.Trail = value6
	return out, nil
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeUUID decodes a stored UUID. agtype has no 128-bit value, so gqlc
// stores one as the string scalar in its RFC 9562 text. The slot is an
// ordinary agtype string on a vertex any writer can touch, so what is
// read back is whatever the graph holds: text that is not a UUID fails
// the read rather than arriving as the zero UUID.
//
// There is no encoder beside this. A UUID parameter crosses through the
// JSON encoder every argument does, and uuid.UUID marshals itself as the
// lowercase hyphenated text this reads — bare, behind a pointer, and as
// a list element alike.
func agtypeUUID(raw []byte) (UUID, error) {
	text, err := agtypeString(raw)
	if err != nil {
		return UUID{}, err
	}
	id, err := uuid.Parse(text)
	if err != nil {
		return UUID{}, fmt.Errorf("gqlc: %q is not a UUID: %w", text, err)
	}
	return id, nil
}

// agtypeDuration decodes a stored DURATION: the integer scalar, counting
// total microseconds. Signed, so a negative count is a duration
// backwards and orders below every positive one.
//
// What comes back is normalised, and cannot be otherwise: the stored
// count is one number, so the Months and Days a Duration can hold have
// nothing to be filled from and stay zero. A value written as 90 days
// reads back as 7776000 seconds. Months is zero rather than derived
// because no fixed count of microseconds is faithful to a month — which
// is the same reason the encode direction refuses a Duration carrying
// one instead of storing an approximation of it.
//
// The division floors rather than truncating, so Nanos is never
// negative and a duration backwards borrows from Seconds: -1500000
// microseconds is Seconds -2 and Nanos 500000000, not Seconds -1 and
// Nanos -500000000. Go's / and % truncate toward zero and would
// produce the second, which no neo4j value ever takes — the driver
// renders a Duration by borrowing from a negative Seconds against a
// positive Nanos, so a negative Nanos is a shape its own String method
// has no reading for. The two are the same amount of time either way;
// what floor division buys is that the components a caller reads off
// this carrier do not change meaning when the target does.
func agtypeDuration(raw []byte) (Duration, error) {
	micros, err := agtypeInt64(raw)
	if err != nil {
		return Duration{}, err
	}
	seconds := micros / 1000000
	rem := micros % 1000000
	if rem < 0 {
		seconds--
		rem += 1000000
	}
	return Duration{Seconds: seconds, Nanos: int(rem * 1000)}, nil
}

// agtypeDurationMicros encodes a DURATION into the integer a query binds
// it as, the same count agtypeDuration reads back.
//
// A Duration carrying months is refused rather than approximated. A month
// is not a fixed count of microseconds — it is 28, 29, 30 or 31 days
// depending on where it lands — so any count this could return would be
// one the caller did not write, and a comparison against it would be
// answered wrongly rather than refused. ADR 0002 collapsed the
// (YEAR TO MONTH) and (DAY TO SECOND) qualifiers onto one carrier, so
// which of the two a value holds is not knowable until it is in hand:
// this is a run-time refusal because there is no generate-time question
// to ask.
//
// Days are not months. A day is fixed at 86400 seconds in this encoding,
// which carries no zone and so has no daylight-saving transition to fall
// on, and it folds into the count.
//
// Sub-microsecond precision truncates, as everywhere else here.
func agtypeDurationMicros(d Duration) (int64, error) {
	if d.Months != 0 {
		return 0, fmt.Errorf(
			"gqlc: a duration of %d months has no faithful encoding here, because a month is not a fixed count of microseconds", d.Months)
	}
	return (d.Days*86400+d.Seconds)*1000000 + int64(d.Nanos)/1000, nil
}

// agtypeEncodedNullable runs a fallible encoder over an absent value,
// which crosses as the agtype null a nullable parameter holds.
func agtypeEncodedNullable[T, E any](in *T, encode func(T) (E, error)) (*E, error) {
	if in == nil {
		return nil, nil
	}
	out, err := encode(*in)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeList decodes an agtype list, reading each element through the
// decoder the caller supplies. The split steps over a nested string, map
// or list whole, so a comma inside one separates nothing; an element the
// decoder refuses fails the whole list rather than being dropped or
// zeroed, because a slice one element short is not the value the graph
// holds.
//
// The empty list decodes to a slice of length zero and not to nil: AGE
// stores it as a value, and a nil slice is what an absent property
// reaches the caller as.
func agtypeList[T any](raw []byte, decode func([]byte) (T, error)) ([]T, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '[' || body[len(body)-1] != ']' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype list", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make([]T, 0)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		elem := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])
		value, err := decode(elem)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d of %q: %w", len(out), raw, err)
		}
		out = append(out, value)
	}
	return out, nil
}

// agtypeNullableElem lifts an element decoder over the null a list whose
// element type is nullable may hold. Every decoder agtypeList is given
// refuses the literal null, which is what the NOT NULL element wants;
// this is the one place that answer changes, and it answers with the nil
// pointer rather than the Go zero, because a null read as "" or 0 is a
// value the graph does not hold.
//
// The whole-value position has no need of this: a null property is
// absent from the entity's map entirely, and agtypeNullableProperty
// reads that absence. Inside a list the null is present as a token, so
// it has to be recognised here.
func agtypeNullableElem[T any](decode func([]byte) (T, error)) func([]byte) (*T, error) {
	return func(raw []byte) (*T, error) {
		if agtypeIsNull(raw) {
			return nil, nil
		}
		out, err := decode(raw)
		if err != nil {
			return nil, err
		}
		return &out, nil
	}
}

// agtypeIsNull reports whether a raw span is agtype's null. It is a
// named helper rather than a comparison inside the closure above so that
// the spelling the wire uses is one thing with one name.
func agtypeIsNull(raw []byte) bool {
	return string(bytes.TrimSpace(raw)) == "null"
}

// agtypeListOfNullableUUID decodes an agtype list of *UUID elements.
func agtypeListOfNullableUUID(raw []byte) ([]*UUID, error) {
	return agtypeList(raw, agtypeNullableElem(agtypeUUID))
}

// agtypeListOfUUID decodes an agtype list of UUID elements.
func agtypeListOfUUID(raw []byte) ([]UUID, error) {
	return agtypeList(raw, agtypeUUID)
}

// decodeUnion26f53c9e dispatches an agtype value onto the member of
// UNION<INT64|UUID> whose wire family it arrived as, and narrows it
// to that member's declared width.
func decodeUnion26f53c9e(raw []byte) (any, error) {
	body := bytes.TrimSpace(raw)
	if len(body) == 0 {
		return nil, fmt.Errorf("decode UNION<INT64|UUID>: %q is not an agtype value", raw)
	}
	switch body[0] {
	case '"':
		out, err := agtypeUUID(body)
		if err != nil {
			return nil, fmt.Errorf("decode UNION<INT64|UUID>: %w", err)
		}
		return out, nil
	}
	if out, err := agtypeInt64(body); err == nil {
		return out, nil
	}
	return nil, fmt.Errorf("decode UNION<INT64|UUID>: %q is no member's wire shape", raw)
}

// encodeUnion26f53c9e validates a value against the member set UNION<INT64|UUID>
// declares, and renders the matched member as what this store binds it
// as. A value outside the set is refused by name, which is what
// declaring the members buys over ADR 0020's open union.
func encodeUnion26f53c9e(v any) (any, error) {
	switch t := v.(type) {
	case int64:
		return t, nil
	case UUID:
		return t, nil
	}
	return nil, fmt.Errorf("encode UNION<INT64|UUID>: no member carries %T", v)
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}

// agtypeNullableProperty reads one nullable property out of a split
// entity, where the absence agtypeProperty refuses is the schema's null
// and reaches the caller as the nil pointer.
func agtypeNullableProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (*T, error) {
	raw, ok := props[key]
	if !ok {
		return nil, nil
	}
	out, err := decode(raw)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
