// Code generated by gqlc dev. DO NOT EDIT.

package uniononlycarrierentitydecodeonly

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// decodeUnion0aa394d5 dispatches a driver value onto the member of UNION<DATE|INT64> whose wire
// shape it arrived as, and narrows it to that member's declared width.
func decodeUnion0aa394d5(v any) (any, error) {
	switch t := v.(type) {
	case dbtype.Date:
		v1 := toDate(t)
		return v1, nil
	case int64:
		return t, nil
	}
	return nil, fmt.Errorf("decode %s: no member carries %T", "UNION<DATE|INT64>", v)
}

// decodeUnion26f53c9e dispatches a driver value onto the member of UNION<INT64|UUID> whose wire
// shape it arrived as, and narrows it to that member's declared width.
func decodeUnion26f53c9e(v any) (any, error) {
	switch t := v.(type) {
	case int64:
		return t, nil
	case string:
		v1, err := toUUID(t)
		if err != nil {
			return nil, fmt.Errorf("decode %s: %w", "UNION<INT64|UUID>", err)
		}
		return v1, nil
	}
	return nil, fmt.Errorf("decode %s: no member carries %T", "UNION<INT64|UUID>", v)
}
