// Code generated by gqlc dev. DO NOT EDIT.

package manycolmany

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const peopleByAgeAndLocaleQueryText = `MATCH (p:Person) WHERE p.age > $minAge AND p.locale = $locale RETURN p.name, p.age`

type PeopleByAgeAndLocaleParams struct {
	MinAge int64
	Locale string
}

type PeopleByAgeAndLocaleRow struct {
	Name string
	Age  int64
}

// PeopleByAgeAndLocale executes the PeopleByAgeAndLocale query.
//
//	MATCH (p:Person) WHERE p.age > $minAge AND p.locale = $locale RETURN p.name, p.age
func (q *Queries) PeopleByAgeAndLocale(ctx context.Context, arg PeopleByAgeAndLocaleParams) ([]PeopleByAgeAndLocaleRow, error) {
	records, err := q.db.run(ctx, peopleByAgeAndLocaleQueryText, map[string]any{"minAge": arg.MinAge, "locale": arg.Locale}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]PeopleByAgeAndLocaleRow, 0, len(records))
	for _, record := range records {
		var row PeopleByAgeAndLocaleRow
		value0, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("PeopleByAgeAndLocale: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("PeopleByAgeAndLocale: column %q is non-nullable but arrived null", "p.name")
		}
		row.Name = value0
		value1, isNil, err := neo4j.GetRecordValue[int64](record, "p.age")
		if err != nil {
			return nil, fmt.Errorf("PeopleByAgeAndLocale: decode column %q: %w", "p.age", err)
		}
		if isNil {
			return nil, fmt.Errorf("PeopleByAgeAndLocale: column %q is non-nullable but arrived null", "p.age")
		}
		row.Age = value1
		out = append(out, row)
	}
	return out, nil
}
