// Code generated by gqlc dev. DO NOT EDIT.

package nullablecolumns

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// ErrNoRows is returned by a :one method when the query produced zero
// rows. Callers branch with errors.Is.
var ErrNoRows = errors.New("gqlc: no rows in result set")

// ErrMultipleResults is returned by a :one method when the query
// produced more than one row. Callers branch with errors.Is.
var ErrMultipleResults = errors.New("gqlc: multiple rows in :one result set")

// DBTX is the pgx surface the generated methods run against.
// *pgxpool.Pool, *pgx.Conn and pgx.Tx all satisfy it, so the caller
// chooses the scope without this package naming a concrete type.
type DBTX interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
}

type Queries struct {
	db    DBTX
	graph string
}

// New returns a Queries bound to db and to one AGE graph. The binding is
// the handle's identity: every method on it addresses that graph. Every
// connection db hands out must have been through SessionInit.
//
// The name is not judged here. AGE's verdict on it arrives from the
// server, at EnsureGraph.
func New(db DBTX, graph string) *Queries {
	return &Queries{db: db, graph: graph}
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx, graph: q.graph}
}

// maxGraphNameBytes is the capacity of PostgreSQL's name type,
// NAMEDATALEN - 1. It is a compile-time property of the server's type,
// not of AGE.
const maxGraphNameBytes = 63

// boundGraph returns the name New bound, once it is short enough to
// reach the server whole. PostgreSQL's name type keeps the leading
// maxGraphNameBytes bytes and drops the rest without raising, so two
// handles whose names differ only past that point address one graph: the
// second EnsureGraph finds it already there and reports nothing, a read
// returns the first's rows, and either handle's DropGraph takes both.
// The limit counts bytes because that is what the type truncates on, so
// a name of 63 multi-byte characters is over it.
//
// Every statement carrying the name is built from this return value, so
// the length is established once and no call site holds a name that has
// not been through it.
func (q *Queries) boundGraph() (string, error) {
	if len(q.graph) > maxGraphNameBytes {
		return "", fmt.Errorf("gqlc: graph name %q is %d bytes, over the %d that PostgreSQL's name type holds: the rest would be dropped silently and this handle could address another graph",
			q.graph, len(q.graph), maxGraphNameBytes)
	}
	return q.graph, nil
}

// cypherStmt composes the statement one query method runs: the bound
// graph name, the query text between the delimiters tag opens and
// closes, and the record shape a set-returning cypher() call declares.
//
// The name travels inside the statement text because AGE resolves
// cypher()'s graph argument during parse analysis and accepts a constant
// there and nothing else. An E-string is the literal form whose escapes
// mean the same thing whatever standard_conforming_strings is set to, so
// escaping the backslash and the quote is the whole of what makes an
// arbitrary bound name arrive as itself. Query arguments never travel
// this way: they bind to $1.
func (q *Queries) cypherStmt(tag, text, record string) (string, error) {
	graph, err := q.boundGraph()
	if err != nil {
		return "", err
	}
	escaped := strings.ReplaceAll(strings.ReplaceAll(graph, `\`, `\\`), `'`, `\'`)
	return "SELECT * FROM ag_catalog.cypher(E'" + escaped + "', " + tag + text + tag + ", $1) AS (" + record + ")", nil
}
