// Code generated by gqlc dev. DO NOT EDIT.

package nullablecolumns

import (
	"context"
	"fmt"
)

const personProfileQueryText = `MATCH (p:Person) WHERE p.id = $id RETURN p.name, p.nickname, p.age`

type PersonProfileRow struct {
	Name     string
	Nickname *string
	Age      *int64
}

// PersonProfile executes the PersonProfile query.
//
//	MATCH (p:Person) WHERE p.id = $id RETURN p.name, p.nickname, p.age
func (q *Queries) PersonProfile(ctx context.Context, id int64) (PersonProfileRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", personProfileQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype, v2 ag_catalog.agtype")
	if err != nil {
		return PersonProfileRow{}, err
	}
	args, err := agtypeArgs(map[string]any{"id": id})
	if err != nil {
		return PersonProfileRow{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return PersonProfileRow{}, fmt.Errorf("PersonProfile: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return PersonProfileRow{}, fmt.Errorf("PersonProfile: %w", err)
		}
		return PersonProfileRow{}, ErrNoRows
	}
	var raw0 []byte
	var raw1 []byte
	var raw2 []byte
	if err := rows.Scan(&raw0, &raw1, &raw2); err != nil {
		return PersonProfileRow{}, fmt.Errorf("PersonProfile: scan row: %w", err)
	}
	if rows.Next() {
		return PersonProfileRow{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return PersonProfileRow{}, fmt.Errorf("PersonProfile: %w", err)
	}
	if raw0 == nil {
		return PersonProfileRow{}, fmt.Errorf("PersonProfile: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return PersonProfileRow{}, fmt.Errorf("PersonProfile: decode column %q: %w", "p.name", err)
	}
	var value1 *string
	if raw1 != nil {
		decoded, err := agtypeString(raw1)
		if err != nil {
			return PersonProfileRow{}, fmt.Errorf("PersonProfile: decode column %q: %w", "p.nickname", err)
		}
		value1 = &decoded
	}
	var value2 *int64
	if raw2 != nil {
		decoded, err := agtypeInt64(raw2)
		if err != nil {
			return PersonProfileRow{}, fmt.Errorf("PersonProfile: decode column %q: %w", "p.age", err)
		}
		value2 = &decoded
	}
	return PersonProfileRow{
		Name:     value0,
		Nickname: value1,
		Age:      value2,
	}, nil
}
