// Code generated by gqlc dev. DO NOT EDIT.

package entitynodeprojectedone

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Id         int64
	MiddleName *string
	Name       string
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing per-property nullability against the schema.
func decodePerson(node dbtype.Node) (Person, error) {
	var out Person
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = value0
	if v, ok := node.Props["middleName"]; ok {
		s, ok := v.(string)
		if !ok {
			return Person{}, fmt.Errorf("decode Person.MiddleName: property %q: expected string, got %T", "middleName", v)
		}
		out.MiddleName = &s
	}
	value2, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Name: %w", err)
	}
	out.Name = value2
	return out, nil
}
