// Code generated by gqlc dev. DO NOT EDIT.

package edgeuniontwoedgeunioncolumns

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Id int64
}

// Post corresponds to the Post node type.
type Post struct {
	Id int64
}

// Authored corresponds to the AUTHORED edge type (Person -> Post).
type Authored struct {
	Since int64
}

func (Authored) isPairActionsR1() {}
func (Authored) isPairActionsR2() {}

// decodeAuthored decodes a driver dbtype.Relationship into a Authored struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeAuthored(rel dbtype.Relationship) (Authored, error) {
	if rel.Type != "AUTHORED" {
		return Authored{}, fmt.Errorf("decode Authored: expected a relationship of type %q, got %q", "AUTHORED", rel.Type)
	}
	var out Authored
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return Authored{}, fmt.Errorf("decode Authored.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}

// Likes corresponds to the LIKES edge type (Person -> Post).
type Likes struct {
}

func (Likes) isPairActionsR1() {}
func (Likes) isPairActionsR2() {}

// decodeLikes decodes a driver dbtype.Relationship into a Likes struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeLikes(rel dbtype.Relationship) (Likes, error) {
	if rel.Type != "LIKES" {
		return Likes{}, fmt.Errorf("decode Likes: expected a relationship of type %q, got %q", "LIKES", rel.Type)
	}
	var out Likes
	return out, nil
}

//sumtype:decl
type PairActionsR1 interface{ isPairActionsR1() }

//sumtype:decl
type PairActionsR2 interface{ isPairActionsR2() }
