// Code generated by gqlc dev. DO NOT EDIT.

package onecolmany

import "context"

type ReadQuerier interface {
	AllPersonNames(ctx context.Context) ([]string, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
