// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionlist

import "context"

type ReadQuerier interface {
	PathActions(ctx context.Context) ([]PathActionsR, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
