// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionundirectedselfloop

import "context"

type ReadQuerier interface {
	GetLink(ctx context.Context) (GetLinkR, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
