// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionmanytwocandidates

import (
	"context"
	"fmt"
)

const listActionsQueryText = `MATCH (:Person)-[r:AUTHORED|LIKES]->(:Post) RETURN r`

// ListActions executes the ListActions query.
//
//	MATCH (:Person)-[r:AUTHORED|LIKES]->(:Post) RETURN r
func (q *Queries) ListActions(ctx context.Context) ([]ListActionsR, error) {
	stmt, err := q.cypherStmt("$gqlc$", listActionsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("ListActions: %w", err)
	}
	defer rows.Close()
	out := make([]ListActionsR, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("ListActions: scan row: %w", err)
		}
		var value0 ListActionsR
		if raw0 == nil {
			return nil, fmt.Errorf("ListActions: column %q is non-nullable but arrived null", "r")
		}
		label0, _, err := agtypeEntity(raw0, "::edge")
		if err != nil {
			return nil, fmt.Errorf("ListActions: decode column %q: %w", "r", err)
		}
		switch label0 {
		case "AUTHORED":
			decoded, err := decodeAUTHORED(raw0)
			if err != nil {
				return nil, fmt.Errorf("ListActions: decode column %q: %w", "r", err)
			}
			value0 = decoded
		case "LIKES":
			decoded, err := decodeLIKES(raw0)
			if err != nil {
				return nil, fmt.Errorf("ListActions: decode column %q: %w", "r", err)
			}
			value0 = decoded
		default:
			return nil, fmt.Errorf("ListActions: column %q: unexpected edge label %q", "r", label0)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("ListActions: %w", err)
	}
	return out, nil
}
