// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionundeclaredrelationshiptype

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Id int64
}

// Post corresponds to the Post node type.
type Post struct {
	Id int64
}

// Authored corresponds to the AUTHORED edge type (Person -> Post).
type Authored struct {
	Since int64
}

func (Authored) isActionOnPostR() {}

// decodeAuthored decodes a driver dbtype.Relationship into a Authored struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeAuthored(rel dbtype.Relationship) (Authored, error) {
	if rel.Type != "AUTHORED" {
		return Authored{}, fmt.Errorf("decode Authored: expected a relationship of type %q, got %q", "AUTHORED", rel.Type)
	}
	var out Authored
	value0, err := neo4j.GetProperty[int64](rel, "since")
	if err != nil {
		return Authored{}, fmt.Errorf("decode Authored.Since: %w", err)
	}
	out.Since = value0
	return out, nil
}

// Likes corresponds to the LIKES edge type (Person -> Post).
type Likes struct {
	Rating int64
}

func (Likes) isActionOnPostR() {}

// decodeLikes decodes a driver dbtype.Relationship into a Likes struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeLikes(rel dbtype.Relationship) (Likes, error) {
	if rel.Type != "LIKES" {
		return Likes{}, fmt.Errorf("decode Likes: expected a relationship of type %q, got %q", "LIKES", rel.Type)
	}
	var out Likes
	value0, err := neo4j.GetProperty[int64](rel, "rating")
	if err != nil {
		return Likes{}, fmt.Errorf("decode Likes.Rating: %w", err)
	}
	out.Rating = value0
	return out, nil
}

//sumtype:decl
type ActionOnPostR interface{ isActionOnPostR() }
