// Code generated by gqlc dev. DO NOT EDIT.

package entityexplicitname

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Actor corresponds to the Person node type.
type Actor struct {
	Id   int64
	Name string
}

// decodeActor decodes a driver dbtype.Node into a Actor struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeActor(node dbtype.Node) (Actor, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Person" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Actor{}, fmt.Errorf("decode Actor: expected a node labelled %q, got labels %q", "Person", node.Labels)
	}
	var out Actor
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Actor{}, fmt.Errorf("decode Actor.Id: %w", err)
	}
	out.Id = value0
	value1, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Actor{}, fmt.Errorf("decode Actor.Name: %w", err)
	}
	out.Name = value1
	return out, nil
}
