// Code generated by gqlc dev. DO NOT EDIT.

package entityexplicitname

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Actor corresponds to the Person node type.
type Actor struct {
	Id   int64
	Name string
}

// decodeActor decodes a driver dbtype.Node into a Actor struct,
// enforcing per-property nullability against the schema.
func decodeActor(node dbtype.Node) (Actor, error) {
	var out Actor
	id, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Actor{}, fmt.Errorf("decode Actor.Id: %w", err)
	}
	out.Id = id
	name, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Actor{}, fmt.Errorf("decode Actor.Name: %w", err)
	}
	out.Name = name
	return out, nil
}
