// Code generated by gqlc dev. DO NOT EDIT.

package zonedtimeroundtrip

import (
	"time"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// toTime reads the clock components and the zone offset off a driver
// zoned time. The offset is east-positive, matching the wire.
func toTime(v dbtype.Time) Time {
	t := time.Time(v)
	hour, minute, second := t.Clock()
	_, offset := t.Zone()
	return Time{Hour: hour, Minute: minute, Second: second, Nanosecond: t.Nanosecond(), OffsetSeconds: offset}
}

// fromTime builds the driver zoned time the packer turns into
// (nanoseconds since local midnight, offset seconds). The zone is
// named "Offset" because that is the name the driver's own hydrator
// gives a fixed-offset zone.
func fromTime(v Time) dbtype.Time {
	zone := time.FixedZone("Offset", v.OffsetSeconds)
	return dbtype.Time(time.Date(0, time.January, 1, v.Hour, v.Minute, v.Second, v.Nanosecond, zone))
}
