// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionundirectedselfloop

import (
	"context"
	"fmt"
)

const getLinkQueryText = `MATCH (x:Person)-[r:LIKES|WROTE]-(y:Person) RETURN r`

// GetLink executes the GetLink query.
//
//	MATCH (x:Person)-[r:LIKES|WROTE]-(y:Person) RETURN r
func (q *Queries) GetLink(ctx context.Context) (GetLinkR, error) {
	stmt, err := q.cypherStmt("$gqlc$", getLinkQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("GetLink: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("GetLink: %w", err)
		}
		return nil, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return nil, fmt.Errorf("GetLink: scan row: %w", err)
	}
	if rows.Next() {
		return nil, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("GetLink: %w", err)
	}
	var value0 GetLinkR
	if raw0 == nil {
		return nil, fmt.Errorf("GetLink: column %q is non-nullable but arrived null", "r")
	}
	label0, _, err := agtypeEntity(raw0, "::edge")
	if err != nil {
		return nil, fmt.Errorf("GetLink: decode column %q: %w", "r", err)
	}
	switch label0 {
	case "LIKES":
		decoded, err := decodeLikes(raw0)
		if err != nil {
			return nil, fmt.Errorf("GetLink: decode column %q: %w", "r", err)
		}
		value0 = decoded
	case "WROTE":
		decoded, err := decodeWrote(raw0)
		if err != nil {
			return nil, fmt.Errorf("GetLink: decode column %q: %w", "r", err)
		}
		value0 = decoded
	default:
		return nil, fmt.Errorf("GetLink: column %q: unexpected edge label %q", "r", label0)
	}
	return value0, nil
}
