// Code generated by gqlc dev. DO NOT EDIT.

package unionproperty

import "context"

type ReadQuerier interface {
	RowWhole(ctx context.Context) (Row, error)
	RowColumns(ctx context.Context) ([]RowColumnsRow, error)
	RowsByPick(ctx context.Context, arg *any) ([]int64, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
