// Code generated by gqlc dev. DO NOT EDIT.

package uint64parameter

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Counter corresponds to the Counter node type.
type Counter struct {
	Hits   uint64
	Id     int64
	Misses *uint64
	Runs   []uint64
	Spans  *[]uint64
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeUnsigned encodes an unsigned value into the signed 64-bit integer
// an agtype scalar carries, refusing one above that range rather than
// letting it cross as the negative it would wrap to.
//
// This is the encode side of the readable set agtypeIntAs names: a UINT64
// value above MaxInt64 is unstorable, so refusing it here is refusing to
// write a value no read could ever return. uint8, uint16 and uint32 are
// absent because every one of their values fits, and uint is here because
// on a 64-bit platform it is uint64 (bd gqlc-tzjqu).
func agtypeUnsigned[T ~uint | ~uint64](v T) (int64, error) {
	const maxInt64 = 1<<63 - 1
	if uint64(v) > maxInt64 {
		return 0, fmt.Errorf(
			"gqlc: value %d does not fit the signed 64-bit integer an agtype scalar carries", v)
	}
	return int64(v), nil
}

// agtypeEncodedNullable runs a fallible encoder over an absent value,
// which crosses as the agtype null a nullable parameter holds.
func agtypeEncodedNullable[T, E any](in *T, encode func(T) (E, error)) (*E, error) {
	if in == nil {
		return nil, nil
	}
	out, err := encode(*in)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// agtypeEncodedList runs a fallible encoder over every element of a bound
// list. The index is named on failure: the elements share one parameter
// name, so it is the only thing that says which value was refused.
func agtypeEncodedList[T, E any](in []T, encode func(T) (E, error)) ([]E, error) {
	out := make([]E, len(in))
	for i, v := range in {
		encoded, err := encode(v)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d: %w", i, err)
		}
		out[i] = encoded
	}
	return out, nil
}
