// Code generated by gqlc dev. DO NOT EDIT.

package writeexecdelete

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const removePersonQueryText = `MATCH (p:Person) WHERE p.id = $id DELETE p`

// RemovePerson executes the RemovePerson query.
//
//	MATCH (p:Person) WHERE p.id = $id DELETE p
func (q *Queries) RemovePerson(ctx context.Context, id int64) error {
	_, err := q.db.run(ctx, removePersonQueryText, map[string]any{"id": id}, neo4j.AccessModeWrite)
	return err
}
