// Code generated by gqlc dev. DO NOT EDIT.

package entitydecodedonlyaslistelement

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Tag corresponds to the Tag node type.
type Tag struct {
	Name string
}

// Near corresponds to the NEAR edge type (Tag -> Tag).
type Near struct {
	Weight int32
}

// decodeNear decodes a driver dbtype.Relationship into a Near struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeNear(rel dbtype.Relationship) (Near, error) {
	if rel.Type != "NEAR" {
		return Near{}, fmt.Errorf("decode Near: expected a relationship of type %q, got %q", "NEAR", rel.Type)
	}
	var out Near
	value0, err := neo4j.GetProperty[int64](rel, "weight")
	if err != nil {
		return Near{}, fmt.Errorf("decode Near.Weight: %w", err)
	}
	value0n, err := narrowInt[int32](value0)
	if err != nil {
		return Near{}, fmt.Errorf("decode Near.Weight: %w", err)
	}
	out.Weight = value0n
	return out, nil
}

// narrowInt converts a driver's int64 down to the integer width the
// schema declared, refusing a value that width cannot represent.
//
// The round-trip catches every width whose range is a strict subset of
// int64's. uint64 is the one where it does not: the conversion is a
// bijection there, so uint64(-1) round-trips back to -1 unchanged and
// only the sign disagreement gives it away. A uint64 property's readable
// range is [0, MaxInt64] — the wire integer is signed 64-bit — so a
// negative carrier is always a violation rather than a large value.
func narrowInt[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](v int64) (T, error) {
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}
