// Code generated by gqlc dev. DO NOT EDIT.

package queryparamshadowsbodylocal

import (
	"context"
	"fmt"
)

const personByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt RETURN p.name`

// PersonByStmt executes the PersonByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt RETURN p.name
func (q *Queries) PersonByStmt(ctx context.Context, stmt string) (string, error) {
	stmt_, err := q.cypherStmt("$gqlc$", personByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"stmt": stmt})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt_, args)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByStmt: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByStmt: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByStmt: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByStmt: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args RETURN p.name`

// PersonByArgs executes the PersonByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args RETURN p.name
func (q *Queries) PersonByArgs(ctx context.Context, args string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args_, err := agtypeArgs(map[string]any{"args": args})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args_)
	if err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByArgs: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByArgs: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByArgs: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonByArgs: %w", err)
	}
	return out, nil
}

const personByRowsQueryText = `MATCH (p:Person) WHERE p.name = $rows RETURN p.name`

// PersonByRows executes the PersonByRows query.
//
//	MATCH (p:Person) WHERE p.name = $rows RETURN p.name
func (q *Queries) PersonByRows(ctx context.Context, rows string) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRowsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	args, err := agtypeArgs(map[string]any{"rows": rows})
	if err != nil {
		return nil, err
	}
	rows_, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	defer rows_.Close()
	out := make([]string, 0)
	for rows_.Next() {
		var raw0 []byte
		if err := rows_.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonByRows: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonByRows: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonByRows: decode column %q: %w", "p.name", err)
		}
		out = append(out, value0)
	}
	if err := rows_.Err(); err != nil {
		return nil, fmt.Errorf("PersonByRows: %w", err)
	}
	return out, nil
}

const personByRaw0QueryText = `MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name`

// PersonByRaw0 executes the PersonByRaw0 query.
//
//	MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name
func (q *Queries) PersonByRaw0(ctx context.Context, raw0 string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByRaw0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"raw0": raw0})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByRaw0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0_ []byte
	if err := rows.Scan(&raw0_); err != nil {
		return "", fmt.Errorf("PersonByRaw0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByRaw0: %w", err)
	}
	if raw0_ == nil {
		return "", fmt.Errorf("PersonByRaw0: column %q is non-nullable but arrived null", "p.name")
	}
	value0, err := agtypeString(raw0_)
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: decode column %q: %w", "p.name", err)
	}
	return value0, nil
}

const personByValue0QueryText = `MATCH (p:Person) WHERE p.name = $value0 RETURN p.name`

// PersonByValue0 executes the PersonByValue0 query.
//
//	MATCH (p:Person) WHERE p.name = $value0 RETURN p.name
func (q *Queries) PersonByValue0(ctx context.Context, value0 string) (string, error) {
	stmt, err := q.cypherStmt("$gqlc$", personByValue0QueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return "", err
	}
	args, err := agtypeArgs(map[string]any{"value0": value0})
	if err != nil {
		return "", err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return "", fmt.Errorf("PersonByValue0: %w", err)
		}
		return "", ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return "", fmt.Errorf("PersonByValue0: scan row: %w", err)
	}
	if rows.Next() {
		return "", ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("PersonByValue0: %w", err)
	}
	if raw0 == nil {
		return "", fmt.Errorf("PersonByValue0: column %q is non-nullable but arrived null", "p.name")
	}
	value0_, err := agtypeString(raw0)
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: decode column %q: %w", "p.name", err)
	}
	return value0_, nil
}

const deleteByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt DELETE p`

// DeleteByStmt executes the DeleteByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt DELETE p
func (q *Queries) DeleteByStmt(ctx context.Context, stmt string) error {
	stmt_, err := q.cypherStmt("$gqlc$", deleteByStmtQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"stmt": stmt})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt_, args); err != nil {
		return fmt.Errorf("DeleteByStmt: %w", err)
	}
	return nil
}

const deleteByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args DELETE p`

// DeleteByArgs executes the DeleteByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args DELETE p
func (q *Queries) DeleteByArgs(ctx context.Context, args string) error {
	stmt, err := q.cypherStmt("$gqlc$", deleteByArgsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args_, err := agtypeArgs(map[string]any{"args": args})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args_); err != nil {
		return fmt.Errorf("DeleteByArgs: %w", err)
	}
	return nil
}
