// Code generated by gqlc dev. DO NOT EDIT.

package entityedgeprojectedone

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const oneActedInQueryText = `MATCH (:Person)-[r:ACTED_IN]->(:Movie) RETURN r`

// OneActedIn executes the OneActedIn query.
//
//	MATCH (:Person)-[r:ACTED_IN]->(:Movie) RETURN r
func (q *queries) OneActedIn(ctx context.Context) (ActedIn, error) {
	records, err := q.db.run(ctx, oneActedInQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return ActedIn{}, err
	}
	if len(records) == 0 {
		return ActedIn{}, ErrNoRows
	}
	if len(records) > 1 {
		return ActedIn{}, ErrMultipleResults
	}
	rel, isNil, err := neo4j.GetRecordValue[dbtype.Relationship](records[0], "r")
	if err != nil {
		return ActedIn{}, fmt.Errorf("OneActedIn: decode column %q: %w", "r", err)
	}
	if isNil {
		return ActedIn{}, fmt.Errorf("OneActedIn: column %q is non-nullable but arrived null", "r")
	}
	value, err := decodeActedIn(rel)
	if err != nil {
		return ActedIn{}, fmt.Errorf("OneActedIn: decode column %q: %w", "r", err)
	}
	return value, nil
}
