// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumnduration

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const oneWeekQueryText = `RETURN duration({days: 7}) AS d`

// OneWeek executes the OneWeek query.
//
//	RETURN duration({days: 7}) AS d
func (q *queries) OneWeek(ctx context.Context) (Duration, error) {
	records, err := q.db.run(ctx, oneWeekQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return Duration{}, err
	}
	if len(records) == 0 {
		return Duration{}, ErrNoRows
	}
	if len(records) > 1 {
		return Duration{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.Duration](records[0], "d")
	if err != nil {
		return Duration{}, fmt.Errorf("OneWeek: decode column %q: %w", "d", err)
	}
	if isNil {
		return Duration{}, fmt.Errorf("OneWeek: column %q is non-nullable but arrived null", "d")
	}
	return toDuration(value), nil
}
