// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumnlocaltime

import "context"

type ReadQuerier interface {
	NowLocalTime(ctx context.Context) (LocalTime, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
