// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionwriteprojection

import "context"

type ReadQuerier interface {
}

type WriteQuerier interface {
	MergeAction(ctx context.Context, arg MergeActionParams) (MergeActionR, error)
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
