// Code generated by gqlc dev. DO NOT EDIT.

package multisourcefiles

import (
	"context"
	"fmt"
)

const allPersonIdsQueryText = `MATCH (p:Person) RETURN p.id`

// AllPersonIds executes the AllPersonIds query.
//
//	MATCH (p:Person) RETURN p.id
func (q *Queries) AllPersonIds(ctx context.Context) ([]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", allPersonIdsQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("AllPersonIds: %w", err)
	}
	defer rows.Close()
	out := make([]int64, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("AllPersonIds: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("AllPersonIds: column %q is non-nullable but arrived null", "p.id")
		}
		value0, err := agtypeInt64(raw0)
		if err != nil {
			return nil, fmt.Errorf("AllPersonIds: decode column %q: %w", "p.id", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("AllPersonIds: %w", err)
	}
	return out, nil
}
