// Code generated by gqlc dev. DO NOT EDIT.

package listexpressionunknownelement

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Account corresponds to the Account node type.
type Account struct {
	Dates  *[]Date
	Either *any
	Id     int64
	N      *int32
}

// decodeAccount decodes a driver dbtype.Node into a Account struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeAccount(node dbtype.Node) (Account, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Account" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Account{}, fmt.Errorf("decode Account: expected a node labelled %q, got labels %q", "Account", node.Labels)
	}
	var out Account
	if v, ok := node.Props["dates"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Account{}, fmt.Errorf("decode Account.Dates: property %q: expected []any, got %T", "dates", v)
		}
		narrowed := make([]Date, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(dbtype.Date)
			if !ok {
				return Account{}, fmt.Errorf("decode Account.Dates: property %q element %d: expected dbtype.Date, got %T", "dates", i0, elem0)
			}
			narrowed = append(narrowed, toDate(v0))
		}
		out.Dates = &narrowed
	}
	if v, ok := node.Props["either"]; ok && v != nil {
		u1, err := decodeUnion0aa394d5(v)
		if err != nil {
			return Account{}, fmt.Errorf("decode Account.Either: property %q: %w", "either", err)
		}
		out.Either = &u1
	}
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Id: %w", err)
	}
	out.Id = value0
	if v, ok := node.Props["n"]; ok {
		s, ok := v.(int64)
		if !ok {
			return Account{}, fmt.Errorf("decode Account.N: property %q: expected int64, got %T", "n", v)
		}
		narrowed, err := narrowInt[int32](s)
		if err != nil {
			return Account{}, fmt.Errorf("decode Account.N: %w", err)
		}
		out.N = &narrowed
	}
	return out, nil
}

// narrowInt converts a driver's int64 down to the integer width the
// schema declared, refusing a value that width cannot represent.
//
// The round-trip catches every width whose range is a strict subset of
// int64's. uint64 is the one where it does not: the conversion is a
// bijection there, so uint64(-1) round-trips back to -1 unchanged and
// only the sign disagreement gives it away. A uint64 property's readable
// range is [0, MaxInt64] — the wire integer is signed 64-bit — so a
// negative carrier is always a violation rather than a large value.
func narrowInt[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](v int64) (T, error) {
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}
