// Code generated by gqlc dev. DO NOT EDIT.

package listexpressionunknownelement

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const accountUnknownElementsQueryText = `MATCH (a:Account) RETURN [a.dates[0]] AS dated, [a.either, null] AS mixed, [a.n, null] AS mixed_scalar ORDER BY a.id`

type AccountUnknownElementsRow struct {
	Dated       []any
	Mixed       []any
	MixedScalar []any
}

// AccountUnknownElements executes the AccountUnknownElements query.
//
//	MATCH (a:Account) RETURN [a.dates[0]] AS dated, [a.either, null] AS mixed, [a.n, null] AS mixed_scalar ORDER BY a.id
func (q *queries) AccountUnknownElements(ctx context.Context) ([]AccountUnknownElementsRow, error) {
	records, err := q.db.run(ctx, accountUnknownElementsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]AccountUnknownElementsRow, 0, len(records))
	for _, record := range records {
		var row AccountUnknownElementsRow
		value0, isNil, err := neo4j.GetRecordValue[[]any](record, "dated")
		if err != nil {
			return nil, fmt.Errorf("AccountUnknownElements: decode column %q: %w", "dated", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountUnknownElements: column %q is non-nullable but arrived null", "dated")
		}
		acc0 := make([]any, 0, len(value0))
		for _, elem := range value0 {
			acc0 = append(acc0, elem)
		}
		row.Dated = acc0
		value1, isNil, err := neo4j.GetRecordValue[[]any](record, "mixed")
		if err != nil {
			return nil, fmt.Errorf("AccountUnknownElements: decode column %q: %w", "mixed", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountUnknownElements: column %q is non-nullable but arrived null", "mixed")
		}
		acc1 := make([]any, 0, len(value1))
		for _, elem := range value1 {
			acc1 = append(acc1, elem)
		}
		row.Mixed = acc1
		value2, isNil, err := neo4j.GetRecordValue[[]any](record, "mixed_scalar")
		if err != nil {
			return nil, fmt.Errorf("AccountUnknownElements: decode column %q: %w", "mixed_scalar", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountUnknownElements: column %q is non-nullable but arrived null", "mixed_scalar")
		}
		acc2 := make([]any, 0, len(value2))
		for _, elem := range value2 {
			acc2 = append(acc2, elem)
		}
		row.MixedScalar = acc2
		out = append(out, row)
	}
	return out, nil
}

const accountBareUnknownQueryText = `MATCH (a:Account) RETURN a.dates[0] AS dated ORDER BY a.id`

// AccountBareUnknown executes the AccountBareUnknown query.
//
//	MATCH (a:Account) RETURN a.dates[0] AS dated ORDER BY a.id
func (q *queries) AccountBareUnknown(ctx context.Context) ([]*any, error) {
	records, err := q.db.run(ctx, accountBareUnknownQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]*any, 0, len(records))
	for _, record := range records {
		value, ok := record.Get("dated")
		if !ok {
			return nil, fmt.Errorf("AccountBareUnknown: decode column %q: key not found", "dated")
		}
		var valuePtr *any
		if value != nil {
			valuePtr = &value
		}
		out = append(out, valuePtr)
	}
	return out, nil
}
