// Code generated by gqlc dev. DO NOT EDIT.

package listexpressionunknownelement

import "context"

type ReadQuerier interface {
	AccountUnknownElements(ctx context.Context) ([]AccountUnknownElementsRow, error)
	AccountBareUnknown(ctx context.Context) ([]any, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
