// Code generated by gqlc dev. DO NOT EDIT.

package recordanyandempty

import (
	"context"
	"fmt"
)

const blobWholeQueryText = `MATCH (b:Blob) RETURN b`

// BlobWhole executes the BlobWhole query.
//
//	MATCH (b:Blob) RETURN b
func (q *queries) BlobWhole(ctx context.Context) (Blob, error) {
	stmt, err := q.cypherStmt("$gqlc$", blobWholeQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Blob{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return Blob{}, fmt.Errorf("BlobWhole: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Blob{}, fmt.Errorf("BlobWhole: %w", err)
		}
		return Blob{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Blob{}, fmt.Errorf("BlobWhole: scan row: %w", err)
	}
	if rows.Next() {
		return Blob{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Blob{}, fmt.Errorf("BlobWhole: %w", err)
	}
	if raw0 == nil {
		return Blob{}, fmt.Errorf("BlobWhole: column %q is non-nullable but arrived null", "b")
	}
	value0, err := decodeBlob(raw0)
	if err != nil {
		return Blob{}, fmt.Errorf("BlobWhole: decode column %q: %w", "b", err)
	}
	return value0, nil
}

const blobColumnsQueryText = `MATCH (b:Blob) RETURN b.loose AS loose, b.maybe AS maybe, b.blank AS blank`

type BlobColumnsRow struct {
	Loose map[string]any
	Maybe *map[string]any
	Blank struct{}
}

// BlobColumns executes the BlobColumns query.
//
//	MATCH (b:Blob) RETURN b.loose AS loose, b.maybe AS maybe, b.blank AS blank
func (q *queries) BlobColumns(ctx context.Context) ([]BlobColumnsRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", blobColumnsQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype, v2 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("BlobColumns: %w", err)
	}
	defer rows.Close()
	out := make([]BlobColumnsRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		var raw2 []byte
		if err := rows.Scan(&raw0, &raw1, &raw2); err != nil {
			return nil, fmt.Errorf("BlobColumns: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("BlobColumns: column %q is non-nullable but arrived null", "loose")
		}
		value0, err := agtypeMap(raw0)
		if err != nil {
			return nil, fmt.Errorf("BlobColumns: decode column %q: %w", "loose", err)
		}
		var value1 *map[string]any
		if raw1 != nil {
			decoded, err := agtypeMap(raw1)
			if err != nil {
				return nil, fmt.Errorf("BlobColumns: decode column %q: %w", "maybe", err)
			}
			value1 = &decoded
		}
		if raw2 == nil {
			return nil, fmt.Errorf("BlobColumns: column %q is non-nullable but arrived null", "blank")
		}
		value2, err := decodeRecordd25fb0e0(raw2)
		if err != nil {
			return nil, fmt.Errorf("BlobColumns: decode column %q: %w", "blank", err)
		}
		out = append(out, BlobColumnsRow{
			Loose: value0,
			Maybe: value1,
			Blank: value2,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("BlobColumns: %w", err)
	}
	return out, nil
}
