// Code generated by gqlc dev. DO NOT EDIT.

package uniononlycarrierentitydecodeonly

import (
	"context"
	"fmt"
)

const accountWholeQueryText = `MATCH (a:Account) WHERE a.id = $id RETURN a`

// AccountWhole executes the AccountWhole query.
//
//	MATCH (a:Account) WHERE a.id = $id RETURN a
func (q *queries) AccountWhole(ctx context.Context, arg int64) (Account, error) {
	stmt, err := q.cypherStmt("$gqlc$", accountWholeQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Account{}, err
	}
	args, err := agtypeArgs(map[string]any{"id": arg})
	if err != nil {
		return Account{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Account{}, fmt.Errorf("AccountWhole: %w", err)
		}
		return Account{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Account{}, fmt.Errorf("AccountWhole: scan row: %w", err)
	}
	if rows.Next() {
		return Account{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Account{}, fmt.Errorf("AccountWhole: %w", err)
	}
	if raw0 == nil {
		return Account{}, fmt.Errorf("AccountWhole: column %q is non-nullable but arrived null", "a")
	}
	value0, err := decodeAccount(raw0)
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	return value0, nil
}
