// Code generated by gqlc dev. DO NOT EDIT.

package scalarmap

import "context"

type ReadQuerier interface {
	OneMap(ctx context.Context) (map[string]any, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
