// Code generated by gqlc dev. DO NOT EDIT.

package writeoneprojectionentity

import "context"

type ReadQuerier interface {
}

type WriteQuerier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
