// Code generated by gqlc dev. DO NOT EDIT.

package listexpressionrecordfieldelement

import (
	"context"
	"fmt"
)

const accountRecordFieldElementsQueryText = `MATCH (a:Account) RETURN [a.ul.u] AS u, [a.ul.n] AS n ORDER BY a.id`

type AccountRecordFieldElementsRow struct {
	U []any
	N []any
}

// AccountRecordFieldElements executes the AccountRecordFieldElements query.
//
//	MATCH (a:Account) RETURN [a.ul.u] AS u, [a.ul.n] AS n ORDER BY a.id
func (q *queries) AccountRecordFieldElements(ctx context.Context) ([]AccountRecordFieldElementsRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", accountRecordFieldElementsQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("AccountRecordFieldElements: %w", err)
	}
	defer rows.Close()
	out := make([]AccountRecordFieldElementsRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		if err := rows.Scan(&raw0, &raw1); err != nil {
			return nil, fmt.Errorf("AccountRecordFieldElements: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("AccountRecordFieldElements: column %q is non-nullable but arrived null", "u")
		}
		value0, err := agtypeListOfAny(raw0)
		if err != nil {
			return nil, fmt.Errorf("AccountRecordFieldElements: decode column %q: %w", "u", err)
		}
		if raw1 == nil {
			return nil, fmt.Errorf("AccountRecordFieldElements: column %q is non-nullable but arrived null", "n")
		}
		value1, err := agtypeListOfAny(raw1)
		if err != nil {
			return nil, fmt.Errorf("AccountRecordFieldElements: decode column %q: %w", "n", err)
		}
		out = append(out, AccountRecordFieldElementsRow{
			U: value0,
			N: value1,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("AccountRecordFieldElements: %w", err)
	}
	return out, nil
}

const accountBareRecordFieldQueryText = `MATCH (a:Account) RETURN a.ul.u AS u ORDER BY a.id`

// AccountBareRecordField executes the AccountBareRecordField query.
//
//	MATCH (a:Account) RETURN a.ul.u AS u ORDER BY a.id
func (q *queries) AccountBareRecordField(ctx context.Context) ([]any, error) {
	stmt, err := q.cypherStmt("$gqlc$", accountBareRecordFieldQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("AccountBareRecordField: %w", err)
	}
	defer rows.Close()
	out := make([]any, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("AccountBareRecordField: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("AccountBareRecordField: column %q is non-nullable but arrived null", "u")
		}
		value0, err := agtypeValue(raw0)
		if err != nil {
			return nil, fmt.Errorf("AccountBareRecordField: decode column %q: %w", "u", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("AccountBareRecordField: %w", err)
	}
	return out, nil
}
