#!/usr/bin/env python3
"""Derive the graph-type-DDL production closure from ISO/IEC 39075's BNF artefact.

Emits productions.go on stdout. See SOURCE.md for the artefact URL, its SHA-256
and how to re-run this.

Only production *names* are emitted. The BNF bodies stay in the downloaded
artefact and are never vendored, for the same licence reason annexd/ vendors
bare feature codes and not ISO's prose.
"""
import hashlib
import re
import sys
from collections import OrderedDict, deque

# The graph-type DDL entry points. <graph type specification> does not exist as
# a production in the artefact despite being the natural name for the concept;
# the three below are the actual spellings, and they are minimal — each of
# <graph type source>, <graph type reference> and <catalog graph type parent and
# name> is reachable from them, so naming those as roots too changes nothing.
ROOTS = [
    "create graph type statement",
    "drop graph type statement",
    "nested graph type specification",
]

# <graph expression> is the frontier of this closure, not part of it. It enters
# through exactly one production, <graph type like graph> (the LIKE form of a
# graph type source), and descending into it drags the entire query language in:
# the closure goes from 200 productions to 738. Query-side coverage is the
# vendored openCypher TCK's job.
CUTS = {"graph expression"}

HEADER_RE = re.compile(r"^<([^>]+)>\s*::=")
REF_RE = re.compile(r"<([^>]+)>")


def parse_productions(path):
    productions = OrderedDict()
    name, body = None, []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            match = HEADER_RE.match(line)
            if match:
                if name:
                    productions[name] = "".join(body)
                name, body = match.group(1), []
            elif name is not None:
                body.append(line)
    if name:
        productions[name] = "".join(body)
    return productions


def closure(productions):
    seen, queue = OrderedDict(), deque()
    for root in ROOTS:
        if root not in productions:
            sys.exit(f"root <{root}> is not a production in the artefact")
        seen[root] = True
        queue.append(root)
    reached_cuts = set()
    while queue:
        current = queue.popleft()
        if current in CUTS:
            reached_cuts.add(current)
            continue
        for ref in sorted(set(REF_RE.findall(productions[current]))):
            if ref == current or ref not in productions:
                continue
            if ref not in seen:
                seen[ref] = True
                queue.append(ref)
    unreached = CUTS - reached_cuts
    if unreached:
        sys.exit(f"cut(s) {sorted(unreached)} never reached; delete them")
    return seen


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <path-to-ISO_IEC_39075(en).bnf.txt>")
    path = sys.argv[1]
    digest = hashlib.sha256(open(path, "rb").read()).hexdigest()

    productions = parse_productions(path)
    ddl = sorted(closure(productions))

    out = sys.stdout.write
    out('// Code generated by extract_ddl_closure.py; DO NOT EDIT.\n\n')
    out(GODOC)
    out("package isobnf\n\n")
    out(f"// SourceSHA256 is the digest of the BNF artefact these names were derived\n")
    out(f"// from. SOURCE.md records the URL and fetch date.\n")
    out(f'const SourceSHA256 = "{digest}"\n\n')
    out(f"// TotalProductions is how many productions the whole artefact defines, of\n")
    out(f"// which DDLClosure is the graph-type-DDL reachable subset.\n")
    out(f"const TotalProductions = {len(productions)}\n\n")
    out("// DDLClosure is every ISO/IEC 39075 production reachable from the graph-type\n")
    out("// DDL entry points, sorted. This is the denominator: a production absent from\n")
    out("// our grammar entirely is still in this list, which is the whole point.\n")
    out("var DDLClosure = []string{\n")
    for name in ddl:
        out(f'\t"{name}",\n')
    out("}\n")


GODOC = '''// Package isobnf vendors the names of the ISO/IEC 39075 BNF productions that
// are reachable from the graph-type DDL entry points.
//
// It exists to be a denominator. A coverage gate built on internal/grammar/gql
// can only report alternatives we implemented and did not exercise; it cannot
// report a production that is in the standard and absent from our grammar,
// because such a production is not in its denominator. This list is, so it can.
//
// Only bare production names are vendored, never the BNF bodies — the same
// licence line annexd draws around ISO's prose.
'''

if __name__ == "__main__":
    main()
