// Code generated by gqlc dev. DO NOT EDIT.

package zonedtimeroundtrip

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const addSlotQueryText = `CREATE (s:Slot {id: $id, startsAt: $startsAt})`

type AddSlotParams struct {
	Id       int64
	StartsAt Time
}

// AddSlot executes the AddSlot query.
//
//	CREATE (s:Slot {id: $id, startsAt: $startsAt})
func (q *queries) AddSlot(ctx context.Context, arg AddSlotParams) error {
	_, err := q.db.run(ctx, addSlotQueryText, map[string]any{"id": arg.Id, "startsAt": fromTime(arg.StartsAt)}, neo4j.AccessModeWrite)
	return err
}

const slotsFromQueryText = `MATCH (s:Slot) WHERE s.startsAt >= $from RETURN s.id AS id ORDER BY s.startsAt`

// SlotsFrom executes the SlotsFrom query.
//
//	MATCH (s:Slot) WHERE s.startsAt >= $from RETURN s.id AS id ORDER BY s.startsAt
func (q *queries) SlotsFrom(ctx context.Context, arg Time) ([]int64, error) {
	records, err := q.db.run(ctx, slotsFromQueryText, map[string]any{"from": fromTime(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("SlotsFrom: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("SlotsFrom: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const slotStartQueryText = `MATCH (s:Slot) WHERE s.id = $id RETURN s.startsAt AS startsAt`

// SlotStart executes the SlotStart query.
//
//	MATCH (s:Slot) WHERE s.id = $id RETURN s.startsAt AS startsAt
func (q *queries) SlotStart(ctx context.Context, arg int64) (Time, error) {
	records, err := q.db.run(ctx, slotStartQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Time{}, err
	}
	if len(records) == 0 {
		return Time{}, ErrNoRows
	}
	if len(records) > 1 {
		return Time{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.Time](records[0], "startsAt")
	if err != nil {
		return Time{}, fmt.Errorf("SlotStart: decode column %q: %w", "startsAt", err)
	}
	if isNil {
		return Time{}, fmt.Errorf("SlotStart: column %q is non-nullable but arrived null", "startsAt")
	}
	return toTime(value), nil
}

const oneSlotQueryText = `MATCH (s:Slot) WHERE s.id = $id RETURN s`

// OneSlot executes the OneSlot query.
//
//	MATCH (s:Slot) WHERE s.id = $id RETURN s
func (q *queries) OneSlot(ctx context.Context, arg int64) (Slot, error) {
	records, err := q.db.run(ctx, oneSlotQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Slot{}, err
	}
	if len(records) == 0 {
		return Slot{}, ErrNoRows
	}
	if len(records) > 1 {
		return Slot{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "s")
	if err != nil {
		return Slot{}, fmt.Errorf("OneSlot: decode column %q: %w", "s", err)
	}
	if isNil {
		return Slot{}, fmt.Errorf("OneSlot: column %q is non-nullable but arrived null", "s")
	}
	value, err := decodeSlot(node)
	if err != nil {
		return Slot{}, fmt.Errorf("OneSlot: decode column %q: %w", "s", err)
	}
	return value, nil
}
