// Code generated by gqlc dev. DO NOT EDIT.

package uint64parameter

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Counter corresponds to the Counter node type.
type Counter struct {
	Hits   uint64
	Id     int64
	Misses *uint64
	Runs   []uint64
	Spans  *[]uint64
}

// decodeCounter decodes a driver dbtype.Node into a Counter struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeCounter(node dbtype.Node) (Counter, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Counter" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Counter{}, fmt.Errorf("decode Counter: expected a node labelled %q, got labels %q", "Counter", node.Labels)
	}
	var out Counter
	value0, err := neo4j.GetProperty[int64](node, "hits")
	if err != nil {
		return Counter{}, fmt.Errorf("decode Counter.Hits: %w", err)
	}
	value0n, err := narrowInt[uint64](value0)
	if err != nil {
		return Counter{}, fmt.Errorf("decode Counter.Hits: %w", err)
	}
	out.Hits = value0n
	value1, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Counter{}, fmt.Errorf("decode Counter.Id: %w", err)
	}
	out.Id = value1
	if v, ok := node.Props["misses"]; ok {
		s, ok := v.(int64)
		if !ok {
			return Counter{}, fmt.Errorf("decode Counter.Misses: property %q: expected int64, got %T", "misses", v)
		}
		narrowed, err := narrowInt[uint64](s)
		if err != nil {
			return Counter{}, fmt.Errorf("decode Counter.Misses: %w", err)
		}
		out.Misses = &narrowed
	}
	value3, err := neo4j.GetProperty[[]any](node, "runs")
	if err != nil {
		return Counter{}, fmt.Errorf("decode Counter.Runs: %w", err)
	}
	value3s := make([]uint64, 0, len(value3))
	for i0, elem0 := range value3 {
		v0, ok := elem0.(int64)
		if !ok {
			return Counter{}, fmt.Errorf("decode Counter.Runs: property %q element %d: expected int64, got %T", "runs", i0, elem0)
		}
		v0n, err := narrowInt[uint64](v0)
		if err != nil {
			return Counter{}, fmt.Errorf("decode Counter.Runs: property %q element %d: %w", "runs", i0, err)
		}
		value3s = append(value3s, v0n)
	}
	out.Runs = value3s
	if v, ok := node.Props["spans"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Counter{}, fmt.Errorf("decode Counter.Spans: property %q: expected []any, got %T", "spans", v)
		}
		narrowed := make([]uint64, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(int64)
			if !ok {
				return Counter{}, fmt.Errorf("decode Counter.Spans: property %q element %d: expected int64, got %T", "spans", i0, elem0)
			}
			v0n, err := narrowInt[uint64](v0)
			if err != nil {
				return Counter{}, fmt.Errorf("decode Counter.Spans: property %q element %d: %w", "spans", i0, err)
			}
			narrowed = append(narrowed, v0n)
		}
		out.Spans = &narrowed
	}
	return out, nil
}

// narrowInt converts a driver's int64 down to the integer width the
// schema declared, refusing a value that width cannot represent.
//
// The round-trip catches every width whose range is a strict subset of
// int64's. uint64 is the one where it does not: the conversion is a
// bijection there, so uint64(-1) round-trips back to -1 unchanged and
// only the sign disagreement gives it away. A uint64 property's readable
// range is [0, MaxInt64] — the wire integer is signed 64-bit — so a
// negative carrier is always a violation rather than a large value.
func narrowInt[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](v int64) (T, error) {
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}
