// Code generated by gqlc dev. DO NOT EDIT.

package propertydate

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Person corresponds to the Person node type.
type Person struct {
	Dob Date
	Id  int64
}

// decodePerson decodes an agtype vertex into a Person struct, enforcing
// the label and the per-property nullability the schema declares.
func decodePerson(raw []byte) (Person, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person: %w", err)
	}
	if label != "Person" {
		return Person{}, fmt.Errorf("decode Person: expected label %q, got %q", "Person", label)
	}
	var out Person
	value0, err := agtypeProperty(props, "dob", agtypeDate)
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Dob: %w", err)
	}
	out.Dob = value0
	value1, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = value1
	return out, nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDate decodes a stored DATE. agtype has no temporal value, so
// gqlc stores one as the string scalar in zero-padded ISO YYYY-MM-DD:
// the one temporal spelling whose lexical order is its chronological
// order, so an author's ORDER BY n.dob is answered by the database's own
// string comparison with nothing for gqlc to rewrite.
//
// That ordering holds across [0001-01-01, 9999-12-31] and nowhere else,
// which is why the padding and the bound are read back here rather than
// assumed. A year needing a fifth digit sorts under every four-digit year
// because '1' < '2', and a proleptic year before 1 CE needs a sign, which
// sorts under every digit and files the whole era at the front,
// ascending. gqlc's own encode produces neither — it refuses them — but
// it writes to an ordinary agtype string property on a vertex any writer
// can touch, so what is read back is whatever the graph holds.
//
// The padding is enforced by the layout and not by a check beside it.
// time.Parse reads each field at a fixed width, so '2024-1-2' fails at
// the month, '24-01-02' at the year, and a signed or five-digit year at
// the first byte that is not a digit where one belongs — every spelling
// that would sort in the wrong place is refused before a Date is built.
//
// That leaves the range bounded at one end only, which is measured
// rather than an oversight. A year over 9999 needs a fifth digit and a
// year before 1 CE needs a sign, and the layout refuses both; year 0 is
// the one out-of-range year spelled with four unsigned digits, so it is
// the only one that reaches here, and it is what this bound is for.
func agtypeDate(raw []byte) (Date, error) {
	text, err := agtypeString(raw)
	if err != nil {
		return Date{}, err
	}
	at, err := time.Parse(agtypeDateLayout, text)
	if err != nil {
		return Date{}, fmt.Errorf("gqlc: %q is not a date in zero-padded ISO YYYY-MM-DD form: %w", text, err)
	}
	if at.Year() < 1 {
		return Date{}, fmt.Errorf("gqlc: %q is outside the year 1 to year 9999 range this encoding admits", text)
	}
	return Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}, nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}
