// Code generated by gqlc dev. DO NOT EDIT.

package onecoloneparamone

import "context"

type ReadQuerier interface {
	PersonName(ctx context.Context, arg int64) (string, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
