// Code generated by gqlc dev. DO NOT EDIT.

package schemalistanyproperty

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Bin corresponds to the Bin node type.
type Bin struct {
	Bag   *[]any
	Id    int64
	Loose []any
}

// decodeBin decodes a driver dbtype.Node into a Bin struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeBin(node dbtype.Node) (Bin, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Bin" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Bin{}, fmt.Errorf("decode Bin: expected a node labelled %q, got labels %q", "Bin", node.Labels)
	}
	var out Bin
	if v, ok := node.Props["bag"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Bin{}, fmt.Errorf("decode Bin.Bag: property %q: expected []any, got %T", "bag", v)
		}
		out.Bag = &s
	}
	value1, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Bin{}, fmt.Errorf("decode Bin.Id: %w", err)
	}
	out.Id = value1
	value2, err := neo4j.GetProperty[[]any](node, "loose")
	if err != nil {
		return Bin{}, fmt.Errorf("decode Bin.Loose: %w", err)
	}
	out.Loose = value2
	return out, nil
}
