// Code generated by gqlc dev. DO NOT EDIT.

package schemalistanyproperty

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const binsQueryText = `MATCH (b:Bin) RETURN b`

// Bins executes the Bins query.
//
//	MATCH (b:Bin) RETURN b
func (q *Queries) Bins(ctx context.Context) ([]Bin, error) {
	records, err := q.db.run(ctx, binsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]Bin, 0, len(records))
	for _, record := range records {
		node, isNil, err := neo4j.GetRecordValue[dbtype.Node](record, "b")
		if err != nil {
			return nil, fmt.Errorf("Bins: decode column %q: %w", "b", err)
		}
		if isNil {
			return nil, fmt.Errorf("Bins: column %q is non-nullable but arrived null", "b")
		}
		value, err := decodeBin(node)
		if err != nil {
			return nil, fmt.Errorf("Bins: decode column %q: %w", "b", err)
		}
		out = append(out, value)
	}
	return out, nil
}

const binByIdQueryText = `MATCH (b:Bin {id: $id}) RETURN b`

// BinById executes the BinById query.
//
//	MATCH (b:Bin {id: $id}) RETURN b
func (q *Queries) BinById(ctx context.Context, id int64) (Bin, error) {
	records, err := q.db.run(ctx, binByIdQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return Bin{}, err
	}
	if len(records) == 0 {
		return Bin{}, ErrNoRows
	}
	if len(records) > 1 {
		return Bin{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "b")
	if err != nil {
		return Bin{}, fmt.Errorf("BinById: decode column %q: %w", "b", err)
	}
	if isNil {
		return Bin{}, fmt.Errorf("BinById: column %q is non-nullable but arrived null", "b")
	}
	value, err := decodeBin(node)
	if err != nil {
		return Bin{}, fmt.Errorf("BinById: decode column %q: %w", "b", err)
	}
	return value, nil
}
