// Code generated by gqlc dev. DO NOT EDIT.

package aliasbarevariableambiguity

import (
	"context"
	"fmt"
)

const peopleBareQueryText = `MATCH (p:Person) RETURN p.name, p.age`

type PeopleBareRow struct {
	Name string
	Age  int64
}

// PeopleBare executes the PeopleBare query.
//
//	MATCH (p:Person) RETURN p.name, p.age
func (q *queries) PeopleBare(ctx context.Context) ([]PeopleBareRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", peopleBareQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PeopleBare: %w", err)
	}
	defer rows.Close()
	out := make([]PeopleBareRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		if err := rows.Scan(&raw0, &raw1); err != nil {
			return nil, fmt.Errorf("PeopleBare: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PeopleBare: column %q is non-nullable but arrived null", "p.name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PeopleBare: decode column %q: %w", "p.name", err)
		}
		if raw1 == nil {
			return nil, fmt.Errorf("PeopleBare: column %q is non-nullable but arrived null", "p.age")
		}
		value1, err := agtypeInt64(raw1)
		if err != nil {
			return nil, fmt.Errorf("PeopleBare: decode column %q: %w", "p.age", err)
		}
		out = append(out, PeopleBareRow{
			Name: value0,
			Age:  value1,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PeopleBare: %w", err)
	}
	return out, nil
}

const peopleAliasedQueryText = `MATCH (p:Person) RETURN p.name AS name, p.age`

type PeopleAliasedRow struct {
	Name string
	Age  int64
}

// PeopleAliased executes the PeopleAliased query.
//
//	MATCH (p:Person) RETURN p.name AS name, p.age
func (q *queries) PeopleAliased(ctx context.Context) ([]PeopleAliasedRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", peopleAliasedQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PeopleAliased: %w", err)
	}
	defer rows.Close()
	out := make([]PeopleAliasedRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		if err := rows.Scan(&raw0, &raw1); err != nil {
			return nil, fmt.Errorf("PeopleAliased: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PeopleAliased: column %q is non-nullable but arrived null", "name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("PeopleAliased: decode column %q: %w", "name", err)
		}
		if raw1 == nil {
			return nil, fmt.Errorf("PeopleAliased: column %q is non-nullable but arrived null", "p.age")
		}
		value1, err := agtypeInt64(raw1)
		if err != nil {
			return nil, fmt.Errorf("PeopleAliased: decode column %q: %w", "p.age", err)
		}
		out = append(out, PeopleAliasedRow{
			Name: value0,
			Age:  value1,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PeopleAliased: %w", err)
	}
	return out, nil
}
