// Code generated by gqlc dev. DO NOT EDIT.

package edgeuniontwoedgeunioncolumns

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const pairActionsQueryText = `MATCH (:Person)-[r1:AUTHORED|LIKES]->(:Post), (:Person)-[r2:AUTHORED|LIKES]->(:Post) RETURN r1, r2`

type PairActionsRow struct {
	R1 PairActionsR1
	R2 PairActionsR2
}

// PairActions executes the PairActions query.
//
//	MATCH (:Person)-[r1:AUTHORED|LIKES]->(:Post), (:Person)-[r2:AUTHORED|LIKES]->(:Post) RETURN r1, r2
func (q *Queries) PairActions(ctx context.Context) (PairActionsRow, error) {
	records, err := q.db.run(ctx, pairActionsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return PairActionsRow{}, err
	}
	if len(records) == 0 {
		return PairActionsRow{}, ErrNoRows
	}
	if len(records) > 1 {
		return PairActionsRow{}, ErrMultipleResults
	}
	var row PairActionsRow
	raw0, ok0 := records[0].Get("r1")
	if !ok0 {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q missing from record", "r1")
	}
	if raw0 == nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q is non-nullable but arrived null", "r1")
	}
	rel0, ok0 := raw0.(dbtype.Relationship)
	if !ok0 {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: expected dbtype.Relationship, got %T", "r1", raw0)
	}
	switch rel0.Type {
	case "AUTHORED":
		entity0, err := decodeAUTHORED(rel0)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r1", err)
		}
		row.R1 = entity0
	case "LIKES":
		entity0, err := decodeLIKES(rel0)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r1", err)
		}
		row.R1 = entity0
	default:
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: unexpected relationship type %q", "r1", rel0.Type)
	}
	raw1, ok1 := records[0].Get("r2")
	if !ok1 {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q missing from record", "r2")
	}
	if raw1 == nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q is non-nullable but arrived null", "r2")
	}
	rel1, ok1 := raw1.(dbtype.Relationship)
	if !ok1 {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: expected dbtype.Relationship, got %T", "r2", raw1)
	}
	switch rel1.Type {
	case "AUTHORED":
		entity1, err := decodeAUTHORED(rel1)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r2", err)
		}
		row.R2 = entity1
	case "LIKES":
		entity1, err := decodeLIKES(rel1)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r2", err)
		}
		row.R2 = entity1
	default:
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: unexpected relationship type %q", "r2", rel1.Type)
	}
	return row, nil
}
