// Code generated by gqlc dev. DO NOT EDIT.

package queriesignored

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

type Queries struct {
	db driverOrTx
}

func New(driver neo4j.DriverWithContext) *Queries {
	return &Queries{db: driverDB{driver: driver}}
}

func (q *Queries) WithTx(tx neo4j.ManagedTransaction) *Queries {
	return &Queries{db: txDB{tx: tx}}
}

// driverOrTx is the unexported run indirection: every generated query
// body routes through it, dispatching between the per-call-session
// path (New) and the caller-owned managed-transaction path (WithTx).
type driverOrTx interface {
	run(ctx context.Context, cypher string, params map[string]any, access neo4j.AccessMode) (neo4j.ResultWithContext, error)
}

type driverDB struct {
	driver neo4j.DriverWithContext
}

func (d driverDB) run(ctx context.Context, cypher string, params map[string]any, access neo4j.AccessMode) (neo4j.ResultWithContext, error) {
	session := d.driver.NewSession(ctx, neo4j.SessionConfig{AccessMode: access})
	defer session.Close(ctx)
	// C0: the driverDB.run body dispatches ExecuteRead / ExecuteWrite
	// by AccessMode. C1 populates the read arm; C4 populates the
	// write arm.
	_ = session
	return nil, nil
}

type txDB struct {
	tx neo4j.ManagedTransaction
}

func (t txDB) run(ctx context.Context, cypher string, params map[string]any, _ neo4j.AccessMode) (neo4j.ResultWithContext, error) {
	return t.tx.Run(ctx, cypher, params)
}
