// Code generated by gqlc dev. DO NOT EDIT.

package uuidproperty

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Account corresponds to the Account node type.
type Account struct {
	Chain  *[]UUID
	Either *any
	Id     int64
	Prior  *UUID
	Ref    UUID
	Span   Duration
	Trail  *[]*UUID
}

// decodeAccount decodes a driver dbtype.Node into a Account struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeAccount(node dbtype.Node) (Account, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Account" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Account{}, fmt.Errorf("decode Account: expected a node labelled %q, got labels %q", "Account", node.Labels)
	}
	var out Account
	if v, ok := node.Props["chain"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Account{}, fmt.Errorf("decode Account.Chain: property %q: expected []any, got %T", "chain", v)
		}
		narrowed := make([]UUID, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Account{}, fmt.Errorf("decode Account.Chain: property %q element %d: expected string, got %T", "chain", i0, elem0)
			}
			v0n, err := toUUID(v0)
			if err != nil {
				return Account{}, fmt.Errorf("decode Account.Chain: property %q element %d: %w", "chain", i0, err)
			}
			narrowed = append(narrowed, v0n)
		}
		out.Chain = &narrowed
	}
	if v, ok := node.Props["either"]; ok && v != nil {
		u1, err := decodeUnion26f53c9e(v)
		if err != nil {
			return Account{}, fmt.Errorf("decode Account.Either: property %q: %w", "either", err)
		}
		out.Either = &u1
	}
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Id: %w", err)
	}
	out.Id = value0
	if v, ok := node.Props["prior"]; ok {
		s, ok := v.(string)
		if !ok {
			return Account{}, fmt.Errorf("decode Account.Prior: property %q: expected string, got %T", "prior", v)
		}
		narrowed, err := toUUID(s)
		if err != nil {
			return Account{}, fmt.Errorf("decode Account.Prior: %w", err)
		}
		out.Prior = &narrowed
	}
	value1, err := neo4j.GetProperty[string](node, "ref")
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Ref: %w", err)
	}
	value1n, err := toUUID(value1)
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Ref: %w", err)
	}
	out.Ref = value1n
	value2, err := neo4j.GetProperty[dbtype.Duration](node, "span")
	if err != nil {
		return Account{}, fmt.Errorf("decode Account.Span: %w", err)
	}
	out.Span = toDuration(value2)
	if v, ok := node.Props["trail"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Account{}, fmt.Errorf("decode Account.Trail: property %q: expected []any, got %T", "trail", v)
		}
		narrowed := make([]*UUID, 0, len(s))
		for i0, elem0 := range s {
			if elem0 == nil {
				narrowed = append(narrowed, nil)
				continue
			}
			v0, ok := elem0.(string)
			if !ok {
				return Account{}, fmt.Errorf("decode Account.Trail: property %q element %d: expected string, got %T", "trail", i0, elem0)
			}
			v0n, err := toUUID(v0)
			if err != nil {
				return Account{}, fmt.Errorf("decode Account.Trail: property %q element %d: %w", "trail", i0, err)
			}
			narrowed = append(narrowed, &v0n)
		}
		out.Trail = &narrowed
	}
	return out, nil
}
