// Code generated by gqlc dev. DO NOT EDIT.

package uuidproperty

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const accountWholeQueryText = `MATCH (a:Account) WHERE a.id = $id RETURN a`

// AccountWhole executes the AccountWhole query.
//
//	MATCH (a:Account) WHERE a.id = $id RETURN a
func (q *queries) AccountWhole(ctx context.Context, arg int64) (Account, error) {
	records, err := q.db.run(ctx, accountWholeQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Account{}, err
	}
	if len(records) == 0 {
		return Account{}, ErrNoRows
	}
	if len(records) > 1 {
		return Account{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "a")
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	if isNil {
		return Account{}, fmt.Errorf("AccountWhole: column %q is non-nullable but arrived null", "a")
	}
	value, err := decodeAccount(node)
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	return value, nil
}

const accountColumnsQueryText = `MATCH (a:Account) RETURN a.ref AS ref, a.prior AS prior, a.trail AS trail, a.chain AS chain, a.either AS either, a.span AS span`

type AccountColumnsRow struct {
	Ref    UUID
	Prior  *UUID
	Trail  *[]*UUID
	Chain  *[]UUID
	Either *any
	Span   Duration
}

// AccountColumns executes the AccountColumns query.
//
//	MATCH (a:Account) RETURN a.ref AS ref, a.prior AS prior, a.trail AS trail, a.chain AS chain, a.either AS either, a.span AS span
func (q *queries) AccountColumns(ctx context.Context) ([]AccountColumnsRow, error) {
	records, err := q.db.run(ctx, accountColumnsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]AccountColumnsRow, 0, len(records))
	for _, record := range records {
		var row AccountColumnsRow
		value0, isNil, err := neo4j.GetRecordValue[string](record, "ref")
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "ref", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountColumns: column %q is non-nullable but arrived null", "ref")
		}
		value0n, err := toUUID(value0)
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "ref", err)
		}
		row.Ref = value0n
		value1, isNil, err := neo4j.GetRecordValue[string](record, "prior")
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "prior", err)
		}
		var value1Ptr *UUID
		if !isNil {
			v, err := toUUID(value1)
			if err != nil {
				return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "prior", err)
			}
			value1Ptr = &v
		}
		row.Prior = value1Ptr
		value2, isNil, err := neo4j.GetRecordValue[[]any](record, "trail")
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "trail", err)
		}
		var value2Ptr *[]*UUID
		if !isNil {
			acc2 := make([]*UUID, 0, len(value2))
			for i, elem := range value2 {
				if elem == nil {
					acc2 = append(acc2, nil)
					continue
				}
				v, ok := elem.(string)
				if !ok {
					return nil, fmt.Errorf("AccountColumns: decode column %q element %d: expected string, got %T", "trail", i, elem)
				}
				vn, err := toUUID(v)
				if err != nil {
					return nil, fmt.Errorf("AccountColumns: decode column %q element %d: %w", "trail", i, err)
				}
				acc2 = append(acc2, &vn)
			}
			value2Ptr = &acc2
		}
		row.Trail = value2Ptr
		value3, isNil, err := neo4j.GetRecordValue[[]any](record, "chain")
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "chain", err)
		}
		var value3Ptr *[]UUID
		if !isNil {
			acc3 := make([]UUID, 0, len(value3))
			for i, elem := range value3 {
				v, ok := elem.(string)
				if !ok {
					return nil, fmt.Errorf("AccountColumns: decode column %q element %d: expected string, got %T", "chain", i, elem)
				}
				vn, err := toUUID(v)
				if err != nil {
					return nil, fmt.Errorf("AccountColumns: decode column %q element %d: %w", "chain", i, err)
				}
				acc3 = append(acc3, vn)
			}
			value3Ptr = &acc3
		}
		row.Chain = value3Ptr
		value4, ok := record.Get("either")
		if !ok {
			return nil, fmt.Errorf("AccountColumns: decode column %q: key not found", "either")
		}
		var value4Ptr *any
		if value4 != nil {
			v, err := decodeUnion26f53c9e(value4)
			if err != nil {
				return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "either", err)
			}
			value4Ptr = &v
		}
		row.Either = value4Ptr
		value5, isNil, err := neo4j.GetRecordValue[dbtype.Duration](record, "span")
		if err != nil {
			return nil, fmt.Errorf("AccountColumns: decode column %q: %w", "span", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountColumns: column %q is non-nullable but arrived null", "span")
		}
		row.Span = toDuration(value5)
		out = append(out, row)
	}
	return out, nil
}

const accountRefQueryText = `MATCH (a:Account) WHERE a.id = $id RETURN a.ref AS ref`

// AccountRef executes the AccountRef query.
//
//	MATCH (a:Account) WHERE a.id = $id RETURN a.ref AS ref
func (q *queries) AccountRef(ctx context.Context, arg int64) (UUID, error) {
	records, err := q.db.run(ctx, accountRefQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return UUID{}, err
	}
	if len(records) == 0 {
		return UUID{}, ErrNoRows
	}
	if len(records) > 1 {
		return UUID{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "ref")
	if err != nil {
		return UUID{}, fmt.Errorf("AccountRef: decode column %q: %w", "ref", err)
	}
	if isNil {
		return UUID{}, fmt.Errorf("AccountRef: column %q is non-nullable but arrived null", "ref")
	}
	valuen, err := toUUID(value)
	if err != nil {
		return UUID{}, fmt.Errorf("AccountRef: decode column %q: %w", "ref", err)
	}
	return valuen, nil
}

const accountByRefQueryText = `MATCH (a:Account) WHERE a.ref = $ref RETURN a.id AS id`

// AccountByRef executes the AccountByRef query.
//
//	MATCH (a:Account) WHERE a.ref = $ref RETURN a.id AS id
func (q *queries) AccountByRef(ctx context.Context, arg UUID) ([]int64, error) {
	records, err := q.db.run(ctx, accountByRefQueryText, map[string]any{"ref": fromUUID(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("AccountByRef: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountByRef: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const accountByPriorQueryText = `MATCH (a:Account) WHERE a.prior = $prior RETURN a.id AS id`

// AccountByPrior executes the AccountByPrior query.
//
//	MATCH (a:Account) WHERE a.prior = $prior RETURN a.id AS id
func (q *queries) AccountByPrior(ctx context.Context, arg *UUID) ([]int64, error) {
	records, err := q.db.run(ctx, accountByPriorQueryText, map[string]any{"prior": fromUUIDPtr(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("AccountByPrior: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountByPrior: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const accountByTrailQueryText = `MATCH (a:Account) WHERE a.trail = $trail RETURN a.id AS id`

// AccountByTrail executes the AccountByTrail query.
//
//	MATCH (a:Account) WHERE a.trail = $trail RETURN a.id AS id
func (q *queries) AccountByTrail(ctx context.Context, arg *[]*UUID) ([]int64, error) {
	records, err := q.db.run(ctx, accountByTrailQueryText, map[string]any{"trail": fromNullableUUIDListPtr(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("AccountByTrail: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountByTrail: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const accountByChainQueryText = `MATCH (a:Account) WHERE a.chain = $chain RETURN a.id AS id`

// AccountByChain executes the AccountByChain query.
//
//	MATCH (a:Account) WHERE a.chain = $chain RETURN a.id AS id
func (q *queries) AccountByChain(ctx context.Context, arg *[]UUID) ([]int64, error) {
	records, err := q.db.run(ctx, accountByChainQueryText, map[string]any{"chain": fromUUIDListPtr(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("AccountByChain: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountByChain: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const openAccountQueryText = `CREATE (a:Account {id: $id, ref: $ref, prior: $prior, trail: $trail, chain: $chain, either: $either, span: $span})`

type OpenAccountParams struct {
	Id     int64
	Ref    UUID
	Prior  *UUID
	Trail  *[]*UUID
	Chain  *[]UUID
	Either *any
	Span   Duration
}

// OpenAccount executes the OpenAccount query.
//
//	CREATE (a:Account {id: $id, ref: $ref, prior: $prior, trail: $trail, chain: $chain, either: $either, span: $span})
func (q *queries) OpenAccount(ctx context.Context, arg OpenAccountParams) error {
	param5, err := encodeUnion26f53c9ePtr(arg.Either)
	if err != nil {
		return err
	}
	_, err = q.db.run(ctx, openAccountQueryText, map[string]any{"id": arg.Id, "ref": fromUUID(arg.Ref), "prior": fromUUIDPtr(arg.Prior), "trail": fromNullableUUIDListPtr(arg.Trail), "chain": fromUUIDListPtr(arg.Chain), "either": param5, "span": fromDuration(arg.Span)}, neo4j.AccessModeWrite)
	return err
}
