// Code generated by gqlc dev. DO NOT EDIT.

package nestedlistproperty

import "context"

type ReadQuerier interface {
	GridWhole(ctx context.Context) (Grid, error)
	GridColumns(ctx context.Context) ([]GridColumnsRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
