// Code generated by gqlc dev. DO NOT EDIT.

package nestedlistproperty

import (
	"context"
	"fmt"
)

const gridWholeQueryText = `MATCH (g:Grid) RETURN g`

// GridWhole executes the GridWhole query.
//
//	MATCH (g:Grid) RETURN g
func (q *queries) GridWhole(ctx context.Context) (Grid, error) {
	stmt, err := q.cypherStmt("$gqlc$", gridWholeQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Grid{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return Grid{}, fmt.Errorf("GridWhole: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Grid{}, fmt.Errorf("GridWhole: %w", err)
		}
		return Grid{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Grid{}, fmt.Errorf("GridWhole: scan row: %w", err)
	}
	if rows.Next() {
		return Grid{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Grid{}, fmt.Errorf("GridWhole: %w", err)
	}
	if raw0 == nil {
		return Grid{}, fmt.Errorf("GridWhole: column %q is non-nullable but arrived null", "g")
	}
	value0, err := decodeGrid(raw0)
	if err != nil {
		return Grid{}, fmt.Errorf("GridWhole: decode column %q: %w", "g", err)
	}
	return value0, nil
}

const gridColumnsQueryText = `MATCH (g:Grid) RETURN g.matrix AS matrix, g.grid AS grid, g.piles AS piles`

type GridColumnsRow struct {
	Matrix *[][]float32
	Grid   *[][]int16
	Piles  *[][]any
}

// GridColumns executes the GridColumns query.
//
//	MATCH (g:Grid) RETURN g.matrix AS matrix, g.grid AS grid, g.piles AS piles
func (q *queries) GridColumns(ctx context.Context) ([]GridColumnsRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", gridColumnsQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype, v2 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("GridColumns: %w", err)
	}
	defer rows.Close()
	out := make([]GridColumnsRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		var raw2 []byte
		if err := rows.Scan(&raw0, &raw1, &raw2); err != nil {
			return nil, fmt.Errorf("GridColumns: scan row: %w", err)
		}
		var value0 *[][]float32
		if raw0 != nil {
			decoded, err := agtypeListOfListOfFloat32(raw0)
			if err != nil {
				return nil, fmt.Errorf("GridColumns: decode column %q: %w", "matrix", err)
			}
			value0 = &decoded
		}
		var value1 *[][]int16
		if raw1 != nil {
			decoded, err := agtypeListOfListOfInt16(raw1)
			if err != nil {
				return nil, fmt.Errorf("GridColumns: decode column %q: %w", "grid", err)
			}
			value1 = &decoded
		}
		var value2 *[][]any
		if raw2 != nil {
			decoded, err := agtypeListOfListOfAny(raw2)
			if err != nil {
				return nil, fmt.Errorf("GridColumns: decode column %q: %w", "piles", err)
			}
			value2 = &decoded
		}
		out = append(out, GridColumnsRow{
			Matrix: value0,
			Grid:   value1,
			Piles:  value2,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("GridColumns: %w", err)
	}
	return out, nil
}
