// Code generated by gqlc dev. DO NOT EDIT.

package uniononlyuuidcarrierdecodeonly

import "context"

type ReadQuerier interface {
	AccountWhole(ctx context.Context, arg int64) (Account, error)
	AccountEithers(ctx context.Context) ([][]any, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
