// Code generated by gqlc dev. DO NOT EDIT.

package nestedlistelementprojection

import "context"

type ReadQuerier interface {
	TagsPair(ctx context.Context) ([][]*[]*string, error)
	RanksPair(ctx context.Context) ([][]*[]int16, error)
	LabelsPair(ctx context.Context) ([][][]*string, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
