// Code generated by gqlc dev. DO NOT EDIT.

package propertyduration

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Span corresponds to the Span node type.
type Span struct {
	Elapsed Duration
	Id      int64
}

// decodeSpan decodes an agtype vertex into a Span struct, enforcing
// the label and the per-property nullability the schema declares.
func decodeSpan(raw []byte) (Span, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Span{}, fmt.Errorf("decode Span: %w", err)
	}
	if label != "Span" {
		return Span{}, fmt.Errorf("decode Span: expected label %q, got %q", "Span", label)
	}
	var out Span
	value0, err := agtypeProperty(props, "elapsed", agtypeDuration)
	if err != nil {
		return Span{}, fmt.Errorf("decode Span.Elapsed: %w", err)
	}
	out.Elapsed = value0
	value1, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Span{}, fmt.Errorf("decode Span.Id: %w", err)
	}
	out.Id = value1
	return out, nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeDuration decodes a stored DURATION: the integer scalar, counting
// total microseconds. Signed, so a negative count is a duration
// backwards and orders below every positive one.
//
// What comes back is normalised, and cannot be otherwise: the stored
// count is one number, so the Months and Days a Duration can hold have
// nothing to be filled from and stay zero. A value written as 90 days
// reads back as 7776000 seconds. Months is zero rather than derived
// because no fixed count of microseconds is faithful to a month — which
// is the same reason the encode direction refuses a Duration carrying
// one instead of storing an approximation of it.
//
// The division floors rather than truncating, so Nanos is never
// negative and a duration backwards borrows from Seconds: -1500000
// microseconds is Seconds -2 and Nanos 500000000, not Seconds -1 and
// Nanos -500000000. Go's / and % truncate toward zero and would
// produce the second, which no neo4j value ever takes — the driver
// renders a Duration by borrowing from a negative Seconds against a
// positive Nanos, so a negative Nanos is a shape its own String method
// has no reading for. The two are the same amount of time either way;
// what floor division buys is that the components a caller reads off
// this carrier do not change meaning when the target does.
func agtypeDuration(raw []byte) (Duration, error) {
	micros, err := agtypeInt64(raw)
	if err != nil {
		return Duration{}, err
	}
	seconds := micros / 1000000
	rem := micros % 1000000
	if rem < 0 {
		seconds--
		rem += 1000000
	}
	return Duration{Seconds: seconds, Nanos: int(rem * 1000)}, nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}
