// Code generated by gqlc dev. DO NOT EDIT.

package schemalistpropertywidths

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Reading corresponds to the Reading node type.
type Reading struct {
	Codes  []int32
	Flags  *[]bool
	Grid   *[][]int16
	Id     int64
	Marks  *[]string
	Matrix *[][]float32
	Ranks  *[]int32
	Tags   *[]string
}

// decodeReading decodes a driver dbtype.Node into a Reading struct,
// enforcing per-property nullability against the schema.
func decodeReading(node dbtype.Node) (Reading, error) {
	var out Reading
	value0, err := neo4j.GetProperty[[]any](node, "codes")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.Codes: %w", err)
	}
	value0s := make([]int32, 0, len(value0))
	for i0, elem0 := range value0 {
		v0, ok := elem0.(int64)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Codes: property %q element %d: expected int64, got %T", "codes", i0, elem0)
		}
		value0s = append(value0s, int32(v0))
	}
	out.Codes = value0s
	if v, ok := node.Props["flags"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Flags: property %q: expected []any, got %T", "flags", v)
		}
		narrowed := make([]bool, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(bool)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Flags: property %q element %d: expected bool, got %T", "flags", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Flags = &narrowed
	}
	if v, ok := node.Props["grid"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Grid: property %q: expected []any, got %T", "grid", v)
		}
		narrowed := make([][]int16, 0, len(s))
		for i0, elem0 := range s {
			nested0, ok := elem0.([]any)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Grid: property %q element %d: expected []any, got %T", "grid", i0, elem0)
			}
			acc0 := make([]int16, 0, len(nested0))
			for i1, elem1 := range nested0 {
				v1, ok := elem1.(int64)
				if !ok {
					return Reading{}, fmt.Errorf("decode Reading.Grid: property %q element %d: expected int64, got %T", "grid", i1, elem1)
				}
				acc0 = append(acc0, int16(v1))
			}
			narrowed = append(narrowed, acc0)
		}
		out.Grid = &narrowed
	}
	value3, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.Id: %w", err)
	}
	out.Id = value3
	if v, ok := node.Props["marks"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Marks: property %q: expected []any, got %T", "marks", v)
		}
		narrowed := make([]string, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Marks: property %q element %d: expected string, got %T", "marks", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Marks = &narrowed
	}
	if v, ok := node.Props["matrix"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Matrix: property %q: expected []any, got %T", "matrix", v)
		}
		narrowed := make([][]float32, 0, len(s))
		for i0, elem0 := range s {
			nested0, ok := elem0.([]any)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Matrix: property %q element %d: expected []any, got %T", "matrix", i0, elem0)
			}
			acc0 := make([]float32, 0, len(nested0))
			for i1, elem1 := range nested0 {
				v1, ok := elem1.(float64)
				if !ok {
					return Reading{}, fmt.Errorf("decode Reading.Matrix: property %q element %d: expected float64, got %T", "matrix", i1, elem1)
				}
				acc0 = append(acc0, float32(v1))
			}
			narrowed = append(narrowed, acc0)
		}
		out.Matrix = &narrowed
	}
	if v, ok := node.Props["ranks"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Ranks: property %q: expected []any, got %T", "ranks", v)
		}
		narrowed := make([]int32, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(int64)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Ranks: property %q element %d: expected int64, got %T", "ranks", i0, elem0)
			}
			narrowed = append(narrowed, int32(v0))
		}
		out.Ranks = &narrowed
	}
	if v, ok := node.Props["tags"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Tags: property %q: expected []any, got %T", "tags", v)
		}
		narrowed := make([]string, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Tags: property %q element %d: expected string, got %T", "tags", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Tags = &narrowed
	}
	return out, nil
}
