// Code generated by gqlc dev. DO NOT EDIT.

package schemalistpropertywidths

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Reading corresponds to the Reading node type.
type Reading struct {
	Codes []int32
	Flags *[]bool
	Id    int64
	Marks *[]string
	Ranks *[]int32
	Tags  *[]string
}

// decodeReading decodes a driver dbtype.Node into a Reading struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeReading(node dbtype.Node) (Reading, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Reading" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Reading{}, fmt.Errorf("decode Reading: expected a node labelled %q, got labels %q", "Reading", node.Labels)
	}
	var out Reading
	value0, err := neo4j.GetProperty[[]any](node, "codes")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.Codes: %w", err)
	}
	value0s := make([]int32, 0, len(value0))
	for i0, elem0 := range value0 {
		v0, ok := elem0.(int64)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Codes: property %q element %d: expected int64, got %T", "codes", i0, elem0)
		}
		value0s = append(value0s, int32(v0))
	}
	out.Codes = value0s
	if v, ok := node.Props["flags"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Flags: property %q: expected []any, got %T", "flags", v)
		}
		narrowed := make([]bool, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(bool)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Flags: property %q element %d: expected bool, got %T", "flags", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Flags = &narrowed
	}
	value2, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.Id: %w", err)
	}
	out.Id = value2
	if v, ok := node.Props["marks"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Marks: property %q: expected []any, got %T", "marks", v)
		}
		narrowed := make([]string, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Marks: property %q element %d: expected string, got %T", "marks", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Marks = &narrowed
	}
	if v, ok := node.Props["ranks"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Ranks: property %q: expected []any, got %T", "ranks", v)
		}
		narrowed := make([]int32, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(int64)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Ranks: property %q element %d: expected int64, got %T", "ranks", i0, elem0)
			}
			narrowed = append(narrowed, int32(v0))
		}
		out.Ranks = &narrowed
	}
	if v, ok := node.Props["tags"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Reading{}, fmt.Errorf("decode Reading.Tags: property %q: expected []any, got %T", "tags", v)
		}
		narrowed := make([]string, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Reading{}, fmt.Errorf("decode Reading.Tags: property %q element %d: expected string, got %T", "tags", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Tags = &narrowed
	}
	return out, nil
}
