// Code generated by gqlc dev. DO NOT EDIT.

package entityexplicitname

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const oneActorQueryText = `MATCH (p:Person) RETURN p`

// OneActor executes the OneActor query.
//
//	MATCH (p:Person) RETURN p
func (q *Queries) OneActor(ctx context.Context) (Actor, error) {
	records, err := q.db.run(ctx, oneActorQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return Actor{}, err
	}
	if len(records) == 0 {
		return Actor{}, ErrNoRows
	}
	if len(records) > 1 {
		return Actor{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "p")
	if err != nil {
		return Actor{}, fmt.Errorf("OneActor: decode column %q: %w", "p", err)
	}
	if isNil {
		return Actor{}, fmt.Errorf("OneActor: column %q is non-nullable but arrived null", "p")
	}
	value, err := decodeActor(node)
	if err != nil {
		return Actor{}, fmt.Errorf("OneActor: decode column %q: %w", "p", err)
	}
	return value, nil
}
