// Code generated by gqlc dev. DO NOT EDIT.

package entitynodeandscalarrow

import (
	"context"
	"fmt"
)

const onePersonWithAgeQueryText = `MATCH (p:Person) RETURN p, p.age AS age`

type OnePersonWithAgeRow struct {
	P   Person
	Age int64
}

// OnePersonWithAge executes the OnePersonWithAge query.
//
//	MATCH (p:Person) RETURN p, p.age AS age
func (q *Queries) OnePersonWithAge(ctx context.Context) (OnePersonWithAgeRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", onePersonWithAgeQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype")
	if err != nil {
		return OnePersonWithAgeRow{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: %w", err)
		}
		return OnePersonWithAgeRow{}, ErrNoRows
	}
	var raw0 []byte
	var raw1 []byte
	if err := rows.Scan(&raw0, &raw1); err != nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: scan row: %w", err)
	}
	if rows.Next() {
		return OnePersonWithAgeRow{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: %w", err)
	}
	if raw0 == nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: column %q is non-nullable but arrived null", "p")
	}
	value0, err := decodePerson(raw0)
	if err != nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: decode column %q: %w", "p", err)
	}
	if raw1 == nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: column %q is non-nullable but arrived null", "age")
	}
	value1, err := agtypeInt64(raw1)
	if err != nil {
		return OnePersonWithAgeRow{}, fmt.Errorf("OnePersonWithAge: decode column %q: %w", "age", err)
	}
	return OnePersonWithAgeRow{
		P:   value0,
		Age: value1,
	}, nil
}
