// Code generated by gqlc dev. DO NOT EDIT.

package timestampprojection

import (
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Reading corresponds to the Reading node type.
type Reading struct {
	Id      int64
	TakenAt time.Time
}

// decodeReading decodes a driver dbtype.Node into a Reading struct,
// enforcing per-property nullability against the schema.
func decodeReading(node dbtype.Node) (Reading, error) {
	var out Reading
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.Id: %w", err)
	}
	out.Id = value0
	value1, err := neo4j.GetProperty[time.Time](node, "takenAt")
	if err != nil {
		return Reading{}, fmt.Errorf("decode Reading.TakenAt: %w", err)
	}
	out.TakenAt = value1
	return out, nil
}
