// Code generated by gqlc dev. DO NOT EDIT.

package timestampprojection

import (
	"context"
	"time"
)

type ReadQuerier interface {
	ReadingAt(ctx context.Context, arg int64) (time.Time, error)
	OneReading(ctx context.Context, arg int64) (Reading, error)
	AllReadings(ctx context.Context) ([]time.Time, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
