// Code generated by gqlc dev. DO NOT EDIT.

package twononnulllistcolumns

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// Listy corresponds to the Listy node type.
type Listy struct {
	Ranks []int32
	Spare *[]string
	Tags  []string
}

// decodeListy decodes a driver dbtype.Node into a Listy struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeListy(node dbtype.Node) (Listy, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Listy" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Listy{}, fmt.Errorf("decode Listy: expected a node labelled %q, got labels %q", "Listy", node.Labels)
	}
	var out Listy
	value0, err := neo4j.GetProperty[[]any](node, "ranks")
	if err != nil {
		return Listy{}, fmt.Errorf("decode Listy.Ranks: %w", err)
	}
	value0s := make([]int32, 0, len(value0))
	for i0, elem0 := range value0 {
		v0, ok := elem0.(int64)
		if !ok {
			return Listy{}, fmt.Errorf("decode Listy.Ranks: property %q element %d: expected int64, got %T", "ranks", i0, elem0)
		}
		v0n, err := narrowInt[int32](v0)
		if err != nil {
			return Listy{}, fmt.Errorf("decode Listy.Ranks: property %q element %d: %w", "ranks", i0, err)
		}
		value0s = append(value0s, v0n)
	}
	out.Ranks = value0s
	if v, ok := node.Props["spare"]; ok {
		s, ok := v.([]any)
		if !ok {
			return Listy{}, fmt.Errorf("decode Listy.Spare: property %q: expected []any, got %T", "spare", v)
		}
		narrowed := make([]string, 0, len(s))
		for i0, elem0 := range s {
			v0, ok := elem0.(string)
			if !ok {
				return Listy{}, fmt.Errorf("decode Listy.Spare: property %q element %d: expected string, got %T", "spare", i0, elem0)
			}
			narrowed = append(narrowed, v0)
		}
		out.Spare = &narrowed
	}
	value2, err := neo4j.GetProperty[[]any](node, "tags")
	if err != nil {
		return Listy{}, fmt.Errorf("decode Listy.Tags: %w", err)
	}
	value2s := make([]string, 0, len(value2))
	for i0, elem0 := range value2 {
		v0, ok := elem0.(string)
		if !ok {
			return Listy{}, fmt.Errorf("decode Listy.Tags: property %q element %d: expected string, got %T", "tags", i0, elem0)
		}
		value2s = append(value2s, v0)
	}
	out.Tags = value2s
	return out, nil
}

// narrowInt converts a driver's int64 down to the integer width the
// schema declared, refusing a value that width cannot represent.
//
// The round-trip catches every width whose range is a strict subset of
// int64's. uint64 is the one where it does not: the conversion is a
// bijection there, so uint64(-1) round-trips back to -1 unchanged and
// only the sign disagreement gives it away. A uint64 property's readable
// range is [0, MaxInt64] — the wire integer is signed 64-bit — so a
// negative carrier is always a violation rather than a large value.
func narrowInt[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](v int64) (T, error) {
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}
