// Code generated by gqlc dev. DO NOT EDIT.

package onecolmany

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Name string
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing per-property nullability against the schema.
func decodePerson(node dbtype.Node) (Person, error) {
	var out Person
	name, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Name: %w", err)
	}
	out.Name = name
	return out, nil
}
