// Code generated by gqlc dev. DO NOT EDIT.

package propertytime

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Event corresponds to the Event node type.
type Event struct {
	Happened dbtype.Time
	Id       int64
}

// decodeEvent decodes a driver dbtype.Node into a Event struct,
// enforcing per-property nullability against the schema.
func decodeEvent(node dbtype.Node) (Event, error) {
	var out Event
	value0, err := neo4j.GetProperty[dbtype.Time](node, "happened")
	if err != nil {
		return Event{}, fmt.Errorf("decode Event.Happened: %w", err)
	}
	out.Happened = value0
	value1, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Event{}, fmt.Errorf("decode Event.Id: %w", err)
	}
	out.Id = value1
	return out, nil
}
