// Code generated by gqlc dev. DO NOT EDIT.

package timestamppropertyroundtrip

import (
	"context"
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const addEventQueryText = `CREATE (e:Event {id: $id, occurredAt: $occurredAt})`

type AddEventParams struct {
	Id         int64
	OccurredAt time.Time
}

// AddEvent executes the AddEvent query.
//
//	CREATE (e:Event {id: $id, occurredAt: $occurredAt})
func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) error {
	_, err := q.db.run(ctx, addEventQueryText, map[string]any{"id": arg.Id, "occurredAt": arg.OccurredAt}, neo4j.AccessModeWrite)
	return err
}

const eventsAfterQueryText = `MATCH (e:Event) WHERE e.occurredAt > $since RETURN e.id AS id ORDER BY e.occurredAt`

// EventsAfter executes the EventsAfter query.
//
//	MATCH (e:Event) WHERE e.occurredAt > $since RETURN e.id AS id ORDER BY e.occurredAt
func (q *Queries) EventsAfter(ctx context.Context, since time.Time) ([]int64, error) {
	records, err := q.db.run(ctx, eventsAfterQueryText, map[string]any{"since": since}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("EventsAfter: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("EventsAfter: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const eventsSeenAfterQueryText = `MATCH (e:Event) WHERE e.seenAt > $seenAfter RETURN e.id AS id ORDER BY e.seenAt`

// EventsSeenAfter executes the EventsSeenAfter query.
//
//	MATCH (e:Event) WHERE e.seenAt > $seenAfter RETURN e.id AS id ORDER BY e.seenAt
func (q *Queries) EventsSeenAfter(ctx context.Context, seenAfter *time.Time) ([]int64, error) {
	records, err := q.db.run(ctx, eventsSeenAfterQueryText, map[string]any{"seenAfter": seenAfter}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("EventsSeenAfter: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("EventsSeenAfter: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const eventAtQueryText = `MATCH (e:Event) WHERE e.id = $id RETURN e.occurredAt AS occurredAt`

// EventAt executes the EventAt query.
//
//	MATCH (e:Event) WHERE e.id = $id RETURN e.occurredAt AS occurredAt
func (q *Queries) EventAt(ctx context.Context, id int64) (time.Time, error) {
	records, err := q.db.run(ctx, eventAtQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return time.Time{}, err
	}
	if len(records) == 0 {
		return time.Time{}, ErrNoRows
	}
	if len(records) > 1 {
		return time.Time{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[time.Time](records[0], "occurredAt")
	if err != nil {
		return time.Time{}, fmt.Errorf("EventAt: decode column %q: %w", "occurredAt", err)
	}
	if isNil {
		return time.Time{}, fmt.Errorf("EventAt: column %q is non-nullable but arrived null", "occurredAt")
	}
	return value, nil
}

const eventSeenAtQueryText = `MATCH (e:Event) WHERE e.id = $id RETURN e.seenAt AS seenAt`

// EventSeenAt executes the EventSeenAt query.
//
//	MATCH (e:Event) WHERE e.id = $id RETURN e.seenAt AS seenAt
func (q *Queries) EventSeenAt(ctx context.Context, id int64) (*time.Time, error) {
	records, err := q.db.run(ctx, eventSeenAtQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[time.Time](records[0], "seenAt")
	if err != nil {
		return nil, fmt.Errorf("EventSeenAt: decode column %q: %w", "seenAt", err)
	}
	var valuePtr *time.Time
	if !isNil {
		v := value
		valuePtr = &v
	}
	return valuePtr, nil
}

const oneEventQueryText = `MATCH (e:Event) WHERE e.id = $id RETURN e`

// OneEvent executes the OneEvent query.
//
//	MATCH (e:Event) WHERE e.id = $id RETURN e
func (q *Queries) OneEvent(ctx context.Context, id int64) (Event, error) {
	records, err := q.db.run(ctx, oneEventQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return Event{}, err
	}
	if len(records) == 0 {
		return Event{}, ErrNoRows
	}
	if len(records) > 1 {
		return Event{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "e")
	if err != nil {
		return Event{}, fmt.Errorf("OneEvent: decode column %q: %w", "e", err)
	}
	if isNil {
		return Event{}, fmt.Errorf("OneEvent: column %q is non-nullable but arrived null", "e")
	}
	value, err := decodeEvent(node)
	if err != nil {
		return Event{}, fmt.Errorf("OneEvent: decode column %q: %w", "e", err)
	}
	return value, nil
}
