// Code generated by gqlc dev. DO NOT EDIT.

package queryparamshadowsemittedname

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const personByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt RETURN p.name`

// PersonByStmt executes the PersonByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt RETURN p.name
func (q *Queries) PersonByStmt(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByStmtQueryText, map[string]any{"stmt": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByStmt: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByStmt: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const personByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args RETURN p.name`

// PersonByArgs executes the PersonByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args RETURN p.name
func (q *Queries) PersonByArgs(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, personByArgsQueryText, map[string]any{"args": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("PersonByArgs: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("PersonByArgs: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const personByRowsQueryText = `MATCH (p:Person) WHERE p.name = $rows RETURN p.name`

// PersonByRows executes the PersonByRows query.
//
//	MATCH (p:Person) WHERE p.name = $rows RETURN p.name
func (q *Queries) PersonByRows(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, personByRowsQueryText, map[string]any{"rows": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("PersonByRows: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("PersonByRows: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const personByRaw0QueryText = `MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name`

// PersonByRaw0 executes the PersonByRaw0 query.
//
//	MATCH (p:Person) WHERE p.name = $raw0 RETURN p.name
func (q *Queries) PersonByRaw0(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByRaw0QueryText, map[string]any{"raw0": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByRaw0: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByRaw0: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const personByValue0QueryText = `MATCH (p:Person) WHERE p.name = $value0 RETURN p.name`

// PersonByValue0 executes the PersonByValue0 query.
//
//	MATCH (p:Person) WHERE p.name = $value0 RETURN p.name
func (q *Queries) PersonByValue0(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, personByValue0QueryText, map[string]any{"value0": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("PersonByValue0: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("PersonByValue0: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const deleteByStmtQueryText = `MATCH (p:Person) WHERE p.name = $stmt DELETE p`

// DeleteByStmt executes the DeleteByStmt query.
//
//	MATCH (p:Person) WHERE p.name = $stmt DELETE p
func (q *Queries) DeleteByStmt(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, deleteByStmtQueryText, map[string]any{"stmt": arg}, neo4j.AccessModeWrite)
	return err
}

const deleteByArgsQueryText = `MATCH (p:Person) WHERE p.name = $args DELETE p`

// DeleteByArgs executes the DeleteByArgs query.
//
//	MATCH (p:Person) WHERE p.name = $args DELETE p
func (q *Queries) DeleteByArgs(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, deleteByArgsQueryText, map[string]any{"args": arg}, neo4j.AccessModeWrite)
	return err
}

const constShadowOneQueryText = `MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name`

// ConstShadowOne executes the ConstShadowOne query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowOneQueryText RETURN p.name
func (q *Queries) ConstShadowOne(ctx context.Context, arg string) (string, error) {
	records, err := q.db.run(ctx, constShadowOneQueryText, map[string]any{"constShadowOneQueryText": arg}, neo4j.AccessModeRead)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", ErrNoRows
	}
	if len(records) > 1 {
		return "", ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[string](records[0], "p.name")
	if err != nil {
		return "", fmt.Errorf("ConstShadowOne: decode column %q: %w", "p.name", err)
	}
	if isNil {
		return "", fmt.Errorf("ConstShadowOne: column %q is non-nullable but arrived null", "p.name")
	}
	return value, nil
}

const constShadowManyQueryText = `MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name`

// ConstShadowMany executes the ConstShadowMany query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowManyQueryText RETURN p.name
func (q *Queries) ConstShadowMany(ctx context.Context, arg string) ([]string, error) {
	records, err := q.db.run(ctx, constShadowManyQueryText, map[string]any{"constShadowManyQueryText": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[string](record, "p.name")
		if err != nil {
			return nil, fmt.Errorf("ConstShadowMany: decode column %q: %w", "p.name", err)
		}
		if isNil {
			return nil, fmt.Errorf("ConstShadowMany: column %q is non-nullable but arrived null", "p.name")
		}
		out = append(out, value)
	}
	return out, nil
}

const constShadowExecQueryText = `MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p`

// ConstShadowExec executes the ConstShadowExec query.
//
//	MATCH (p:Person) WHERE p.name = $constShadowExecQueryText DELETE p
func (q *Queries) ConstShadowExec(ctx context.Context, arg string) error {
	_, err := q.db.run(ctx, constShadowExecQueryText, map[string]any{"constShadowExecQueryText": arg}, neo4j.AccessModeWrite)
	return err
}
