// Code generated by gqlc dev. DO NOT EDIT.

package writeexecnullableparam

import (
	"context"
	"fmt"
)

const removeByTagQueryText = `MATCH (p:Person {optionalTag: $tag}) DELETE p`

// RemoveByTag executes the RemoveByTag query.
//
//	MATCH (p:Person {optionalTag: $tag}) DELETE p
func (q *Queries) RemoveByTag(ctx context.Context, tag *string) error {
	stmt, err := q.cypherStmt("$gqlc$", removeByTagQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return err
	}
	args, err := agtypeArgs(map[string]any{"tag": tag})
	if err != nil {
		return err
	}
	if _, err := q.db.Exec(ctx, stmt, args); err != nil {
		return fmt.Errorf("RemoveByTag: %w", err)
	}
	return nil
}
