// Code generated by gqlc dev. DO NOT EDIT.

package writeexecnullableparam

import "context"

type ReadQuerier interface {
}

type WriteQuerier interface {
	RemoveByTag(ctx context.Context, tag *string) error
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
