// Code generated by gqlc dev. DO NOT EDIT.

package entityexplicitname

import (
	"context"
	"fmt"
)

const oneActorQueryText = `MATCH (p:Person) RETURN p`

// OneActor executes the OneActor query.
//
//	MATCH (p:Person) RETURN p
func (q *queries) OneActor(ctx context.Context) (Actor, error) {
	stmt, err := q.cypherStmt("$gqlc$", oneActorQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Actor{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return Actor{}, fmt.Errorf("OneActor: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Actor{}, fmt.Errorf("OneActor: %w", err)
		}
		return Actor{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Actor{}, fmt.Errorf("OneActor: scan row: %w", err)
	}
	if rows.Next() {
		return Actor{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Actor{}, fmt.Errorf("OneActor: %w", err)
	}
	if raw0 == nil {
		return Actor{}, fmt.Errorf("OneActor: column %q is non-nullable but arrived null", "p")
	}
	value0, err := decodeActor(raw0)
	if err != nil {
		return Actor{}, fmt.Errorf("OneActor: decode column %q: %w", "p", err)
	}
	return value0, nil
}
