// Code generated by gqlc dev. DO NOT EDIT.

package propertybytes

type ReadQuerier interface {
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
