// Code generated by gqlc dev. DO NOT EDIT.

package writeonlybatch

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const removePersonQueryText = `MATCH (p:Person) WHERE p.id = $id DELETE p`

// RemovePerson executes the RemovePerson query.
//
//	MATCH (p:Person) WHERE p.id = $id DELETE p
func (q *Queries) RemovePerson(ctx context.Context, id int64) error {
	_, err := q.db.run(ctx, removePersonQueryText, map[string]any{"id": id}, neo4j.AccessModeWrite)
	return err
}

const createPersonQueryText = `CREATE (p:Person {id: $id, name: $name})`

type CreatePersonParams struct {
	Id   int64
	Name string
}

// CreatePerson executes the CreatePerson query.
//
//	CREATE (p:Person {id: $id, name: $name})
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.run(ctx, createPersonQueryText, map[string]any{"id": arg.Id, "name": arg.Name}, neo4j.AccessModeWrite)
	return err
}
