// Code generated by gqlc dev. DO NOT EDIT.

package temporalpropertyroundtrip

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const addReadingQueryText = `CREATE (r:Reading {id: $id, onDate: $onDate, atLocal: $atLocal, elapsed: $elapsed})`

type AddReadingParams struct {
	Id      int64
	OnDate  Date
	AtLocal LocalTime
	Elapsed Duration
}

// AddReading executes the AddReading query.
//
//	CREATE (r:Reading {id: $id, onDate: $onDate, atLocal: $atLocal, elapsed: $elapsed})
func (q *queries) AddReading(ctx context.Context, arg AddReadingParams) error {
	_, err := q.db.run(ctx, addReadingQueryText, map[string]any{"id": arg.Id, "onDate": fromDate(arg.OnDate), "atLocal": fromLocalTime(arg.AtLocal), "elapsed": fromDuration(arg.Elapsed)}, neo4j.AccessModeWrite)
	return err
}

const readingsFromQueryText = `MATCH (r:Reading) WHERE r.onDate >= $from RETURN r.id AS id ORDER BY r.onDate`

// ReadingsFrom executes the ReadingsFrom query.
//
//	MATCH (r:Reading) WHERE r.onDate >= $from RETURN r.id AS id ORDER BY r.onDate
func (q *queries) ReadingsFrom(ctx context.Context, arg Date) ([]int64, error) {
	records, err := q.db.run(ctx, readingsFromQueryText, map[string]any{"from": fromDate(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("ReadingsFrom: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("ReadingsFrom: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const readingsSeenFromQueryText = `MATCH (r:Reading) WHERE r.seenOn >= $seenFrom RETURN r.id AS id ORDER BY r.seenOn`

// ReadingsSeenFrom executes the ReadingsSeenFrom query.
//
//	MATCH (r:Reading) WHERE r.seenOn >= $seenFrom RETURN r.id AS id ORDER BY r.seenOn
func (q *queries) ReadingsSeenFrom(ctx context.Context, arg *Date) ([]int64, error) {
	records, err := q.db.run(ctx, readingsSeenFromQueryText, map[string]any{"seenFrom": fromDatePtr(arg)}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("ReadingsSeenFrom: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("ReadingsSeenFrom: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}

const readingDateQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r.onDate AS onDate`

// ReadingDate executes the ReadingDate query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r.onDate AS onDate
func (q *queries) ReadingDate(ctx context.Context, arg int64) (Date, error) {
	records, err := q.db.run(ctx, readingDateQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Date{}, err
	}
	if len(records) == 0 {
		return Date{}, ErrNoRows
	}
	if len(records) > 1 {
		return Date{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.Date](records[0], "onDate")
	if err != nil {
		return Date{}, fmt.Errorf("ReadingDate: decode column %q: %w", "onDate", err)
	}
	if isNil {
		return Date{}, fmt.Errorf("ReadingDate: column %q is non-nullable but arrived null", "onDate")
	}
	return toDate(value), nil
}

const readingLocalTimeQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r.atLocal AS atLocal`

// ReadingLocalTime executes the ReadingLocalTime query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r.atLocal AS atLocal
func (q *queries) ReadingLocalTime(ctx context.Context, arg int64) (LocalTime, error) {
	records, err := q.db.run(ctx, readingLocalTimeQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return LocalTime{}, err
	}
	if len(records) == 0 {
		return LocalTime{}, ErrNoRows
	}
	if len(records) > 1 {
		return LocalTime{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.LocalTime](records[0], "atLocal")
	if err != nil {
		return LocalTime{}, fmt.Errorf("ReadingLocalTime: decode column %q: %w", "atLocal", err)
	}
	if isNil {
		return LocalTime{}, fmt.Errorf("ReadingLocalTime: column %q is non-nullable but arrived null", "atLocal")
	}
	return toLocalTime(value), nil
}

const readingElapsedQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r.elapsed AS elapsed`

// ReadingElapsed executes the ReadingElapsed query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r.elapsed AS elapsed
func (q *queries) ReadingElapsed(ctx context.Context, arg int64) (Duration, error) {
	records, err := q.db.run(ctx, readingElapsedQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Duration{}, err
	}
	if len(records) == 0 {
		return Duration{}, ErrNoRows
	}
	if len(records) > 1 {
		return Duration{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.Duration](records[0], "elapsed")
	if err != nil {
		return Duration{}, fmt.Errorf("ReadingElapsed: decode column %q: %w", "elapsed", err)
	}
	if isNil {
		return Duration{}, fmt.Errorf("ReadingElapsed: column %q is non-nullable but arrived null", "elapsed")
	}
	return toDuration(value), nil
}

const oneReadingQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r`

// OneReading executes the OneReading query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r
func (q *queries) OneReading(ctx context.Context, arg int64) (Reading, error) {
	records, err := q.db.run(ctx, oneReadingQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Reading{}, err
	}
	if len(records) == 0 {
		return Reading{}, ErrNoRows
	}
	if len(records) > 1 {
		return Reading{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "r")
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: decode column %q: %w", "r", err)
	}
	if isNil {
		return Reading{}, fmt.Errorf("OneReading: column %q is non-nullable but arrived null", "r")
	}
	value, err := decodeReading(node)
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: decode column %q: %w", "r", err)
	}
	return value, nil
}
