// Code generated by gqlc dev. DO NOT EDIT.

package writeoneprojectionentity

import (
	"context"
	"fmt"
)

const createPersonQueryText = `CREATE (p:Person {id: $id, name: $name}) RETURN p`

type CreatePersonParams struct {
	Id   int64
	Name string
}

// CreatePerson executes the CreatePerson query.
//
//	CREATE (p:Person {id: $id, name: $name}) RETURN p
func (q *queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	stmt, err := q.cypherStmt("$gqlc$", createPersonQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Person{}, err
	}
	args, err := agtypeArgs(map[string]any{"id": arg.Id, "name": arg.Name})
	if err != nil {
		return Person{}, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return Person{}, fmt.Errorf("CreatePerson: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Person{}, fmt.Errorf("CreatePerson: %w", err)
		}
		return Person{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Person{}, fmt.Errorf("CreatePerson: scan row: %w", err)
	}
	if rows.Next() {
		return Person{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Person{}, fmt.Errorf("CreatePerson: %w", err)
	}
	if raw0 == nil {
		return Person{}, fmt.Errorf("CreatePerson: column %q is non-nullable but arrived null", "p")
	}
	value0, err := decodePerson(raw0)
	if err != nil {
		return Person{}, fmt.Errorf("CreatePerson: decode column %q: %w", "p", err)
	}
	return value0, nil
}
