// Code generated by gqlc dev. DO NOT EDIT.

package entitymultilabelnamed

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const personEmployeesQueryText = `MATCH (p:Person:Employee) RETURN p`

// PersonEmployees executes the PersonEmployees query.
//
//	MATCH (p:Person:Employee) RETURN p
func (q *queries) PersonEmployees(ctx context.Context) ([]PersonEmployee, error) {
	records, err := q.db.run(ctx, personEmployeesQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]PersonEmployee, 0, len(records))
	for _, record := range records {
		node, isNil, err := neo4j.GetRecordValue[dbtype.Node](record, "p")
		if err != nil {
			return nil, fmt.Errorf("PersonEmployees: decode column %q: %w", "p", err)
		}
		if isNil {
			return nil, fmt.Errorf("PersonEmployees: column %q is non-nullable but arrived null", "p")
		}
		value, err := decodePersonEmployee(node)
		if err != nil {
			return nil, fmt.Errorf("PersonEmployees: decode column %q: %w", "p", err)
		}
		out = append(out, value)
	}
	return out, nil
}
