// Code generated by gqlc dev. DO NOT EDIT.

package nullabletimestamplistelement

import (
	"time"
)

// Entry corresponds to the Entry node type.
type Entry struct {
	Fixed  []time.Time
	Id     int64
	Maybe  *[]*time.Time
	Stamps []*time.Time
}
