// Code generated by gqlc dev. DO NOT EDIT.

package timestampnullableparam

import (
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Sample corresponds to the Sample node type.
type Sample struct {
	Id     int64
	SeenAt *time.Time
}

// decodeSample decodes a driver dbtype.Node into a Sample struct,
// enforcing per-property nullability against the schema.
func decodeSample(node dbtype.Node) (Sample, error) {
	var out Sample
	value0, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Sample{}, fmt.Errorf("decode Sample.Id: %w", err)
	}
	out.Id = value0
	if v, ok := node.Props["seenAt"]; ok {
		s, ok := v.(time.Time)
		if !ok {
			return Sample{}, fmt.Errorf("decode Sample.SeenAt: property %q: expected time.Time, got %T", "seenAt", v)
		}
		out.SeenAt = &s
	}
	return out, nil
}
