// Code generated by gqlc dev. DO NOT EDIT.

package timestampnullableparam

import (
	"time"
)

// Sample corresponds to the Sample node type.
type Sample struct {
	Id     int64
	SeenAt *time.Time
}
