// Code generated by gqlc dev. DO NOT EDIT.

package timestampnullableparam

import (
	"context"
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const samplesSeenAfterQueryText = `MATCH (s:Sample) WHERE s.seenAt > $seenAfter RETURN s.id AS id ORDER BY s.seenAt`

// SamplesSeenAfter executes the SamplesSeenAfter query.
//
//	MATCH (s:Sample) WHERE s.seenAt > $seenAfter RETURN s.id AS id ORDER BY s.seenAt
func (q *Queries) SamplesSeenAfter(ctx context.Context, arg *time.Time) ([]int64, error) {
	records, err := q.db.run(ctx, samplesSeenAfterQueryText, map[string]any{"seenAfter": arg}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("SamplesSeenAfter: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("SamplesSeenAfter: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}
