// Code generated by gqlc dev. DO NOT EDIT.

package timestamppropertyroundtrip

import (
	"context"
	"time"
)

type ReadQuerier interface {
	EventsAfter(ctx context.Context, since time.Time) ([]int64, error)
	EventsSeenAfter(ctx context.Context, seenAfter *time.Time) ([]int64, error)
	EventAt(ctx context.Context, id int64) (time.Time, error)
	EventSeenAt(ctx context.Context, id int64) (*time.Time, error)
	OneEvent(ctx context.Context, id int64) (Event, error)
}

type WriteQuerier interface {
	AddEvent(ctx context.Context, arg AddEventParams) error
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
