// Code generated by gqlc dev. DO NOT EDIT.

package edgeuniontwoedgeunioncolumns

import (
	"context"
	"fmt"
)

const pairActionsQueryText = `MATCH (:Person)-[r1:AUTHORED|LIKES]->(:Post), (:Person)-[r2:AUTHORED|LIKES]->(:Post) RETURN r1, r2`

type PairActionsRow struct {
	R1 PairActionsR1
	R2 PairActionsR2
}

// PairActions executes the PairActions query.
//
//	MATCH (:Person)-[r1:AUTHORED|LIKES]->(:Post), (:Person)-[r2:AUTHORED|LIKES]->(:Post) RETURN r1, r2
func (q *Queries) PairActions(ctx context.Context) (PairActionsRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", pairActionsQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype")
	if err != nil {
		return PairActionsRow{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: %w", err)
		}
		return PairActionsRow{}, ErrNoRows
	}
	var raw0 []byte
	var raw1 []byte
	if err := rows.Scan(&raw0, &raw1); err != nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: scan row: %w", err)
	}
	if rows.Next() {
		return PairActionsRow{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: %w", err)
	}
	var value0 PairActionsR1
	if raw0 == nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q is non-nullable but arrived null", "r1")
	}
	label0, _, err := agtypeEntity(raw0, "::edge")
	if err != nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r1", err)
	}
	switch label0 {
	case "AUTHORED":
		decoded, err := decodeAUTHORED(raw0)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r1", err)
		}
		value0 = decoded
	case "LIKES":
		decoded, err := decodeLIKES(raw0)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r1", err)
		}
		value0 = decoded
	default:
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: unexpected edge label %q", "r1", label0)
	}
	var value1 PairActionsR2
	if raw1 == nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q is non-nullable but arrived null", "r2")
	}
	label1, _, err := agtypeEntity(raw1, "::edge")
	if err != nil {
		return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r2", err)
	}
	switch label1 {
	case "AUTHORED":
		decoded, err := decodeAUTHORED(raw1)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r2", err)
		}
		value1 = decoded
	case "LIKES":
		decoded, err := decodeLIKES(raw1)
		if err != nil {
			return PairActionsRow{}, fmt.Errorf("PairActions: decode column %q: %w", "r2", err)
		}
		value1 = decoded
	default:
		return PairActionsRow{}, fmt.Errorf("PairActions: column %q: unexpected edge label %q", "r2", label1)
	}
	return PairActionsRow{
		R1: value0,
		R2: value1,
	}, nil
}
