// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionmulticolumnrow

import "context"

type ReadQuerier interface {
	PersonAction(ctx context.Context, arg int64) (PersonActionRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
