// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumndate

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

type ReadQuerier interface {
	TodayDate(ctx context.Context) (dbtype.Date, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
