// Code generated by gqlc dev. DO NOT EDIT.

package iterreadentity

import (
	"context"
	"fmt"
	"iter"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const streamPersonsQueryText = `MATCH (p:Person) RETURN p`

// StreamPersons executes the StreamPersons query.
//
//	MATCH (p:Person) RETURN p
//
// The returned sequence holds a database connection for as long as the
// consumer keeps ranging, and releases it when the range ends — by
// exhaustion, by break, or by an error item, which is always the sequence's
// last. Ranging over it while doing per-row work that itself needs a
// connection can deadlock against a bounded pool.
func (q *queries) StreamPersons(ctx context.Context) iter.Seq2[Person, error] {
	return func(yield func(Person, error) bool) {
		q.db.stream(ctx, streamPersonsQueryText, nil, func(record *neo4j.Record, err error) bool {
			if err != nil {
				yield(Person{}, err)
				return false
			}
			node, isNil, err := neo4j.GetRecordValue[dbtype.Node](record, "p")
			if err != nil {
				yield(Person{}, fmt.Errorf("StreamPersons: decode column %q: %w", "p", err))
				return false
			}
			if isNil {
				yield(Person{}, fmt.Errorf("StreamPersons: column %q is non-nullable but arrived null", "p"))
				return false
			}
			value, err := decodePerson(node)
			if err != nil {
				yield(Person{}, fmt.Errorf("StreamPersons: decode column %q: %w", "p", err))
				return false
			}
			return yield(value, nil)
		})
	}
}
