// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumnlocaldatetime

import "context"

type ReadQuerier interface {
	NowLocal(ctx context.Context) (LocalDateTime, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
