// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumnlocaldatetime

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

type ReadQuerier interface {
	NowLocal(ctx context.Context) (dbtype.LocalDateTime, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
