// Code generated by gqlc dev. DO NOT EDIT.

package temporalcolumnlocaldatetime

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const nowLocalQueryText = `RETURN localdatetime() AS ldt`

// NowLocal executes the NowLocal query.
//
//	RETURN localdatetime() AS ldt
func (q *queries) NowLocal(ctx context.Context) (LocalDateTime, error) {
	records, err := q.db.run(ctx, nowLocalQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return LocalDateTime{}, err
	}
	if len(records) == 0 {
		return LocalDateTime{}, ErrNoRows
	}
	if len(records) > 1 {
		return LocalDateTime{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[dbtype.LocalDateTime](records[0], "ldt")
	if err != nil {
		return LocalDateTime{}, fmt.Errorf("NowLocal: decode column %q: %w", "ldt", err)
	}
	if isNil {
		return LocalDateTime{}, fmt.Errorf("NowLocal: column %q is non-nullable but arrived null", "ldt")
	}
	return toLocalDateTime(value), nil
}
