// Code generated by gqlc dev. DO NOT EDIT.

package zonedtimeroundtrip

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Slot corresponds to the Slot node type.
type Slot struct {
	Id       int64
	StartsAt Time
}

// decodeSlot decodes an agtype vertex into a Slot struct, enforcing
// the label and the per-property nullability the schema declares.
func decodeSlot(raw []byte) (Slot, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot: %w", err)
	}
	if label != "Slot" {
		return Slot{}, fmt.Errorf("decode Slot: expected label %q, got %q", "Slot", label)
	}
	var out Slot
	value0, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.Id: %w", err)
	}
	out.Id = value0
	value1, err := agtypeProperty(props, "startsAt", agtypeTime)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.StartsAt: %w", err)
	}
	out.StartsAt, err = agtypeTimeZone(props, "startsAtOffset", value1)
	if err != nil {
		return Slot{}, fmt.Errorf("decode Slot.StartsAt: %w", err)
	}
	return out, nil
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeTime decodes a stored TIME: the integer scalar, counting
// microseconds since midnight UTC-NORMALISED — the reading the writer saw
// minus the offset it was read at, wrapped into the day. Normalising is
// what makes the count comparable across offsets, so agtype's integer
// ordering is instant order and an author's ORDER BY needs no rewriting;
// a raw local reading would sort 23:00+02:00 after 22:30+00:00 when the
// first is the earlier instant.
//
// What comes back here is therefore the UTC reading, with OffsetSeconds
// left zero. Where the value is an entity property, agtypeTimeZone reads
// the sidecar beside it and puts the reading back in its own zone; where
// it is a projected column there is no sidecar to read, and UTC is the
// whole of what the count carries.
//
// The count is bounded to [0, 86400000000) before the reading is built,
// because a count outside it names no clock reading at all and gqlc's
// encode is not the only writer of the property. Sub-microsecond
// precision is not in the count: it truncated at encode, which is this
// backend's one policy for every temporal it stores.
func agtypeTime(raw []byte) (Time, error) {
	micros, err := agtypeInt64(raw)
	if err != nil {
		return Time{}, err
	}
	if micros < 0 || micros >= 86400000000 {
		return Time{}, fmt.Errorf(
			"gqlc: %d microseconds since midnight is outside the [0, 86400000000) interval a clock reading occupies", micros)
	}
	return agtypeTimeAt(micros, 0), nil
}

// agtypeTimeAt builds a clock reading from a microsecond count already
// known to be in [0, 86400000000), recording the offset it is a reading
// at. The component arithmetic is here rather than at its two call sites
// so decode and re-zoning cannot drift apart in it.
func agtypeTimeAt(micros int64, offset int) Time {
	return Time{
		Hour:          int(micros / 3600000000),
		Minute:        int(micros / 60000000 % 60),
		Second:        int(micros / 1000000 % 60),
		Nanosecond:    int(micros % 1000000 * 1000),
		OffsetSeconds: offset,
	}
}

// agtypeWrapDay reduces a microsecond count into the [0, 86400000000)
// interval a clock reading occupies, which shifting a reading by an
// offset can leave it outside in either direction. Both directions of the
// TIME encoding go through it: encode subtracts the offset, decode adds
// it back.
//
// The explicit correction is load-bearing. Go's % follows the sign of its
// left operand, so -1 % 86400000000 is -1 and not the 86399999999 the
// day-before reading actually is: taking the remainder alone leaves a
// negative count that then builds a reading with negative components, or
// stores one no decode will accept.
func agtypeWrapDay(micros int64) int64 {
	micros %= 86400000000
	if micros < 0 {
		micros += 86400000000
	}
	return micros
}

// agtypeTimeZone puts a decoded TIME back in the zone it was written in,
// reading the offset-seconds sidecar stored beside it. Where the instant
// re-zones by moving a Location and leaving the moment alone, this one
// rebuilds the clock reading: the stored count is UTC-normalised, so the
// reading the writer saw is that count plus the offset, wrapped back into
// the day.
//
// An absent sidecar leaves the UTC reading as it is, which is the same
// instant with OffsetSeconds zero.
func agtypeTimeZone(props map[string][]byte, key string, t Time) (Time, error) {
	offset, ok, err := agtypeOffset(props, key)
	if err != nil {
		return Time{}, err
	}
	if !ok {
		return t, nil
	}
	micros := int64(t.Hour)*3600000000 + int64(t.Minute)*60000000 +
		int64(t.Second)*1000000 + int64(t.Nanosecond)/1000
	return agtypeTimeAt(agtypeWrapDay(micros+int64(offset)*1000000), offset), nil
}

// agtypeOffset reads the offset-seconds sidecar stored beside a zoned
// value, with ok=false where the graph holds no such property. An absent
// sidecar is not an error: the stored count is complete without it, so
// the property stays readable by anything that never wrote one —
// including this package, which binds the value alone. Where a sidecar
// goes is the author's query text, and gqlc runs that text as written.
//
// Flat rather than a member of a map so the value stays the property
// itself: ORDER BY n.at and WHERE n.at > $since are then answered by
// agtype's integer ordering, with nothing for gqlc to rewrite.
//
// The offset is bounded at a day either way, exclusive, before it is
// taken. gqlc derives no sidecar to bind — a parameter crosses as the
// value alone — so the integer read here is whatever the graph holds: a
// query that names the key binds it like any other property, whether or
// not gqlc generated that query. Unbounded it names a zone no clock
// keeps, and the wall clock the caller then reads is arbitrarily far
// from the value stored beside it. The bound is a day rather than the
// narrower range zone databases populate today, so a graph a future zone
// database would accept is not refused here.
//
// Both zoned widths read their sidecar through this, so the bound is one
// policy and not two agreeing by inspection.
func agtypeOffset(props map[string][]byte, key string) (int, bool, error) {
	raw, ok := props[key]
	if !ok {
		return 0, false, nil
	}
	offset, err := agtypeInt64(raw)
	if err != nil {
		return 0, false, fmt.Errorf("gqlc: offset %q: %w", key, err)
	}
	if offset <= -86400 || offset >= 86400 {
		return 0, false, fmt.Errorf("gqlc: offset %q is %d seconds, which is not within a day of UTC", key, offset)
	}
	return int(offset), true, nil
}

// agtypeTimeMicros encodes a TIME into the integer a query binds it as,
// the same count agtypeTime reads back: the clock reading UTC-NORMALISED,
// which is the reading minus its offset wrapped into the day.
//
// Normalising here is what the stored ordering rests on. Two readings at
// different offsets compare as instants because both counts are on one
// scale; storing the local reading instead would sort 23:00+02:00 after
// 22:30+00:00 when it is the earlier instant by half an hour.
//
// The offset does not cross beside it. gqlc adds no parameter to the
// author's query (ADR 0005), so a value bound here and read back through
// this package returns at the same instant with OffsetSeconds zero — the
// original zone comes back only from a sidecar the author's own query
// text writes. That is the instant's arrangement exactly, one width down.
//
// Each component is bounded on its own, and the offset with the bound
// agtypeOffset applies on the way in, so what is stored is a count some
// clock somewhere actually read. Sub-microsecond precision truncates,
// this backend's policy for every temporal it stores.
func agtypeTimeMicros(t Time) (int64, error) {
	if t.Hour < 0 || t.Hour > 23 || t.Minute < 0 || t.Minute > 59 ||
		t.Second < 0 || t.Second > 59 || t.Nanosecond < 0 || t.Nanosecond > 999999999 {
		return 0, fmt.Errorf(
			"gqlc: hour %d minute %d second %d nanosecond %d is not a clock reading",
			t.Hour, t.Minute, t.Second, t.Nanosecond)
	}
	if t.OffsetSeconds <= -86400 || t.OffsetSeconds >= 86400 {
		return 0, fmt.Errorf(
			"gqlc: offset %d seconds is not within a day of UTC", t.OffsetSeconds)
	}
	local := int64(t.Hour)*3600000000 + int64(t.Minute)*60000000 +
		int64(t.Second)*1000000 + int64(t.Nanosecond)/1000
	return agtypeWrapDay(local - int64(t.OffsetSeconds)*1000000), nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}
