// Code generated by gqlc dev. DO NOT EDIT.

package zonedtimeroundtrip

import "context"

type ReadQuerier interface {
	SlotsFrom(ctx context.Context, arg Time) ([]int64, error)
	SlotStart(ctx context.Context, arg int64) (Time, error)
	OneSlot(ctx context.Context, arg int64) (Slot, error)
}

type WriteQuerier interface {
	AddSlot(ctx context.Context, arg AddSlotParams) error
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
