// Code generated by gqlc dev. DO NOT EDIT.

package writeexectemporalparam

import (
	"sync"
	"time"
)

// fromTimestamp binds a TIMESTAMP in a form the server accepts. A value
// whose zone the driver sends as an id the server takes is sent as it is
// (time.UTC among them: LoadLocation("UTC") is time.UTC); any other is
// moved, same instant and same offset, into a fixed zone named "Offset",
// which the driver sends as an offset instead.
func fromTimestamp(v time.Time) time.Time {
	_, offset := v.Zone()
	if timestampZoneIsSendable(v, offset) {
		return v
	}
	return v.In(time.FixedZone("Offset", offset))
}

// timestampZones caches time.LoadLocation by name, guarded by
// timestampZonesMu; a nil entry is a name not to send as a zone id. It is
// seeded with the names the server refuses that LoadLocation would not
// reject: "" and "Local", which it resolves to UTC and to time.Local, and
// the five ids Go's tzdata loads and the server does not.
var (
	timestampZonesMu sync.Mutex
	timestampZones   = map[string]*time.Location{
		"": nil, "Local": nil, "EST": nil, "HST": nil, "MST": nil, "ROC": nil, "Factory": nil,
	}
)

// timestampZoneIsSendable reports whether v's location name is a zone id
// the server accepts and that this host's tzdata resolves to the offset v
// reads. A name that loads at a different offset is a FixedZone
// mislabelled with a real id, which the server would store at the id's
// offset rather than v's. The server's tzdb can itself disagree with Go's
// for a few name and instant pairs (measured 2026-10-04: Africa/Casablanca
// and Africa/El_Aaiun in 2040, CST6CDT, EST5EDT and PST8PDT in 1950); it
// then stores its own offset at the same instant, as a bare send did.
func timestampZoneIsSendable(v time.Time, offset int) bool {
	name := v.Location().String()
	timestampZonesMu.Lock()
	loc, ok := timestampZones[name]
	if !ok {
		loc, _ = time.LoadLocation(name)
		timestampZones[name] = loc
	}
	timestampZonesMu.Unlock()
	if loc == nil {
		return false
	}
	_, want := v.In(loc).Zone()
	return want == offset
}
