// Code generated by gqlc dev. DO NOT EDIT.

package iterreadscalar

import (
	"context"
	"fmt"
	"iter"
)

const streamPersonNamesQueryText = `MATCH (p:Person) RETURN p.name`

// StreamPersonNames executes the StreamPersonNames query.
//
//	MATCH (p:Person) RETURN p.name
//
// The returned sequence holds a database connection for as long as the
// consumer keeps ranging, and releases it when the range ends — by
// exhaustion, by break, or by an error item, which is always the sequence's
// last. Ranging over it while doing per-row work that itself needs a
// connection can deadlock against a bounded pool.
func (q *queries) StreamPersonNames(ctx context.Context) iter.Seq2[string, error] {
	return func(yield func(string, error) bool) {
		stmt, err := q.cypherStmt("$gqlc$", streamPersonNamesQueryText, "v0 ag_catalog.agtype")
		if err != nil {
			yield("", err)
			return
		}
		rows, err := q.db.Query(ctx, stmt, "{}")
		if err != nil {
			yield("", fmt.Errorf("StreamPersonNames: %w", err))
			return
		}
		defer rows.Close()
		for rows.Next() {
			var raw0 []byte
			if err := rows.Scan(&raw0); err != nil {
				yield("", fmt.Errorf("StreamPersonNames: scan row: %w", err))
				return
			}
			if raw0 == nil {
				yield("", fmt.Errorf("StreamPersonNames: column %q is non-nullable but arrived null", "p.name"))
				return
			}
			value0, err := agtypeString(raw0)
			if err != nil {
				yield("", fmt.Errorf("StreamPersonNames: decode column %q: %w", "p.name", err))
				return
			}
			if !yield(value0, nil) {
				return
			}
		}
		if err := rows.Err(); err != nil {
			yield("", fmt.Errorf("StreamPersonNames: %w", err))
			return
		}
	}
}
