// Code generated by gqlc dev. DO NOT EDIT.

package writeexeczeroparam

import (
	"context"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const truncatePeopleQueryText = `MATCH (p:Person) DELETE p`

// TruncatePeople executes the TruncatePeople query.
//
//	MATCH (p:Person) DELETE p
func (q *Queries) TruncatePeople(ctx context.Context) error {
	_, err := q.db.run(ctx, truncatePeopleQueryText, nil, neo4j.AccessModeWrite)
	return err
}
