// Code generated by gqlc dev. DO NOT EDIT.

package manycolonerow

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Age  int64
	Id   int64
	Name string
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodePerson(node dbtype.Node) (Person, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Person" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Person{}, fmt.Errorf("decode Person: expected a node labelled %q, got labels %q", "Person", node.Labels)
	}
	var out Person
	value0, err := neo4j.GetProperty[int64](node, "age")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Age: %w", err)
	}
	out.Age = value0
	value1, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = value1
	value2, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Name: %w", err)
	}
	out.Name = value2
	return out, nil
}
