// Code generated by gqlc dev. DO NOT EDIT.

package schemaanypropertyalone

import (
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Blob corresponds to the Blob node type.
type Blob struct {
	Payload *any
	Tag     *any
}

// decodeBlob decodes a driver dbtype.Node into a Blob struct,
// enforcing per-property nullability against the schema.
func decodeBlob(node dbtype.Node) (Blob, error) {
	var out Blob
	if v, ok := node.Props["payload"]; ok {
		out.Payload = &v
	}
	if v, ok := node.Props["tag"]; ok {
		out.Tag = &v
	}
	return out, nil
}
