// Code generated by gqlc dev. DO NOT EDIT.

package schemaanypropertyalone

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Blob corresponds to the Blob node type.
type Blob struct {
	Payload *any
	Tag     *any
}

// decodeBlob decodes a driver dbtype.Node into a Blob struct,
// enforcing the wire label and the per-property nullability the
// schema declares.
func decodeBlob(node dbtype.Node) (Blob, error) {
	has0 := false
	for _, label := range node.Labels {
		if label == "Blob" {
			has0 = true
			break
		}
	}
	if !has0 {
		return Blob{}, fmt.Errorf("decode Blob: expected a node labelled %q, got labels %q", "Blob", node.Labels)
	}
	var out Blob
	if v, ok := node.Props["payload"]; ok {
		out.Payload = &v
	}
	if v, ok := node.Props["tag"]; ok {
		out.Tag = &v
	}
	return out, nil
}
