// Code generated by gqlc dev. DO NOT EDIT.

package schemaanypropertyalone

import "context"

type ReadQuerier interface {
	Blobs(ctx context.Context) ([]Blob, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
