// Code generated by gqlc dev. DO NOT EDIT.

package edgeunionnullablecolumn

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const maybeActionQueryText = `MATCH (p:Person) WHERE p.id = $id
OPTIONAL MATCH (p)-[r:AUTHORED|LIKES]->(:Post)
RETURN r`

// MaybeAction executes the MaybeAction query.
//
//	MATCH (p:Person) WHERE p.id = $id
//	OPTIONAL MATCH (p)-[r:AUTHORED|LIKES]->(:Post)
//	RETURN r
func (q *Queries) MaybeAction(ctx context.Context, id int64) (MaybeActionR, error) {
	records, err := q.db.run(ctx, maybeActionQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	raw, ok := records[0].Get("r")
	if !ok {
		return nil, fmt.Errorf("MaybeAction: column %q missing from record", "r")
	}
	if raw == nil {
		return nil, nil
	} else {
		rel, ok := raw.(dbtype.Relationship)
		if !ok {
			return nil, fmt.Errorf("MaybeAction: column %q: expected dbtype.Relationship, got %T", "r", raw)
		}
		switch rel.Type {
		case "AUTHORED":
			entity, err := decodeAUTHORED(rel)
			if err != nil {
				return nil, fmt.Errorf("MaybeAction: decode column %q: %w", "r", err)
			}
			return entity, nil
		case "LIKES":
			entity, err := decodeLIKES(rel)
			if err != nil {
				return nil, fmt.Errorf("MaybeAction: decode column %q: %w", "r", err)
			}
			return entity, nil
		default:
			return nil, fmt.Errorf("MaybeAction: column %q: unexpected relationship type %q", "r", rel.Type)
		}
	}
}
