// Code generated by gqlc dev. DO NOT EDIT.

package uniononlycarrierentitydecodeonly

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const accountWholeQueryText = `MATCH (a:Account) WHERE a.id = $id RETURN a`

// AccountWhole executes the AccountWhole query.
//
//	MATCH (a:Account) WHERE a.id = $id RETURN a
func (q *queries) AccountWhole(ctx context.Context, arg int64) (Account, error) {
	records, err := q.db.run(ctx, accountWholeQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Account{}, err
	}
	if len(records) == 0 {
		return Account{}, ErrNoRows
	}
	if len(records) > 1 {
		return Account{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "a")
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	if isNil {
		return Account{}, fmt.Errorf("AccountWhole: column %q is non-nullable but arrived null", "a")
	}
	value, err := decodeAccount(node)
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	return value, nil
}
