// Code generated by gqlc dev. DO NOT EDIT.

package float32parameter

import "context"

type ReadQuerier interface {
	PeopleAtHeight(ctx context.Context, h float32) ([]string, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
