// Code generated by gqlc dev. DO NOT EDIT.

package entityzeropropertynode

import (
	"context"
	"fmt"
)

const markersQueryText = `MATCH (m:Marker) RETURN m`

// Markers executes the Markers query.
//
//	MATCH (m:Marker) RETURN m
func (q *queries) Markers(ctx context.Context) ([]Marker, error) {
	stmt, err := q.cypherStmt("$gqlc$", markersQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("Markers: %w", err)
	}
	defer rows.Close()
	out := make([]Marker, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("Markers: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("Markers: column %q is non-nullable but arrived null", "m")
		}
		value0, err := decodeMarker(raw0)
		if err != nil {
			return nil, fmt.Errorf("Markers: decode column %q: %w", "m", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("Markers: %w", err)
	}
	return out, nil
}
