// Code generated by gqlc dev. DO NOT EDIT.

package unionproperty

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const rowWholeQueryText = `MATCH (r:Row) RETURN r`

// RowWhole executes the RowWhole query.
//
//	MATCH (r:Row) RETURN r
func (q *queries) RowWhole(ctx context.Context) (Row, error) {
	records, err := q.db.run(ctx, rowWholeQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return Row{}, err
	}
	if len(records) == 0 {
		return Row{}, ErrNoRows
	}
	if len(records) > 1 {
		return Row{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "r")
	if err != nil {
		return Row{}, fmt.Errorf("RowWhole: decode column %q: %w", "r", err)
	}
	if isNil {
		return Row{}, fmt.Errorf("RowWhole: column %q is non-nullable but arrived null", "r")
	}
	value, err := decodeRow(node)
	if err != nil {
		return Row{}, fmt.Errorf("RowWhole: decode column %q: %w", "r", err)
	}
	return value, nil
}

const rowColumnsQueryText = `MATCH (r:Row) RETURN r.pick AS pick, r.also AS also, r.flag AS flag`

type RowColumnsRow struct {
	Pick *any
	Also *any
	Flag *any
}

// RowColumns executes the RowColumns query.
//
//	MATCH (r:Row) RETURN r.pick AS pick, r.also AS also, r.flag AS flag
func (q *queries) RowColumns(ctx context.Context) ([]RowColumnsRow, error) {
	records, err := q.db.run(ctx, rowColumnsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]RowColumnsRow, 0, len(records))
	for _, record := range records {
		var row RowColumnsRow
		value0, ok := record.Get("pick")
		if !ok {
			return nil, fmt.Errorf("RowColumns: decode column %q: key not found", "pick")
		}
		var value0Ptr *any
		if value0 != nil {
			v, err := decodeUnion2f53465c(value0)
			if err != nil {
				return nil, fmt.Errorf("RowColumns: decode column %q: %w", "pick", err)
			}
			value0Ptr = &v
		}
		row.Pick = value0Ptr
		value1, ok := record.Get("also")
		if !ok {
			return nil, fmt.Errorf("RowColumns: decode column %q: key not found", "also")
		}
		var value1Ptr *any
		if value1 != nil {
			v, err := decodeUnion2f53465c(value1)
			if err != nil {
				return nil, fmt.Errorf("RowColumns: decode column %q: %w", "also", err)
			}
			value1Ptr = &v
		}
		row.Also = value1Ptr
		value2, ok := record.Get("flag")
		if !ok {
			return nil, fmt.Errorf("RowColumns: decode column %q: key not found", "flag")
		}
		var value2Ptr *any
		if value2 != nil {
			v, err := decodeUnion8b198fa4(value2)
			if err != nil {
				return nil, fmt.Errorf("RowColumns: decode column %q: %w", "flag", err)
			}
			value2Ptr = &v
		}
		row.Flag = value2Ptr
		out = append(out, row)
	}
	return out, nil
}

const rowsByPickQueryText = `MATCH (r:Row) WHERE r.pick = $pick RETURN r.id AS id`

// RowsByPick executes the RowsByPick query.
//
//	MATCH (r:Row) WHERE r.pick = $pick RETURN r.id AS id
func (q *queries) RowsByPick(ctx context.Context, arg *any) ([]int64, error) {
	param0, err := encodeUnion2f53465cPtr(arg)
	if err != nil {
		return nil, err
	}
	records, err := q.db.run(ctx, rowsByPickQueryText, map[string]any{"pick": param0}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("RowsByPick: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("RowsByPick: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}
