// Code generated by gqlc dev. DO NOT EDIT.

package certifiedlistelement

import (
	"context"
	"fmt"
)

const personIdQueryText = `MATCH (p:Person) RETURN p.id AS id`

// PersonId executes the PersonId query.
//
//	MATCH (p:Person) RETURN p.id AS id
func (q *queries) PersonId(ctx context.Context) ([]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", personIdQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonId: %w", err)
	}
	defer rows.Close()
	out := make([]int64, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonId: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonId: column %q is non-nullable but arrived null", "id")
		}
		value0, err := agtypeInt64(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonId: decode column %q: %w", "id", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonId: %w", err)
	}
	return out, nil
}

const personPairQueryText = `MATCH (p:Person) RETURN [p.id, p.age] AS pair`

// PersonPair executes the PersonPair query.
//
//	MATCH (p:Person) RETURN [p.id, p.age] AS pair
func (q *queries) PersonPair(ctx context.Context) ([][]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", personPairQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonPair: %w", err)
	}
	defer rows.Close()
	out := make([][]int64, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonPair: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonPair: column %q is non-nullable but arrived null", "pair")
		}
		value0, err := agtypeListOfInt64(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonPair: decode column %q: %w", "pair", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonPair: %w", err)
	}
	return out, nil
}

const personCollectIdQueryText = `MATCH (p:Person) RETURN collect(p.id) AS ids`

// PersonCollectId executes the PersonCollectId query.
//
//	MATCH (p:Person) RETURN collect(p.id) AS ids
func (q *queries) PersonCollectId(ctx context.Context) ([]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", personCollectIdQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonCollectId: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("PersonCollectId: %w", err)
		}
		return nil, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return nil, fmt.Errorf("PersonCollectId: scan row: %w", err)
	}
	if rows.Next() {
		return nil, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonCollectId: %w", err)
	}
	if raw0 == nil {
		return nil, fmt.Errorf("PersonCollectId: column %q is non-nullable but arrived null", "ids")
	}
	value0, err := agtypeListOfInt64(raw0)
	if err != nil {
		return nil, fmt.Errorf("PersonCollectId: decode column %q: %w", "ids", err)
	}
	return value0, nil
}

const personCollectPairQueryText = `MATCH (p:Person) RETURN collect([p.id, p.age]) AS pairs`

// PersonCollectPair executes the PersonCollectPair query.
//
//	MATCH (p:Person) RETURN collect([p.id, p.age]) AS pairs
func (q *queries) PersonCollectPair(ctx context.Context) ([][]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", personCollectPairQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonCollectPair: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("PersonCollectPair: %w", err)
		}
		return nil, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return nil, fmt.Errorf("PersonCollectPair: scan row: %w", err)
	}
	if rows.Next() {
		return nil, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonCollectPair: %w", err)
	}
	if raw0 == nil {
		return nil, fmt.Errorf("PersonCollectPair: column %q is non-nullable but arrived null", "pairs")
	}
	value0, err := agtypeListOfListOfInt64(raw0)
	if err != nil {
		return nil, fmt.Errorf("PersonCollectPair: decode column %q: %w", "pairs", err)
	}
	return value0, nil
}

const personNullablePairQueryText = `MATCH (p:Person) RETURN [p.score, p.score] AS scores`

// PersonNullablePair executes the PersonNullablePair query.
//
//	MATCH (p:Person) RETURN [p.score, p.score] AS scores
func (q *queries) PersonNullablePair(ctx context.Context) ([][]int64, error) {
	stmt, err := q.cypherStmt("$gqlc$", personNullablePairQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonNullablePair: %w", err)
	}
	defer rows.Close()
	out := make([][]int64, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonNullablePair: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonNullablePair: column %q is non-nullable but arrived null", "scores")
		}
		value0, err := agtypeListOfInt64(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonNullablePair: decode column %q: %w", "scores", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonNullablePair: %w", err)
	}
	return out, nil
}

const personNarrowPairQueryText = `MATCH (p:Person) RETURN [p.rank, p.rank] AS ranks`

// PersonNarrowPair executes the PersonNarrowPair query.
//
//	MATCH (p:Person) RETURN [p.rank, p.rank] AS ranks
func (q *queries) PersonNarrowPair(ctx context.Context) ([][]int32, error) {
	stmt, err := q.cypherStmt("$gqlc$", personNarrowPairQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonNarrowPair: %w", err)
	}
	defer rows.Close()
	out := make([][]int32, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonNarrowPair: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonNarrowPair: column %q is non-nullable but arrived null", "ranks")
		}
		value0, err := agtypeListOfInt32(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonNarrowPair: decode column %q: %w", "ranks", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonNarrowPair: %w", err)
	}
	return out, nil
}

const personFoldPairQueryText = `MATCH (p:Person) RETURN [p.id + p.age] AS folded`

// PersonFoldPair executes the PersonFoldPair query.
//
//	MATCH (p:Person) RETURN [p.id + p.age] AS folded
func (q *queries) PersonFoldPair(ctx context.Context) ([][]any, error) {
	stmt, err := q.cypherStmt("$gqlc$", personFoldPairQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("PersonFoldPair: %w", err)
	}
	defer rows.Close()
	out := make([][]any, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("PersonFoldPair: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("PersonFoldPair: column %q is non-nullable but arrived null", "folded")
		}
		value0, err := agtypeListOfAny(raw0)
		if err != nil {
			return nil, fmt.Errorf("PersonFoldPair: decode column %q: %w", "folded", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("PersonFoldPair: %w", err)
	}
	return out, nil
}
