// Code generated by gqlc dev. DO NOT EDIT.

package nullablecolumns

import "context"

type ReadQuerier interface {
	PersonProfile(ctx context.Context, arg int64) (PersonProfileRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
