// Code generated by gqlc dev. DO NOT EDIT.

package certifiedselection

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Person corresponds to the Person node type.
type Person struct {
	Name string
	Rank int32
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeIntAs decodes an agtype integer into a width narrower than the
// int64 scalar it rides in, refusing a stored value that width cannot
// hold rather than wrapping it.
//
// Two clauses, and both are load-bearing. The round-trip catches every
// width whose range is a strict subset of int64's. It cannot catch
// uint64, where the conversion is a bijection and int64(uint64(-1)) is
// -1 again; there the sign comparison is the whole of the check. A
// UINT64 property's readable set is therefore [0, MaxInt64], since
// agtype's integer scalar is signed 64-bit and a larger value is
// unstorable rather than unreadable.
func agtypeIntAs[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](raw []byte) (T, error) {
	v, err := agtypeInt64(raw)
	if err != nil {
		return 0, err
	}
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("gqlc: value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}
