// Code generated by gqlc dev. DO NOT EDIT.

package twodateparams

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Event corresponds to the Event node type.
type Event struct {
	Created dbtype.Date
	Id      int64
	Name    string
}

// decodeEvent decodes a driver dbtype.Node into a Event struct,
// enforcing per-property nullability against the schema.
func decodeEvent(node dbtype.Node) (Event, error) {
	var out Event
	created, err := neo4j.GetProperty[dbtype.Date](node, "created")
	if err != nil {
		return Event{}, fmt.Errorf("decode Event.Created: %w", err)
	}
	out.Created = created
	id, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Event{}, fmt.Errorf("decode Event.Id: %w", err)
	}
	out.Id = id
	name, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Event{}, fmt.Errorf("decode Event.Name: %w", err)
	}
	out.Name = name
	return out, nil
}
