// Code generated by gqlc dev. DO NOT EDIT.

package scalarnull

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const oneNullQueryText = `RETURN null AS n`

// OneNull executes the OneNull query.
//
//	RETURN null AS n
func (q *Queries) OneNull(ctx context.Context) (any, error) {
	records, err := q.db.run(ctx, oneNullQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, ok := records[0].Get("n")
	if !ok {
		return nil, fmt.Errorf("OneNull: decode column %q: key not found", "n")
	}
	return value, nil
}
