// Code generated by gqlc dev. DO NOT EDIT.

package schemalistpropertyunprojected

import "context"

type ReadQuerier interface {
	EventIds(ctx context.Context) ([]int64, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
