// Code generated by gqlc dev. DO NOT EDIT.

package writemanyprojectionproperty

// Person corresponds to the Person node type.
type Person struct {
	Age     int64
	Checked bool
	Id      int64
	Name    string
}
