// Code generated by gqlc dev. DO NOT EDIT.

package uniononlycarrierrecordmember

import "context"

type ReadQuerier interface {
	LedgerWhole(ctx context.Context, arg int64) (Ledger, error)
	LedgerEntry(ctx context.Context) ([]*any, error)
	LedgersByEntry(ctx context.Context, arg *any) ([]int64, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
