// Code generated by gqlc dev. DO NOT EDIT.

package uniononlyuuidcarrier

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

const accountWholeQueryText = `MATCH (a:Account) WHERE a.id = $id RETURN a`

// AccountWhole executes the AccountWhole query.
//
//	MATCH (a:Account) WHERE a.id = $id RETURN a
func (q *queries) AccountWhole(ctx context.Context, arg int64) (Account, error) {
	records, err := q.db.run(ctx, accountWholeQueryText, map[string]any{"id": arg}, neo4j.AccessModeRead)
	if err != nil {
		return Account{}, err
	}
	if len(records) == 0 {
		return Account{}, ErrNoRows
	}
	if len(records) > 1 {
		return Account{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "a")
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	if isNil {
		return Account{}, fmt.Errorf("AccountWhole: column %q is non-nullable but arrived null", "a")
	}
	value, err := decodeAccount(node)
	if err != nil {
		return Account{}, fmt.Errorf("AccountWhole: decode column %q: %w", "a", err)
	}
	return value, nil
}

const accountEitherQueryText = `MATCH (a:Account) RETURN a.either AS either`

// AccountEither executes the AccountEither query.
//
//	MATCH (a:Account) RETURN a.either AS either
func (q *queries) AccountEither(ctx context.Context) ([]*any, error) {
	records, err := q.db.run(ctx, accountEitherQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]*any, 0, len(records))
	for _, record := range records {
		value, ok := record.Get("either")
		if !ok {
			return nil, fmt.Errorf("AccountEither: decode column %q: key not found", "either")
		}
		var valuePtr *any
		if value != nil {
			v, err := decodeUnion26f53c9e(value)
			if err != nil {
				return nil, fmt.Errorf("AccountEither: decode column %q: %w", "either", err)
			}
			valuePtr = &v
		}
		out = append(out, valuePtr)
	}
	return out, nil
}

const accountsByEitherQueryText = `MATCH (a:Account) WHERE a.either = $either RETURN a.id AS id`

// AccountsByEither executes the AccountsByEither query.
//
//	MATCH (a:Account) WHERE a.either = $either RETURN a.id AS id
func (q *queries) AccountsByEither(ctx context.Context, arg *any) ([]int64, error) {
	param0, err := encodeUnion26f53c9ePtr(arg)
	if err != nil {
		return nil, err
	}
	records, err := q.db.run(ctx, accountsByEitherQueryText, map[string]any{"either": param0}, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]int64, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[int64](record, "id")
		if err != nil {
			return nil, fmt.Errorf("AccountsByEither: decode column %q: %w", "id", err)
		}
		if isNil {
			return nil, fmt.Errorf("AccountsByEither: column %q is non-nullable but arrived null", "id")
		}
		out = append(out, value)
	}
	return out, nil
}
