// Code generated by gqlc dev. DO NOT EDIT.

package entitynodeandscalarrow

import "context"

type ReadQuerier interface {
	OnePersonWithAge(ctx context.Context) (OnePersonWithAgeRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
