// Code generated by gqlc dev. DO NOT EDIT.

package liststring

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const oneNameListQueryText = `RETURN ['a', 'b', 'c'] AS xs`

// OneNameList executes the OneNameList query.
//
//	RETURN ['a', 'b', 'c'] AS xs
func (q *Queries) OneNameList(ctx context.Context) ([]string, error) {
	records, err := q.db.run(ctx, oneNameListQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[[]any](records[0], "xs")
	if err != nil {
		return nil, fmt.Errorf("OneNameList: decode column %q: %w", "xs", err)
	}
	if isNil {
		return nil, fmt.Errorf("OneNameList: column %q is non-nullable but arrived null", "xs")
	}
	acc := make([]string, 0, len(value))
	for i, elem := range value {
		v, ok := elem.(string)
		if !ok {
			return nil, fmt.Errorf("OneNameList: decode column %q element %d: expected string, got %T", "xs", i, elem)
		}
		acc = append(acc, v)
	}
	return acc, nil
}
