// Code generated by gqlc dev. DO NOT EDIT.

package allwidths

import "context"

type ReadQuerier interface {
	AllWidths(ctx context.Context) (AllWidthsRow, error)
	AllRows(ctx context.Context) ([]Row, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
