// Code generated by gqlc dev. DO NOT EDIT.

package recordproperty

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Dwelling corresponds to the Dwelling node type.
type Dwelling struct {
	Home struct {
		Note    *string
		ZipCode int32
	}
	Id    int64
	Moves *[]struct {
		Note    *string
		ZipCode int32
	}
	Opened struct {
		Label    string
		OpenedOn Date
	}
	Prior *struct {
		Note    *string
		ZipCode int32
	}
}

// decodeDwelling decodes an agtype vertex into a Dwelling struct, enforcing
// the label and the per-property nullability the schema declares.
func decodeDwelling(raw []byte) (Dwelling, error) {
	label, props, err := agtypeEntity(raw, "::vertex")
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling: %w", err)
	}
	if label != "Dwelling" {
		return Dwelling{}, fmt.Errorf("decode Dwelling: expected label %q, got %q", "Dwelling", label)
	}
	var out Dwelling
	value0, err := agtypeProperty(props, "home", decodeRecord4329c440)
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling.Home: %w", err)
	}
	out.Home = value0
	value1, err := agtypeProperty(props, "id", agtypeInt64)
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling.Id: %w", err)
	}
	out.Id = value1
	value2, err := agtypeNullableProperty(props, "moves", agtypeListOfRecord4329c440)
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling.Moves: %w", err)
	}
	out.Moves = value2
	value3, err := agtypeProperty(props, "opened", decodeRecordf3273f80)
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling.Opened: %w", err)
	}
	out.Opened = value3
	value4, err := agtypeNullableProperty(props, "prior", decodeRecord4329c440)
	if err != nil {
		return Dwelling{}, fmt.Errorf("decode Dwelling.Prior: %w", err)
	}
	out.Prior = value4
	return out, nil
}

// record4329c440 is the carrier for RECORD<note STRING,zip_code INT32 NOT NULL>.
type record4329c440 = struct {
	Note    *string
	ZipCode int32
}

// recordf3273f80 is the carrier for RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>.
type recordf3273f80 = struct {
	Label    string
	OpenedOn Date
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeInt64 decodes an agtype integer scalar, whose range is Go's
// int64. A value carrying the ::numeric annotation is one AGE evaluated
// in arbitrary precision: it is an integer only if it survives the parse
// as one, so a fractional part fails the decode rather than truncating
// quietly.
func agtypeInt64(raw []byte) (int64, error) {
	out, err := strconv.ParseInt(strings.TrimSuffix(string(raw), "::numeric"), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gqlc: %q is not an agtype integer: %w", raw, err)
	}
	return out, nil
}

// agtypeIntAs decodes an agtype integer into a width narrower than the
// int64 scalar it rides in, refusing a stored value that width cannot
// hold rather than wrapping it.
//
// Two clauses, and both are load-bearing. The round-trip catches every
// width whose range is a strict subset of int64's. It cannot catch
// uint64, where the conversion is a bijection and int64(uint64(-1)) is
// -1 again; there the sign comparison is the whole of the check. A
// UINT64 property's readable set is therefore [0, MaxInt64], since
// agtype's integer scalar is signed 64-bit and a larger value is
// unstorable rather than unreadable.
func agtypeIntAs[T ~int | ~int8 | ~int16 | ~int32 | ~int64 |
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64](raw []byte) (T, error) {
	v, err := agtypeInt64(raw)
	if err != nil {
		return 0, err
	}
	out := T(v)
	if int64(out) != v || (out < T(0)) != (v < 0) {
		return 0, fmt.Errorf("gqlc: value %d does not fit the declared %T width", v, out)
	}
	return out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDate decodes a stored DATE. agtype has no temporal value, so
// gqlc stores one as the string scalar in zero-padded ISO YYYY-MM-DD:
// the one temporal spelling whose lexical order is its chronological
// order, so an author's ORDER BY n.dob is answered by the database's own
// string comparison with nothing for gqlc to rewrite.
//
// That ordering holds across [0001-01-01, 9999-12-31] and nowhere else,
// which is why the padding and the bound are read back here rather than
// assumed. A year needing a fifth digit sorts under every four-digit year
// because '1' < '2', and a proleptic year before 1 CE needs a sign, which
// sorts under every digit and files the whole era at the front,
// ascending. gqlc's own encode produces neither — it refuses them — but
// it writes to an ordinary agtype string property on a vertex any writer
// can touch, so what is read back is whatever the graph holds.
//
// The padding is enforced by the layout and not by a check beside it.
// time.Parse reads each field at a fixed width, so '2024-1-2' fails at
// the month, '24-01-02' at the year, and a signed or five-digit year at
// the first byte that is not a digit where one belongs — every spelling
// that would sort in the wrong place is refused before a Date is built.
//
// That leaves the range bounded at one end only, which is measured
// rather than an oversight. A year over 9999 needs a fifth digit and a
// year before 1 CE needs a sign, and the layout refuses both; year 0 is
// the one out-of-range year spelled with four unsigned digits, so it is
// the only one that reaches here, and it is what this bound is for.
func agtypeDate(raw []byte) (Date, error) {
	text, err := agtypeString(raw)
	if err != nil {
		return Date{}, err
	}
	at, err := time.Parse(agtypeDateLayout, text)
	if err != nil {
		return Date{}, fmt.Errorf("gqlc: %q is not a date in zero-padded ISO YYYY-MM-DD form: %w", text, err)
	}
	if at.Year() < 1 {
		return Date{}, fmt.Errorf("gqlc: %q is outside the year 1 to year 9999 range this encoding admits", text)
	}
	return Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}, nil
}

// agtypeSpan reports where the value at the front of b ends: the offset
// of the first stop byte outside any nested structure, or len(b) when
// there is none. A string, a nested map and a nested list are each
// stepped over whole, so a delimiter one of them contains ends nothing.
func agtypeSpan(b []byte, stop byte) (int, error) {
	depth := 0
	for i := 0; i < len(b); i++ {
		if b[i] == '"' {
			for i++; i < len(b) && b[i] != '"'; i++ {
				if b[i] == '\\' {
					i++
				}
			}
			if i >= len(b) {
				return 0, fmt.Errorf("gqlc: %q leaves a string unterminated", b)
			}
			continue
		}
		if depth == 0 && b[i] == stop {
			return i, nil
		}
		switch b[i] {
		case '{', '[':
			depth++
		case '}', ']':
			depth--
			if depth < 0 {
				return 0, fmt.Errorf("gqlc: %q closes a structure it never opened", b)
			}
		}
	}
	if depth != 0 {
		return 0, fmt.Errorf("gqlc: %q leaves a structure open", b)
	}
	return len(b), nil
}

// agtypeObject splits an agtype map into its members, each key holding
// the undecoded text of its value. A map carries more than the schema
// declares: AGE stores whatever a writer wrote, so a value here may be of
// a shape no helper in this package reads, and only the ones a field asks
// for are ever decoded.
func agtypeObject(raw []byte) (map[string][]byte, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype map", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make(map[string][]byte)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		member := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])

		at, err := agtypeSpan(member, ':')
		if err != nil {
			return nil, err
		}
		if at == len(member) {
			return nil, fmt.Errorf("gqlc: %q is not a key and a value", member)
		}
		key, err := agtypeString(bytes.TrimSpace(member[:at]))
		if err != nil {
			return nil, err
		}
		out[key] = bytes.TrimSpace(member[at+1:])
	}
	return out, nil
}

// agtypeEntity splits an agtype vertex or edge into the label it carries
// and the undecoded text of each of its properties. A vertex and an edge
// are the same object but for the annotation, so requiring the one the
// caller named is what stands between an edge's decoder and a vertex
// whose label happens to match it.
func agtypeEntity(raw []byte, annotation string) (string, map[string][]byte, error) {
	body, ok := bytes.CutSuffix(bytes.TrimSpace(raw), []byte(annotation))
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q does not carry the %s annotation", raw, annotation)
	}
	fields, err := agtypeObject(body)
	if err != nil {
		return "", nil, err
	}
	rawLabel, ok := fields["label"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no label", raw)
	}
	label, err := agtypeString(rawLabel)
	if err != nil {
		return "", nil, err
	}
	rawProps, ok := fields["properties"]
	if !ok {
		return "", nil, fmt.Errorf("gqlc: %q carries no properties", raw)
	}
	props, err := agtypeObject(rawProps)
	if err != nil {
		return "", nil, err
	}
	return label, props, nil
}

// agtypeList decodes an agtype list, reading each element through the
// decoder the caller supplies. The split steps over a nested string, map
// or list whole, so a comma inside one separates nothing; an element the
// decoder refuses fails the whole list rather than being dropped or
// zeroed, because a slice one element short is not the value the graph
// holds.
//
// The empty list decodes to a slice of length zero and not to nil: AGE
// stores it as a value, and a nil slice is what an absent property
// reaches the caller as.
func agtypeList[T any](raw []byte, decode func([]byte) (T, error)) ([]T, error) {
	body := bytes.TrimSpace(raw)
	if len(body) < 2 || body[0] != '[' || body[len(body)-1] != ']' {
		return nil, fmt.Errorf("gqlc: %q is not an agtype list", raw)
	}
	body = bytes.TrimSpace(body[1 : len(body)-1])
	out := make([]T, 0)
	for len(body) > 0 {
		end, err := agtypeSpan(body, ',')
		if err != nil {
			return nil, err
		}
		elem := bytes.TrimSpace(body[:end])
		body = bytes.TrimSpace(body[min(end+1, len(body)):])
		value, err := decode(elem)
		if err != nil {
			return nil, fmt.Errorf("gqlc: element %d of %q: %w", len(out), raw, err)
		}
		out = append(out, value)
	}
	return out, nil
}

// agtypeListOfRecord4329c440 decodes an agtype list of record4329c440 elements.
func agtypeListOfRecord4329c440(raw []byte) ([]struct {
	Note    *string
	ZipCode int32
}, error) {
	return agtypeList(raw, decodeRecord4329c440)
}

// agtypeRecordField reads one member of a record's map. An absent key and
// an explicit null are the same thing — no value here — and both answer
// nil, because a record spells "this field has no value" both ways and a
// reader that told them apart would report a difference the schema does
// not declare.
func agtypeRecordField[T any](fields map[string][]byte, key string, decode func([]byte) (T, error)) (*T, error) {
	raw, ok := fields[key]
	if !ok || string(bytes.TrimSpace(raw)) == "null" {
		return nil, nil
	}
	out, err := decode(raw)
	if err != nil {
		return nil, fmt.Errorf("gqlc: field %q: %w", key, err)
	}
	return &out, nil
}

// decodeRecord4329c440 checks an agtype map into a record4329c440.
func decodeRecord4329c440(raw []byte) (record4329c440, error) {
	var out record4329c440
	fields, err := agtypeObject(raw)
	if err != nil {
		return out, fmt.Errorf("decode RECORD<note STRING,zip_code INT32 NOT NULL>: %w", err)
	}
	value0, err := agtypeRecordField(fields, "note", agtypeString)
	if err != nil {
		return out, fmt.Errorf("decode RECORD<note STRING,zip_code INT32 NOT NULL>: field %q: %w", "note", err)
	}
	out.Note = value0
	value1, err := agtypeRecordField(fields, "zip_code", agtypeIntAs[int32])
	if err != nil {
		return out, fmt.Errorf("decode RECORD<note STRING,zip_code INT32 NOT NULL>: field %q: %w", "zip_code", err)
	}
	if value1 == nil {
		return out, fmt.Errorf("decode RECORD<note STRING,zip_code INT32 NOT NULL>: field %q is not null but has no value", "zip_code")
	}
	out.ZipCode = *value1
	return out, nil
}

// decodeRecordf3273f80 checks an agtype map into a recordf3273f80.
func decodeRecordf3273f80(raw []byte) (recordf3273f80, error) {
	var out recordf3273f80
	fields, err := agtypeObject(raw)
	if err != nil {
		return out, fmt.Errorf("decode RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>: %w", err)
	}
	value0, err := agtypeRecordField(fields, "label", agtypeString)
	if err != nil {
		return out, fmt.Errorf("decode RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>: field %q: %w", "label", err)
	}
	if value0 == nil {
		return out, fmt.Errorf("decode RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>: field %q is not null but has no value", "label")
	}
	out.Label = *value0
	value1, err := agtypeRecordField(fields, "opened_on", agtypeDate)
	if err != nil {
		return out, fmt.Errorf("decode RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>: field %q: %w", "opened_on", err)
	}
	if value1 == nil {
		return out, fmt.Errorf("decode RECORD<label STRING NOT NULL,opened_on DATE NOT NULL>: field %q is not null but has no value", "opened_on")
	}
	out.OpenedOn = *value1
	return out, nil
}

// agtypeProperty reads one property the schema declares NOT NULL out of a
// split entity. AGE drops a property whose value is null, so an absent
// key is how a null arrives, and taking the Go zero for one would report
// absence as a value the graph holds.
func agtypeProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (T, error) {
	raw, ok := props[key]
	if !ok {
		var zero T
		return zero, fmt.Errorf("gqlc: property %q is absent", key)
	}
	return decode(raw)
}

// agtypeNullableProperty reads one nullable property out of a split
// entity, where the absence agtypeProperty refuses is the schema's null
// and reaches the caller as the nil pointer.
func agtypeNullableProperty[T any](props map[string][]byte, key string, decode func([]byte) (T, error)) (*T, error) {
	raw, ok := props[key]
	if !ok {
		return nil, nil
	}
	out, err := decode(raw)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
