// Code generated by gqlc dev. DO NOT EDIT.

package recordproperty

import (
	"context"
	"fmt"
)

const dwellingWholeQueryText = `MATCH (d:Dwelling) RETURN d`

// DwellingWhole executes the DwellingWhole query.
//
//	MATCH (d:Dwelling) RETURN d
func (q *queries) DwellingWhole(ctx context.Context) (Dwelling, error) {
	stmt, err := q.cypherStmt("$gqlc$", dwellingWholeQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return Dwelling{}, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return Dwelling{}, fmt.Errorf("DwellingWhole: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return Dwelling{}, fmt.Errorf("DwellingWhole: %w", err)
		}
		return Dwelling{}, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return Dwelling{}, fmt.Errorf("DwellingWhole: scan row: %w", err)
	}
	if rows.Next() {
		return Dwelling{}, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return Dwelling{}, fmt.Errorf("DwellingWhole: %w", err)
	}
	if raw0 == nil {
		return Dwelling{}, fmt.Errorf("DwellingWhole: column %q is non-nullable but arrived null", "d")
	}
	value0, err := decodeDwelling(raw0)
	if err != nil {
		return Dwelling{}, fmt.Errorf("DwellingWhole: decode column %q: %w", "d", err)
	}
	return value0, nil
}

const dwellingColumnsQueryText = `MATCH (d:Dwelling) RETURN d.home AS home, d.prior AS prior, d.moves AS moves, d.opened AS opened`

type DwellingColumnsRow struct {
	Home struct {
		Note    *string
		ZipCode int32
	}
	Prior *struct {
		Note    *string
		ZipCode int32
	}
	Moves *[]struct {
		Note    *string
		ZipCode int32
	}
	Opened struct {
		Label    string
		OpenedOn Date
	}
}

// DwellingColumns executes the DwellingColumns query.
//
//	MATCH (d:Dwelling) RETURN d.home AS home, d.prior AS prior, d.moves AS moves, d.opened AS opened
func (q *queries) DwellingColumns(ctx context.Context) ([]DwellingColumnsRow, error) {
	stmt, err := q.cypherStmt("$gqlc$", dwellingColumnsQueryText, "v0 ag_catalog.agtype, v1 ag_catalog.agtype, v2 ag_catalog.agtype, v3 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("DwellingColumns: %w", err)
	}
	defer rows.Close()
	out := make([]DwellingColumnsRow, 0)
	for rows.Next() {
		var raw0 []byte
		var raw1 []byte
		var raw2 []byte
		var raw3 []byte
		if err := rows.Scan(&raw0, &raw1, &raw2, &raw3); err != nil {
			return nil, fmt.Errorf("DwellingColumns: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("DwellingColumns: column %q is non-nullable but arrived null", "home")
		}
		value0, err := decodeRecord4329c440(raw0)
		if err != nil {
			return nil, fmt.Errorf("DwellingColumns: decode column %q: %w", "home", err)
		}
		var value1 *struct {
			Note    *string
			ZipCode int32
		}
		if raw1 != nil {
			decoded, err := decodeRecord4329c440(raw1)
			if err != nil {
				return nil, fmt.Errorf("DwellingColumns: decode column %q: %w", "prior", err)
			}
			value1 = &decoded
		}
		var value2 *[]struct {
			Note    *string
			ZipCode int32
		}
		if raw2 != nil {
			decoded, err := agtypeListOfRecord4329c440(raw2)
			if err != nil {
				return nil, fmt.Errorf("DwellingColumns: decode column %q: %w", "moves", err)
			}
			value2 = &decoded
		}
		if raw3 == nil {
			return nil, fmt.Errorf("DwellingColumns: column %q is non-nullable but arrived null", "opened")
		}
		value3, err := decodeRecordf3273f80(raw3)
		if err != nil {
			return nil, fmt.Errorf("DwellingColumns: decode column %q: %w", "opened", err)
		}
		out = append(out, DwellingColumnsRow{
			Home:   value0,
			Prior:  value1,
			Moves:  value2,
			Opened: value3,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("DwellingColumns: %w", err)
	}
	return out, nil
}
