// Code generated by gqlc dev. DO NOT EDIT.

package entitynullablenode

import (
	"context"
	"fmt"
)

const maybePersonQueryText = `OPTIONAL MATCH (p:Person) RETURN p`

// MaybePerson executes the MaybePerson query.
//
//	OPTIONAL MATCH (p:Person) RETURN p
func (q *Queries) MaybePerson(ctx context.Context) (*Person, error) {
	stmt, err := q.cypherStmt("$gqlc$", maybePersonQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, "{}")
	if err != nil {
		return nil, fmt.Errorf("MaybePerson: %w", err)
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("MaybePerson: %w", err)
		}
		return nil, ErrNoRows
	}
	var raw0 []byte
	if err := rows.Scan(&raw0); err != nil {
		return nil, fmt.Errorf("MaybePerson: scan row: %w", err)
	}
	if rows.Next() {
		return nil, ErrMultipleResults
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("MaybePerson: %w", err)
	}
	var value0 *Person
	if raw0 != nil {
		decoded, err := decodePerson(raw0)
		if err != nil {
			return nil, fmt.Errorf("MaybePerson: decode column %q: %w", "p", err)
		}
		value0 = &decoded
	}
	return value0, nil
}
