// Code generated by gqlc dev. DO NOT EDIT.

package listunknown

import "context"

type ReadQuerier interface {
	OneUnknownList(ctx context.Context) ([]any, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
