// Code generated by gqlc dev. DO NOT EDIT.

package listunknown

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const oneUnknownListQueryText = `MATCH (p:Person) RETURN [foo(p.id)] AS xs`

// OneUnknownList executes the OneUnknownList query.
//
//	MATCH (p:Person) RETURN [foo(p.id)] AS xs
func (q *Queries) OneUnknownList(ctx context.Context) ([]any, error) {
	records, err := q.db.run(ctx, oneUnknownListQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, ErrNoRows
	}
	if len(records) > 1 {
		return nil, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[[]any](records[0], "xs")
	if err != nil {
		return nil, fmt.Errorf("OneUnknownList: decode column %q: %w", "xs", err)
	}
	if isNil {
		return nil, fmt.Errorf("OneUnknownList: column %q is non-nullable but arrived null", "xs")
	}
	acc := make([]any, 0, len(value))
	for _, elem := range value {
		acc = append(acc, elem)
	}
	return acc, nil
}
