// Code generated by gqlc dev. DO NOT EDIT.

package schemalistanyproperty

import "context"

type ReadQuerier interface {
	Bins(ctx context.Context) ([]Bin, error)
	BinById(ctx context.Context, arg int64) (Bin, error)
	BinColumns(ctx context.Context) ([]BinColumnsRow, error)
}

type WriteQuerier interface {
}

type Querier interface {
	ReadQuerier
	WriteQuerier
}

var _ Querier = (*Queries)(nil)
var _ Querier = (*Tx)(nil)
