// Code generated by gqlc dev. DO NOT EDIT.

package twodateparams

import (
	"encoding/json"
	"fmt"
	"time"
)

// Event corresponds to the Event node type.
type Event struct {
	Created Date
	Id      int64
	Name    string
}

// agtypeArgs renders a query's bound parameters as the single agtype
// argument cypher() takes. The value crosses as a Go string: agtype's
// OID is assigned per database, so pgx holds no registered codec for it
// and sends a string as an untyped literal, which is the form agtype's
// input function reads. JSON is a subset of agtype's own text syntax, so
// what the encoder produces is text AGE parses.
func agtypeArgs(args map[string]any) (string, error) {
	out, err := json.Marshal(args)
	if err != nil {
		return "", fmt.Errorf("gqlc: encode query parameters: %w", err)
	}
	return string(out), nil
}

// agtypeString decodes an agtype string scalar. AGE renders one as a
// JSON string, escapes included, so the JSON decoder reads it back
// exactly; it also refuses every other agtype scalar, which is what
// stops a mis-shaped projection arriving as a plausible value.
//
// The target is a pointer because that is what separates the two shapes
// the decoder would otherwise agree on: unmarshalling a JSON null into a
// string succeeds and leaves it empty, so an agtype null would reach a
// non-nullable column as "".
func agtypeString(raw []byte) (string, error) {
	var out *string
	if err := json.Unmarshal(raw, &out); err != nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string: %w", raw, err)
	}
	if out == nil {
		return "", fmt.Errorf("gqlc: %q is not an agtype string", raw)
	}
	return *out, nil
}

// agtypeDateLayout is the stored form of a DATE, in the reference time
// every Go layout is written in. Zero-padded and four-digit: both halves
// are load-bearing, because they are the whole of why the stored strings
// sort chronologically.
const agtypeDateLayout = "2006-01-02"

// agtypeDateText encodes a DATE into the string a query binds it as, the
// same text agtypeDate reads back.
//
// It fails rather than encodes twice over. A year outside
// [0001, 9999] has no zero-padded four-digit spelling, and the string it
// would get instead sorts in the wrong place — which is the one property
// the whole encoding rests on, so storing it would put a value in the
// column that silently breaks every ORDER BY over it. A Year, Month and
// Day naming no day on the calendar fails for the narrower reason that
// agtypeDate would refuse to read it back: time.Date rolls February 30th
// forward to March 2nd, and a round trip that returns a different date
// than it stored is not one.
func agtypeDateText(d Date) (string, error) {
	if d.Year < 1 || d.Year > 9999 {
		return "", fmt.Errorf(
			"gqlc: year %d is outside the year 1 to year 9999 range this encoding admits", d.Year)
	}
	at := time.Date(d.Year, time.Month(d.Month), d.Day, 0, 0, 0, 0, time.UTC)
	if (Date{Year: at.Year(), Month: int(at.Month()), Day: at.Day()}) != d {
		return "", fmt.Errorf(
			"gqlc: year %d month %d day %d is not a date on the calendar", d.Year, d.Month, d.Day)
	}
	return at.Format(agtypeDateLayout), nil
}
