// Code generated by gqlc dev. DO NOT EDIT.

package twodateparams

import (
	"context"
	"fmt"
)

const eventsInRangeQueryText = `MATCH (e:Event) WHERE e.created >= $from AND e.created <= $to RETURN e.name AS name`

type EventsInRangeParams struct {
	From Date
	To   Date
}

// EventsInRange executes the EventsInRange query.
//
//	MATCH (e:Event) WHERE e.created >= $from AND e.created <= $to RETURN e.name AS name
func (q *Queries) EventsInRange(ctx context.Context, arg EventsInRangeParams) ([]string, error) {
	stmt, err := q.cypherStmt("$gqlc$", eventsInRangeQueryText, "v0 ag_catalog.agtype")
	if err != nil {
		return nil, err
	}
	param0, err := agtypeDateText(arg.From)
	if err != nil {
		return nil, fmt.Errorf("EventsInRange: parameter $from: %w", err)
	}
	param1, err := agtypeDateText(arg.To)
	if err != nil {
		return nil, fmt.Errorf("EventsInRange: parameter $to: %w", err)
	}
	args, err := agtypeArgs(map[string]any{"from": param0, "to": param1})
	if err != nil {
		return nil, err
	}
	rows, err := q.db.Query(ctx, stmt, args)
	if err != nil {
		return nil, fmt.Errorf("EventsInRange: %w", err)
	}
	defer rows.Close()
	out := make([]string, 0)
	for rows.Next() {
		var raw0 []byte
		if err := rows.Scan(&raw0); err != nil {
			return nil, fmt.Errorf("EventsInRange: scan row: %w", err)
		}
		if raw0 == nil {
			return nil, fmt.Errorf("EventsInRange: column %q is non-nullable but arrived null", "name")
		}
		value0, err := agtypeString(raw0)
		if err != nil {
			return nil, fmt.Errorf("EventsInRange: decode column %q: %w", "name", err)
		}
		out = append(out, value0)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("EventsInRange: %w", err)
	}
	return out, nil
}
