// Code generated by gqlc dev. DO NOT EDIT.

package allwidths

import (
	"context"
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

const allWidthsQueryText = `MATCH (r:Row) RETURN r.s, r.b, r.i, r.i8, r.i16, r.i32, r.i64, r.u, r.u8, r.u16, r.u32, r.u64, r.f, r.f32, r.f64`

type AllWidthsRow struct {
	S   string
	B   bool
	I   int
	I8  int8
	I16 int16
	I32 int32
	I64 int64
	U   uint
	U8  uint8
	U16 uint16
	U32 uint32
	U64 uint64
	F   float64
	F32 float32
	F64 float64
}

// AllWidths executes the AllWidths query.
//
//	MATCH (r:Row) RETURN r.s, r.b, r.i, r.i8, r.i16, r.i32, r.i64, r.u, r.u8, r.u16, r.u32, r.u64, r.f, r.f32, r.f64
func (q *queries) AllWidths(ctx context.Context) (AllWidthsRow, error) {
	records, err := q.db.run(ctx, allWidthsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return AllWidthsRow{}, err
	}
	if len(records) == 0 {
		return AllWidthsRow{}, ErrNoRows
	}
	if len(records) > 1 {
		return AllWidthsRow{}, ErrMultipleResults
	}
	var row AllWidthsRow
	value0, isNil, err := neo4j.GetRecordValue[string](records[0], "r.s")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.s", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.s")
	}
	row.S = value0
	value1, isNil, err := neo4j.GetRecordValue[bool](records[0], "r.b")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.b", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.b")
	}
	row.B = value1
	value2, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.i")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.i")
	}
	value2n, err := narrowInt[int](value2)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i", err)
	}
	row.I = value2n
	value3, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.i8")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i8", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.i8")
	}
	value3n, err := narrowInt[int8](value3)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i8", err)
	}
	row.I8 = value3n
	value4, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.i16")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i16", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.i16")
	}
	value4n, err := narrowInt[int16](value4)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i16", err)
	}
	row.I16 = value4n
	value5, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.i32")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i32", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.i32")
	}
	value5n, err := narrowInt[int32](value5)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i32", err)
	}
	row.I32 = value5n
	value6, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.i64")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.i64", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.i64")
	}
	row.I64 = value6
	value7, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.u")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.u")
	}
	value7n, err := narrowInt[uint](value7)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u", err)
	}
	row.U = value7n
	value8, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.u8")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u8", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.u8")
	}
	value8n, err := narrowInt[uint8](value8)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u8", err)
	}
	row.U8 = value8n
	value9, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.u16")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u16", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.u16")
	}
	value9n, err := narrowInt[uint16](value9)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u16", err)
	}
	row.U16 = value9n
	value10, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.u32")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u32", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.u32")
	}
	value10n, err := narrowInt[uint32](value10)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u32", err)
	}
	row.U32 = value10n
	value11, isNil, err := neo4j.GetRecordValue[int64](records[0], "r.u64")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u64", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.u64")
	}
	value11n, err := narrowInt[uint64](value11)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.u64", err)
	}
	row.U64 = value11n
	value12, isNil, err := neo4j.GetRecordValue[float64](records[0], "r.f")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.f", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.f")
	}
	row.F = value12
	value13, isNil, err := neo4j.GetRecordValue[float64](records[0], "r.f32")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.f32", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.f32")
	}
	value13n, err := narrowFloat32(value13)
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.f32", err)
	}
	row.F32 = value13n
	value14, isNil, err := neo4j.GetRecordValue[float64](records[0], "r.f64")
	if err != nil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: decode column %q: %w", "r.f64", err)
	}
	if isNil {
		return AllWidthsRow{}, fmt.Errorf("AllWidths: column %q is non-nullable but arrived null", "r.f64")
	}
	row.F64 = value14
	return row, nil
}
