// Code generated by gqlc dev. DO NOT EDIT.

package timestampprojection

import (
	"context"
	"fmt"
	"time"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

const readingAtQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r.takenAt AS takenAt`

// ReadingAt executes the ReadingAt query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r.takenAt AS takenAt
func (q *Queries) ReadingAt(ctx context.Context, id int64) (time.Time, error) {
	records, err := q.db.run(ctx, readingAtQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return time.Time{}, err
	}
	if len(records) == 0 {
		return time.Time{}, ErrNoRows
	}
	if len(records) > 1 {
		return time.Time{}, ErrMultipleResults
	}
	value, isNil, err := neo4j.GetRecordValue[time.Time](records[0], "takenAt")
	if err != nil {
		return time.Time{}, fmt.Errorf("ReadingAt: decode column %q: %w", "takenAt", err)
	}
	if isNil {
		return time.Time{}, fmt.Errorf("ReadingAt: column %q is non-nullable but arrived null", "takenAt")
	}
	return value, nil
}

const oneReadingQueryText = `MATCH (r:Reading) WHERE r.id = $id RETURN r`

// OneReading executes the OneReading query.
//
//	MATCH (r:Reading) WHERE r.id = $id RETURN r
func (q *Queries) OneReading(ctx context.Context, id int64) (Reading, error) {
	records, err := q.db.run(ctx, oneReadingQueryText, map[string]any{"id": id}, neo4j.AccessModeRead)
	if err != nil {
		return Reading{}, err
	}
	if len(records) == 0 {
		return Reading{}, ErrNoRows
	}
	if len(records) > 1 {
		return Reading{}, ErrMultipleResults
	}
	node, isNil, err := neo4j.GetRecordValue[dbtype.Node](records[0], "r")
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: decode column %q: %w", "r", err)
	}
	if isNil {
		return Reading{}, fmt.Errorf("OneReading: column %q is non-nullable but arrived null", "r")
	}
	value, err := decodeReading(node)
	if err != nil {
		return Reading{}, fmt.Errorf("OneReading: decode column %q: %w", "r", err)
	}
	return value, nil
}

const allReadingsQueryText = `MATCH (r:Reading) RETURN r.takenAt AS takenAt ORDER BY r.takenAt`

// AllReadings executes the AllReadings query.
//
//	MATCH (r:Reading) RETURN r.takenAt AS takenAt ORDER BY r.takenAt
func (q *Queries) AllReadings(ctx context.Context) ([]time.Time, error) {
	records, err := q.db.run(ctx, allReadingsQueryText, nil, neo4j.AccessModeRead)
	if err != nil {
		return nil, err
	}
	out := make([]time.Time, 0, len(records))
	for _, record := range records {
		value, isNil, err := neo4j.GetRecordValue[time.Time](record, "takenAt")
		if err != nil {
			return nil, fmt.Errorf("AllReadings: decode column %q: %w", "takenAt", err)
		}
		if isNil {
			return nil, fmt.Errorf("AllReadings: column %q is non-nullable but arrived null", "takenAt")
		}
		out = append(out, value)
	}
	return out, nil
}
