// Code generated by gqlc dev. DO NOT EDIT.

package nullablecolumns

import (
	"fmt"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j/dbtype"
)

// Person corresponds to the Person node type.
type Person struct {
	Age      *int64
	Id       int64
	Name     string
	Nickname *string
}

// decodePerson decodes a driver dbtype.Node into a Person struct,
// enforcing per-property nullability against the schema.
func decodePerson(node dbtype.Node) (Person, error) {
	var out Person
	if v, ok := node.Props["age"]; ok {
		s, ok := v.(int64)
		if !ok {
			return Person{}, fmt.Errorf("decode Person.Age: property %q: expected int64, got %T", "age", v)
		}
		out.Age = &s
	}
	id, err := neo4j.GetProperty[int64](node, "id")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Id: %w", err)
	}
	out.Id = id
	name, err := neo4j.GetProperty[string](node, "name")
	if err != nil {
		return Person{}, fmt.Errorf("decode Person.Name: %w", err)
	}
	out.Name = name
	if v, ok := node.Props["nickname"]; ok {
		s, ok := v.(string)
		if !ok {
			return Person{}, fmt.Errorf("decode Person.Nickname: property %q: expected string, got %T", "nickname", v)
		}
		out.Nickname = &s
	}
	return out, nil
}
